### ISSUE TITLE
CI failures: use after dispose + undefined telemetryEnabled

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1071]
* [travis](https://travis-ci.org/github/aws/aws-toolkit-vscode/builds/682180650) and [CodeBuild](https://github.com/aws/aws-toolkit-vscode/pull/1070) failures seem to be due to a use-after-dispose scenario with web views.

  * `SEGV_MAPERR` is observed which causes the tests to fail with result code `null`
  * Suspected to be a race condition where [`debouncedUpdate`](https://github.com/aws/aws-toolkit-vscode/blob/master/src/stepFunctions/commands/visualizeStateMachine/aslVisualization.ts#L116) is called between a `dispose` and firing of [`onDidDispose`](https://github.com/aws/aws-toolkit-vscode/blob/master/src/stepFunctions/commands/visualizeStateMachine/aslVisualization.ts#L156). `dispose` in the parent simply fires and forgets the event emitter. It doesn't wait for event handlers to complete before disposing.
  * Probably possible to override `dispose` to ensure that the `isDisposed` flag is updated before disposal

* `telemetryEnabled` exception is logged  but **does not fail the build**
  * Due to `onDidChangeConfiguration` firing for telemetry during telemetry unit testing and expecting it to be set
```
rejected promise not handled within 1 second: TypeError: Cannot set property 'telemetryEnabled' of undefined
stack trace: TypeError: Cannot set property 'telemetryEnabled' of undefined
    at applyTelemetryEnabledState (/Users/travis/build/aws/aws-toolkit-vscode/dist/src/shared/telemetry/activation.js:9:5779)
    at Object.<anonymous> (/Users/travis/build/aws/aws-toolkit-vscode/dist/src/shared/telemetry/activation.js:9:4573)
    at Generator.next (<anonymous>)
    at /Users/travis/build/aws/aws-toolkit-vscode/dist/src/shared/telemetry/activation.js:9:1746
    at new Promise (<anonymous>)
    at __awaiter (/Users/travis/build/aws/aws-toolkit-vscode/dist/src/shared/telemetry/activation.js:9:662)
    at /Users/travis/build/aws/aws-toolkit-vscode/dist/src/shared/telemetry/activation.js:9:4183
    at e.fire (/Users/travis/build/aws/aws-toolkit-vscode/.vscode-test/vscode-1.44.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
    at E.$acceptConfigurationChanged (/Users/travis/build/aws/aws-toolkit-vscode/.vscode-test/vscode-1.44.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:778:32)
    at /Users/travis/build/aws/aws-toolkit-vscode/.vscode-test/vscode-1.44.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:262
      ✓ detects running processes and successfully sends a kill signal to a running process - Unix (127ms)
      ✓ can not kill previously killed processes - Unix (226ms)
  CollectionUtils
```

**Comment by justinmk3** [comment]
this avoids the issue: https://github.com/aws/aws-toolkit-vscode/pull/1070/commits/da015575876a5b52c0c2f2262b9afee482f51468

```diff

diff --git a/src/shared/telemetry/activation.ts b/src/shared/telemetry/activation.ts
index a6c75b99..a68f35b9 100644
--- a/src/shared/telemetry/activation.ts
+++ b/src/shared/telemetry/activation.ts
@@ -54,6 +54,9 @@ export async function activate(activateArguments: {
     // When there are configuration changes, update the telemetry service appropriately
     vscode.workspace.onDidChangeConfiguration(
         async event => {
+            if (!ext.telemetry) {
+                return
+            }
             if (
                 event.affectsConfiguration('telemetry.enableTelemetry') ||
                 event.affectsConfiguration('aws.telemetry')
```

**Comment by justinmk3** [comment]
Haven't seen this for 6+ months.
