### ISSUE TITLE
CI test matrix failures

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1207]
CI test matrix has some know failures with certain vscode variants.

### Related

- Hang at `getmac.exe` message (**update:** this error isn't the cause of the hang, just happens to be the last message printed)
  - https://github.com/microsoft/vscode-remote-release/issues/2719
  - https://github.com/aws/aws-toolkit-vscode/pull/1193#issuecomment-659490004
  - https://github.com/microsoft/vscode/issues/102428
  - Fixed the `getmac.exe` error (by installing `getmac.exe` in CI), but doesn't actually fix our builds: https://github.com/aws/aws-toolkit-vscode/issues/1207#issuecomment-666609262
- https://github.com/aws/aws-toolkit-vscode/issues/1201 ?
- https://github.com/aws/aws-toolkit-vscode/issues/1071 ?

### Exit code -4058

- Exit code `-4058` indicates a node.js crash/segfault. This is strictly a node.js bug, but we need to either work around it or root-cause it and report it upstream.
- observed in CI jobs:
  - `Windows Unit Tests [insiders]`

```
Starting tests: C:\codebuild\tmp\output\src630281967\src\github.com\aws\aws-toolkit-vscode-staging\dist\src\test\index.js
Test error: Error: spawn C:\codebuild\tmp\output\src630281967\src\github.com\aws\aws-toolkit-vscode-staging\.vscode-test\vscode-insiders\Code - Insiders.exe ENOENT
Exit code:   -4058
```

### Exit code 3221226356

- commit https://github.com/aws/aws-toolkit-vscode/commit/e691811d87f00050450f4973181578961e5e9467 (2020-08-17)
- Windows CI job failure `Exit code:   3221226356` ([heap corruption](https://stackoverflow.com/questions/54209937/the-terminal-process-terminated-with-exit-code-3221226356#comment95260108_54209937))
  ```
    Cannot read property 'toJSON' of null: TypeError: Cannot read property 'toJSON' of null
        at file:///C:/codebuild/tmp/output/src125341715/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-1.48.0/resources/app/out/vs/workbench/workbench.desktop.main.js:3930:297
        at Array.map (<anonymous>)
        at file:///C:/codebuild/tmp/output/src125341715/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-1.48.0/resources/app/out/vs/workbench/workbench.desktop.main.js:3930:288
      TypescriptLambdaHandlerSearch
        √ finds export declared functions in Typescript code
        √ ignores class declarations in Typescript code
        √ ignores interface declarations in Typescript code
        √ finds module.exports declared functions in javascript code
        √ ignores class declarations in javascript code
      1158 passing (16s)
    [main 2020-08-18T00:53:33.744Z] Lifecycle#kill()
    [main 2020-08-18T00:53:33.747Z] Lifecycle#window.on('closed') - window ID 1
    [main 2020-08-18T00:53:33.747Z] Lifecycle#onWillShutdown.fire()
    [main 2020-08-18T00:53:33.749Z] Lifecycle#app.on(window-all-closed)
    [main 2020-08-18T00:53:33.750Z] Lifecycle#app.on(before-quit)
    [main 2020-08-18T00:53:33.750Z] Lifecycle#onBeforeShutdown.fire()
    [main 2020-08-18T00:53:33.757Z] onBeforeShutdown {
      lastActiveWindow: undefined,
      lastPluginDevelopmentHostWindow: undefined,
      openedWindows: []
    }
    [main 2020-08-18T00:53:33.757Z] Lifecycle#app.on(will-quit)
    [main 2020-08-18T00:53:33.765Z] [storage :memory:] close()
    Exit code:   3221226356
  ```

### ~~Error: TypeError~~ Fixed

- observed in CI jobs:
  - `Windows Unit Tests [insiders]` https://github.com/aws/aws-toolkit-vscode/pull/1206:
- **Fixed:** pulling newer VSCode versions (instead of pinning to 1.46) fixes the `ERR_INVALID_ARG_TYPE` error.

```
[main 2020-07-23T16:03:32.425Z] update#setState idle
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at h._doHandleExtensionTests (c:\codebuild\tmp\output\src251412895\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:885)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
native-keymap: Could not create ITfThreadMgr.
Exit code:   1
...
npm ERR! aws-toolkit-vscode@1.12.0-SNAPSHOT test: `npm run testCompile && ts-node ./test-scripts/test.ts`
```

**Comment by justinmk3** [comment]
Fixed by https://github.com/microsoft/vscode/issues/102642 :

> ERR_INVALID_ARG_TYPE when testing extension on 1.47.1

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1222 shows that

- "insiders" build is currently https://github.com/microsoft/vscode/commit/15e798e081984a17eae00de91adf4479190d5ed2  
- "stable" build is currently https://github.com/microsoft/vscode/commit/91899dcef7b8110878ea59626991a18c8a6a1b3e which includes the fix https://github.com/microsoft/vscode/pull/102966

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1223 (commit: https://github.com/aws/aws-toolkit-vscode/pull/1223/commits/25d143fc7858fce943285c374d5059247baf9c05) demonstrates that installing `pip install getmac` avoids the `getmac.exe` error. But that doesn't solve any of the CI job failures:

- the `Windows Unit Tests [insiders]` job still fails with:
   ```
   native-keymap: Could not create ITfThreadMgr.
   Exit code:   1
   ```
- the `Windows Unit Tests [stable]` job still hangs

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/1223 passes after rebasing onto https://github.com/aws/aws-toolkit-vscode/pull/1241

**Comment by justinmk3** [comment]
- Most issues tracked here were fixed, and CI is fairly stable now.
- Some unreliable tests are tracked in separate issues: https://github.com/aws/aws-toolkit-vscode/issues?q=is%3Aissue+is%3Aopen+test+in%3Atitle
- Still seeing infrequent `Exit code 3221226356` failure in some PRs, but that is a nodejs crash. Individual flaky tests are covered in separate issues as mentioned above.
