### ISSUE TITLE
unreliable test: "ChildProcess runs and captures stdout - unix"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1233]
- vscode version: `1.47.3`
- observed in https://github.com/aws/aws-toolkit-vscode-staging/commit/993c7de8eb1e1ad29a4f8806961fda90a9917178

```
  ChildProcess
    run
this.onSuccess is not a function: TypeError: this.onSuccess is not a function
    at Timeout._onTimeout (/codebuild/output/src250312244/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-1.47.3/VSCode-linux-x64/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain.js:1:228177)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
      1) runs and captures stdout - unix
      2) runs and captures stdout - unix

...

Cannot read property 'toJSON' of null: TypeError: Cannot read property 'toJSON' of null
    at file:///codebuild/output/src250312244/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-1.47.3/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:3858:711
    at Array.map (<anonymous>)
    at file:///codebuild/output/src250312244/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-1.47.3/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:3858:702

...

  1151 passing (9s)
  2 failing
  1) ChildProcess
       run
         runs and captures stdout - unix:
     Uncaught TypeError: this.onSuccess is not a function
      at Timeout._onTimeout (.vscode-test/vscode-1.47.3/VSCode-linux-x64/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain.js:1:228177)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
  2) ChildProcess
       run
         runs and captures stdout - unix:
     Uncaught TypeError: this.onSuccess is not a function
      at Timeout._onTimeout (.vscode-test/vscode-1.47.3/VSCode-linux-x64/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain.js:1:228177)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
Error: 2 tests failed.
```

**Comment by justinmk3** [comment]
Haven't seen this since it was reported. Internals also changed in https://github.com/aws/aws-toolkit-vscode/pull/1372
