### ISSUE TITLE
unreliable test: "IteratingQuickPickController pauses and restarts iteration"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1281]
Is there a race in this test (or the impl)? cc @bryceitoc9 

https://d1ihu6zq92vp9p.cloudfront.net/cc442eab-664c-4450-9614-e256552af10e/report.html

> IteratingQuickPickController pauses and restarts iteration

```
TypeError: this.onSuccess is not a function
    at Timeout._onTimeout (c:\codebuild\tmp\output\src366497151\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-1.42.0\resources\app\extensions\json-language-features\client\dist\jsonMain.js:9:106345)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

```
Error: done() called multiple times
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
    at process.topLevelDomainCallback (domain.js:126:23)
```

**Comment by bryceitoc9** [comment]
No idea what this is tied to. Might be an issue with `lolex` or something? Will keep an eye on it

**Comment by justinmk3** [comment]
Seems related to `sinon.SinonSandbox` not being recreated https://github.com/aws/aws-toolkit-vscode/pull/2189 , but `IteratingQuickPickController pauses and restarts iteration` looks ok: https://github.com/aws/aws-toolkit-vscode/blob/69340f4703426bf62181ca438b4954d6e6c0727f/src/test/shared/ui/picker.test.ts#L689-L691
