### ISSUE TITLE
Error while deploying SAM application using WSL2

### ISSUE THREAD

**Issue by mattgillard** [aws/aws-toolkit-vscode#1305]
While deploying a SAM application I get an error regarding the locale setting, even though this setting is set everywhere correctly.
```
Starting SAM Application deployment...
Building SAM Application...
Packaging SAM Application to S3 Bucket: mattg2019test
Error with child process: Traceback (most recent call last):
  File "/home/matt/.local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/home/matt/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/matt/.local/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/home/matt/.local/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
An error occurred while deploying a SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.

```

Manual deployment within my WSL2 shell works as expected.  It appears my shell variables are not being picked up by the extension.  In VS Code developer tools, process.env just shows Windows environment variables and not Linux ones so the required locale is not listed.

AWS Toolkit logs are not providing further clarity:
```

2020-09-21 16:31:30 [INFO]: Running command: /home/matt/.local/bin/sam --info
2020-09-21 16:32:09 [INFO]: Starting SAM Application deployment...
2020-09-21 16:32:09 [INFO]: Building SAM Application...
2020-09-21 16:32:09 [INFO]: Running command: /home/matt/.local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/samDeployWNsLsc/build --template /path/to/template.yaml
2020-09-21 16:32:12 [INFO]: Packaging SAM Application to S3 Bucket: mattg2019test
2020-09-21 16:32:12 [INFO]: Running command: /home/matt/.local/bin/sam package --template-file /tmp/aws-toolkit-vscode/samDeployWNsLsc/build/template.yaml --s3-bucket xxx --output-template-file /tmp/aws-toolkit-vscode/samDeployWNsLsc/template.yaml --region ap-southeast-2
2020-09-21 16:32:13 [ERROR]: Unexpected exitcode (1), expecting (0)
2020-09-21 16:32:13 [ERROR]: Error: undefined
2020-09-21 16:32:13 [ERROR]: stderr: Traceback (most recent call last):
  File "/home/matt/.local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/home/matt/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/matt/.local/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/home/matt/.local/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
2020-09-21 16:32:13 [ERROR]: stdout: 
2020-09-21 16:32:13 [ERROR]: Error: Error with child process: Traceback (most recent call last):
  File "/home/matt/.local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/home/matt/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/matt/.local/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/home/matt/.local/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    at Object.t.logAndThrowIfUnexpectedExitCode (/home/matt/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.13.0/dist/extension.js:2:509696)
    at Object.<anonymous> (/home/matt/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.13.0/dist/extension.js:2:6981372)
    at Generator.next (<anonymous>)
    at o (/home/matt/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.13.0/dist/extension.js:2:6980797)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
2020-09-21 16:32:13 [ERROR]: An error occurred while deploying a SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
2020-09-21 16:36:16 [INFO]: Successfully sent a telemetry batch of 11

```

**To Reproduce**

**Expected behavior**

I expect deployment to succeed as per running the SAM CLI in a WSL2 terminal window.

**Screenshots**

N/A

**Desktop (please complete the following information):**

OS:  Linux x64 4.19.128-microsoft-standard
Visual Studio Code Version:  1.49.1
AWS Toolkit Version:  1.13.0
Ubuntu 18.04
WSL2
sam --version
SAM CLI, version 1.2.0

**Additional context**

N/A

**Comment by bryceitoc9** [comment]
This looks similar to https://github.com/aws/aws-toolkit-vscode/issues/1300 ... I'm assuming that no SAM CLI-related operations are working through the toolkit? If that's the case, I'll merge these issues, and if it's not the case, can you let us know what operations are working vs. not working (run/debug uses `sam build` and `sam local invoke`, deploy uses `sam build`, `sam package`, and `sam deploy`)

**Comment by mattgillard** [comment]
No - I would keep them separate.  I actually hit that other one as well but worked around it by manually specifying the sam path.
Can confirm that run/debug worked **fine**.
```
Debugger attached.
START RequestId: 17b5f491-91fc-1b0c-b3dd-2eb1239ec2da Version: $LATEST
END RequestId: 17b5f491-91fc-1b0c-b3dd-2eb1239ec2da
REPORT RequestId: 17b5f491-91fc-1b0c-b3dd-2eb1239ec2da	Init Duration: 6012.08 ms	Duration: 10.86 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 52 MB	
```
The issue is just deploy which fails with the error in my original post.

thanks

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/issues/1300 appears to be a filesystem issue whereas this issue looks related to environment variables.

**Comment by mattgillard** [comment]
some more information.
I have replaced my ~/.local/bin/sam with a fake shell script which calls the real sam.
I captured the environment variables.

When running the problematic deploy which is after the `sam package ` command - the *only* Environment variables are:
```
AWS_SECRET_ACCESS_KEY=xx
PWD=/mnt/c/Users/matt/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.5
AWS_ACCESS_KEY=xx
AWS_SECRET_KEY=xx
AWS_ACCESS_KEY_ID=xx
SHLVL=1
```
Prior to the deployment, toolkit runs a `sam --info`, and a `sam build ` which both have all the correct variables which is why it doesn't fail earlier.
It is like toolkit has removed them all which i am not sure should be expected behavior.  
That looks like the problem.

**Comment by mattgillard** [comment]
I couldn't help myself but have a peek in the source code.  In /src/lambda/commands/deploySamApplication.ts on line 172 environment variables are passed through to sam package but they were only initialized with AWS credentials on line 86.  I guess there needs to be a merge of existing environment variables with the AWS credentials instead on that line 86.
```
const deployParameters: DeploySamApplicationParameters = {
            deployRootFolder: await makeTemporaryToolkitFolder('samDeploy'),
            destinationStackName: deployWizardResponse.stackName,
            packageBucketName: deployWizardResponse.s3Bucket,
            parameterOverrides: deployWizardResponse.parameterOverrides,
            environmentVariables: asEnvironmentVariables(credentials),   <-- here
            region: deployWizardResponse.region,
            sourceTemplatePath: deployWizardResponse.template.fsPath,
        }
```

**Comment by patricknazar** [comment]
This should be an easy fix, please prioritize this
