### ISSUE TITLE
CI failure: "TypeError: e.replace is not a function"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1360]
`Windows Unit Tests [insiders]` job started failing today.

observed in

- https://github.com/aws/aws-toolkit-vscode/pull/1357
- https://github.com/aws/aws-toolkit-vscode/pull/1358

```
  1) DefaultSamDeployWizardContext
       promptUserForS3Bucket
         returns an s3 bucket name:
     TypeError: e.replace is not a function
      at Function.file (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:279)
      at p (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:270)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:104
      at h (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:147)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:795
      at Array.map (<anonymous>)
      at m.set buttons [as buttons] (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:773)
      at Object.createQuickPick (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\shared\ui\picker.js:9:4029)
      at DefaultSamDeployWizardContext.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:13143)
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:1746
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:662)
      at DefaultSamDeployWizardContext.promptUserForS3Bucket (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:12863)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\lambda\wizards\samDeployWizard.test.ts:571:42
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\lambda\wizards\samDeployWizard.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\lambda\wizards\samDeployWizard.test.js:8:12)
      at Context.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\lambda\wizards\samDeployWizard.test.ts:565:52)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)

  2) DefaultSamDeployWizardContext
       promptUserForS3Bucket
         returns undefined on receiving undefined from the picker (back button):
     TypeError: e.replace is not a function
      at Function.file (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:279)
      at p (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:270)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:104
      at h (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:147)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:795
      at Array.map (<anonymous>)
      at m.set buttons [as buttons] (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:773)
      at Object.createQuickPick (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\shared\ui\picker.js:9:4029)
      at DefaultSamDeployWizardContext.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:13143)
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:1746
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:662)
      at DefaultSamDeployWizardContext.promptUserForS3Bucket (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:12863)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\lambda\wizards\samDeployWizard.test.ts:580:42
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\lambda\wizards\samDeployWizard.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\lambda\wizards\samDeployWizard.test.js:8:12)
      at Context.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\lambda\wizards\samDeployWizard.test.ts:575:97)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)

  3) DefaultSamDeployWizardContext
       promptUserForS3Bucket
         returns undefined if the user selects a no items/error message:
     TypeError: e.replace is not a function
      at Function.file (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:279)
      at p (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:270)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:104
      at h (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:147)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:795
      at Array.map (<anonymous>)
      at m.set buttons [as buttons] (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:773)
      at Object.createQuickPick (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\shared\ui\picker.js:9:4029)
      at DefaultSamDeployWizardContext.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:13143)
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:1746
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:662)
      at DefaultSamDeployWizardContext.promptUserForS3Bucket (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\lambda\wizards\samDeployWizard.js:9:12863)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\lambda\wizards\samDeployWizard.test.ts:595:47
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\lambda\wizards\samDeployWizard.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\lambda\wizards\samDeployWizard.test.js:8:12)
      at Context.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\lambda\wizards\samDeployWizard.test.ts:584:89)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)

  4) createInputBox
       Sets buttons:
     TypeError: e.replace is not a function
      at Function.file (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:279)
      at p (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:270)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:104
      at h (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:147)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:795
      at Array.map (<anonymous>)
      at g.set buttons [as buttons] (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:773)
      at Object.createInputBox (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\shared\ui\input.js:9:2938)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\shared\ui\input.test.ts:23:27
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\shared\ui\input.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\shared\ui\input.test.js:8:12)
      at Context.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\shared\ui\input.test.ts:20:35)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)


  5) createQuickPick
       Sets buttons:
     TypeError: e.replace is not a function
      at Function.file (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:279)
      at p (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:270)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:104
      at h (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:147)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:795
      at Array.map (<anonymous>)
      at m.set buttons [as buttons] (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:773)
      at Object.createQuickPick (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\shared\ui\picker.js:9:4029)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\shared\ui\picker.test.ts:51:29
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\shared\ui\picker.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\shared\ui\picker.test.js:8:12)
      at Context.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\shared\ui\picker.test.ts:48:35)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)


  6) createDocumentFromTemplate
       open and save document based on selected template:
     TypeError: e.replace is not a function
      at Function.file (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:279)
      at p (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:270)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:104
      at h (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:147)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:795
      at Array.map (<anonymous>)
      at m.set buttons [as buttons] (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:773)
      at Object.createQuickPick (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\shared\ui\picker.js:9:4029)
      at Object.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\createDocumentFromTemplate.js:9:4058)
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\createDocumentFromTemplate.js:9:1746
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\createDocumentFromTemplate.js:9:662)
      at Object.createSsmDocumentFromTemplate (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\createDocumentFromTemplate.js:9:3656)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\ssmDocument\commands\createDocumentFromTemplate.test.ts:59:15
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\ssmDocument\commands\createDocumentFromTemplate.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\ssmDocument\commands\createDocumentFromTemplate.test.js:8:12)
      at Context.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\ssmDocument\commands\createDocumentFromTemplate.test.ts:49:72)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)

  7) publishSSMDocument
       tests calling createDocument:
     TypeError: e.replace is not a function
      at Function.file (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:279)
      at p (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:270)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:104
      at h (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:147)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:795
      at Array.map (<anonymous>)
      at m.set buttons [as buttons] (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:773)
      at Object.createQuickPick (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\shared\ui\picker.js:9:4029)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:13799
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:1746
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:662)
      at promptUserForRegion (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:13517)
      at Object.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:5521)
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:1746
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:662)
      at Object.publishSSMDocument (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:3488)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\ssmDocument\commands\publishDocument.test.ts:113:23
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\ssmDocument\commands\publishDocument.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\ssmDocument\commands\publishDocument.test.js:8:12)
      at Context.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\ssmDocument\commands\publishDocument.test.ts:104:51)


  8) publishSSMDocument
       tests calling updateDocument:
     TypeError: e.replace is not a function
      at Function.file (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:279)
      at p (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:270)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:104
      at h (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:799:147)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:795
      at Array.map (<anonymous>)
      at m.set buttons [as buttons] (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:773)
      at Object.createQuickPick (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\shared\ui\picker.js:9:4029)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:13799
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:1746
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:662)
      at promptUserForRegion (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:13517)
      at Object.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:5521)
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:1746
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:662)
      at Object.publishSSMDocument (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\ssmDocument\commands\publishDocument.js:9:3488)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\ssmDocument\commands\publishDocument.test.ts:127:23
      at Generator.next (<anonymous>)
      at c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\ssmDocument\commands\publishDocument.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\dist\src\test\ssmDocument\commands\publishDocument.test.js:8:12)
      at Context.<anonymous> (c:\codebuild\tmp\output\src911916531\src\github.com\aws\aws-toolkit-vscode\src\test\ssmDocument\commands\publishDocument.test.ts:119:51)

**Comment by justinmk3** [comment]
fixed upstream by https://github.com/microsoft/vscode/commit/41f396d722b338cad1fc4c9c3e153df2a986deee
