### ISSUE TITLE
Exception when templates.json exists, but is empty

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-vscode#1375]
```
2020-11-02 15:57:06 [ERROR]: [Error: Could not load .aws/templates.json: Error: Could not parse .aws/templates.json: value expected at offset 0, length 0
	at /Users/richali/aws-toolkit-vscode/dist/src/lambda/config/templates.js:114:19
	at Generator.next (<anonymous>)
	at fulfilled (/Users/richali/aws-toolkit-vscode/dist/src/lambda/config/templates.js:9:58)]
2020-11-02 15:57:06 [ERROR]: An error occurred while deploying a SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
```

**Comment by justinmk3** [comment]
AFAIK we have no need for `templates.json` anymore. Should remove all code related to it.

**Comment by bryceitoc9** [comment]
> 
> 
> AFAIK we have no need for `templates.json` anymore. Should remove all code related to it.

It's a compatibility case. This was our former way of passing event and env var data to SAM Local runs. We have a converter to turn that into launch config data.

**Comment by rli** [comment]
At the moment it also appears necessary for the deploy workflow, if a user specifies a template with parameters that do not have default values (not sure how common that'd be)
