### ISSUE TITLE
Failed to load endpoints manifest, using proxy

### ISSUE THREAD

**Issue by MarkMindlin** [aws/aws-toolkit-vscode#1432]
2020-12-09 09:52:46 [INFO]: log level: info
2020-12-09 09:52:46 [INFO]: Retrieving AWS endpoint data
2020-12-09 09:52:46 [INFO]: OS:  Linux x64 4.19.128-microsoft-standard
Visual Studio Code Version:  1.51.1
AWS Toolkit Version:  1.16.0

2020-12-09 09:52:48 [ERROR]: Failed to load endpoints manifest: [SyntaxError: Unexpected token < in JSON at position 0
	at JSON.parse (<anonymous>)
	at Object.t.loadEndpoints (/home/mmindlin/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.16.0/dist/extension.js:2:7842416)
	at t.EndpointsProvider.<anonymous> (/home/mmindlin/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.16.0/dist/extension.js:2:7841602)
	at Generator.next (<anonymous>)
	at o (/home/mmindlin/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.16.0/dist/extension.js:2:7840770)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
2020-12-09 09:56:23 [INFO]: Submitting Negative feedback
2020-12-09 10:01:01 [ERROR]: Error getting AccountId: [Error [TimeoutError]: Connection timed out after 120000ms
	at ClientRequest.<anonymous> (/home/mmindlin/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.16.0/dist/extension.js:2:2298991)
	at Object.onceWrapper (events.js:312:28)
	at ClientRequest.emit (events.js:223:5)
	at ClientRequest.EventEmitter.emit (domain.js:475:20)
	at Socket.emitRequestTimeout (_http_client.js:690:9)
	at Object.onceWrapper (events.js:312:28)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at Socket._onTimeout (net.js:474:8)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)] {
  message: 'Connection timed out after 120000ms',
  code: 'TimeoutError',
  time: 2020-12-08T23:01:01.157Z,
  region: 'us-east-1',
  hostname: 'sts.amazonaws.com',
  retryable: true,
  statusCode: 407
}
2020-12-09 10:01:01 [ERROR]: Error trying to connect to AWS with Credentials Provider profile:default. Toolkit will now disconnect from AWS. [Error: Could not determine Account Id for credentials
	at t.LoginManager.<anonymous> (/home/mmindlin/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.16.0/dist/extension.js:2:7376034)
	at Generator.next (<anonymous>)
	at o (/home/mmindlin/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.16.0/dist/extension.js:2:7375006)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]

**Comment by justinmk3** [comment]
> Connection timed out after 120000ms

Looks like there is a network issue. If your machine isn't having connectivity issues in general, perhaps there is a cert or proxy issue. https://github.com/aws/aws-toolkit-vscode/issues/899 https://github.com/aws/aws-toolkit-vscode/issues/185

Is the Toolkit failing to load?

**Comment by MarkMindlin** [comment]
It is not failing. It shows "Connect..." endlessly and pops up dialog "View Logs" after

Now, we 

- export HTTP_PROXY=user:pass@http://my.proxy.server:port

- export HTTPS_PROXY=user:pass@http://my.proxy.server:port

- enabled the setting in VS Code 

![image](https://user-images.githubusercontent.com/18206302/101701168-7a0abf80-3ad2-11eb-8acd-32c8c5b216b5.png)

After that, it shows list of services with errors
![image](https://user-images.githubusercontent.com/18206302/101701577-467c6500-3ad3-11eb-9d5d-85e18bcabca6.png)

**Comment by MarkMindlin** [comment]
??
Should it work for 
region = ap-southeast-2

**Comment by MarkMindlin** [comment]
Please suggest _proper_ format for HTTP_PROXY, HTTPS_PROXY variables

**Comment by MarkMindlin** [comment]
Normally, I use a role to access to the AWS services. What should I put to "config", "credentials"?

**Comment by justinmk3** [comment]
Based on the error message, the user does not have the necessary permissions. Does your user have `cloudformation:ListStacks` permission?

**Comment by MarkMindlin** [comment]
Yes, the role I use has it. 
The point is probably how to configure user and role for AWS Toolkit.

**Comment by justinmk3** [comment]
Are you able to list clouformation stacks using AWS CLI, with the identical credentials configuration?

    aws --profile default cloudformation list-stacks

**Comment by MarkMindlin** [comment]
It returns error:
Failed to connect to proxy URL: "http://USER:PASSWORD@https://MY_PROXY:MY_PORT/"

**Comment by justinmk3** [comment]
First step is to figure out the correct proxy configuration. Related AWS CLI documentation: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html

**Comment by MarkMindlin** [comment]
Sorry,

It solved by
aws-mfa --profile MY_PROFILE

We do not use a proxy.

**Comment by justinmk3** [comment]
Thanks for the followup. Toolkit supports MFA https://github.com/aws/aws-toolkit-vscode/pull/66 so I assume we can close this.
