### ISSUE TITLE
failing test: "visualizeStateMachine throws an error if no active text editor is open"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1441]
- Happens consistently with `Integration Tests [insiders]`, could be an upstream issue.
- Observed in https://github.com/aws/aws-toolkit-vscode/pull/1438/commits/9efb496151b5e49ebc295514dfc6454250a90f2d
- Presumably same root cause as these similar issues: https://github.com/aws/aws-toolkit-vscode/issues/1261 https://github.com/aws/aws-toolkit-vscode/issues/1230 https://github.com/aws/aws-toolkit-vscode/issues/1201
- Previous attempt to fix: https://github.com/aws/aws-toolkit-vscode/pull/1209 

```
  74 passing (5m)
  1 failing
  1) visualizeStateMachine
       throws an error if no active text editor is open:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ "Running the contributed command: 'aws.previewStateMachine' failed."
- 'Could not get active text editor for state machine render.'
      + expected - actual

      -Running the contributed command: 'aws.previewStateMachine' failed.
      +Could not get active text editor for state machine render.
 
      at /codebuild/output/src004984545/src/github.com/aws/aws-toolkit-vscode/src/integrationTest/stepFunctions/visualizeStateMachine.test.ts:214:16
      at Generator.next (<anonymous>)
      at fulfilled (dist/src/integrationTest/stepFunctions/visualizeStateMachine.test.js:9:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: 1 tests failed.
```

stacktrace

```
Error: Could not get active text editor for state machine render.
    at AslVisualizationManager.<anonymous> (/…/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.ts:40:19)
    at Generator.next (<anonymous>)
    at /…/dist/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/…/dist/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.js:8:12)
    at AslVisualizationManager.visualizeStateMachine (/…/dist/src/stepFunctions/commands/visualizeStateMachine/aslVisualizationManager.js:32:16)
    at /…/src/stepFunctions/activation.ts:43:51
    at Generator.next (<anonymous>)
    ...
    at /…/src/integrationTest/stepFunctions/visualizeStateMachine.test.ts:212:47
```

**Comment by bryceitoc9** [comment]
Looks like Insiders shifted the ground underneath us; they catch the error and send out their own custom one (commit is 2 days old):
https://github.com/microsoft/vscode/blame/3ba967fd7eb97621b0e2a4fb0267b70323ffcf5f/src/vs/workbench/api/common/extHostCommands.ts#L208

**Comment by justinmk3** [comment]
seen again, which broke the release pipeline:

```
2023-01-12 19:16:40 [ERROR]: aws.previewStateMachine: ToolkitError: No active text editor or document found
    at initializeCodeLens (/codebuild/output/src379733299/src/src/stepFunctions/activation.ts:55:19)
    at localize (/codebuild/output/src379733299/src/src/stepFunctions/activation.ts:8:12)
    at /codebuild/output/src379733299/src/src/stepFunctions/activation.ts:50:129
    ...
    at Context.<anonymous> (/codebuild/output/src379733299/src/src/integrationTest/stepFunctions/visualizeStateMachine.test.ts:219:55)
    at fulfilled (/codebuild/output/src379733299/src/dist/src/integrationTest/stepFunctions/visualizeStateMachine.test.js:9:58)
```
