### ISSUE TITLE
cloud9: SAM debug fails with Image resource + python 3.8

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1442]
**To Reproduce**

1. create a cloud9 environment with Toolkit 1.18 9efb496
1. Create sam application with runtime `python 3.8 (Image)`
    - issue **does NOT affect python 3.7**
1. try to run/debug the Image resource
1. output log shows: `unable to execute 'gcc': No such file or directory`

---

-   OS: AL2
-   Visual Studio Code Version: cloud9/1.42
-   AWS Toolkit Version: 1.18 https://github.com/aws/aws-toolkit-vscode/pull/1438/commits/9efb496151b5e49ebc295514dfc6454250a90f2d

## Full log

```
Preparing to debug locally: API "/hello", Lambda "HelloWorldFunction"
Building SAM application...
Running command: (not started) [/home/linuxbrew/.linuxbrew/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkt5Ceuk/output --template /home/ec2-user/environment/py38image/app___vsctk___template.yaml --use-container --manifest /home/ec2-user/environment/py38image/hello_world/requirements.txt]
Starting Build inside a container
Building codeuri: . runtime: None metadata: {'Dockerfile': 'Dockerfile', 'DockerContext': './hello_world', 'DockerTag': 'python3.8-v1'} functions: ['HelloWorldFunction']
Building image for HelloWorldFunction function
Setting DockerBuildArgs: {'SAM_BUILD_MODE': 'debug'} for HelloWorldFunction function
Step 1/4 : FROM public.ecr.aws/lambda/python:3.8
 ---> 80e51cc8a434
Step 2/4 : COPY app.py requirements.txt ./
 ---> ebb3cdbe7aa8
Step 3/4 : RUN python3.8 -m pip install -r requirements.txt -t .
 ---> Running in 756c7c342261
Collecting requests
  Downloading requests-2.25.0-py2.py3-none-any.whl (61 kB)
Collecting ikp3db
  Downloading ikp3db-1.4.1.tar.gz (24 kB)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Using legacy 'setup.py install' for ikp3db, since package 'wheel' is not installed.
Installing collected packages: chardet, certifi, idna, urllib3, requests, ikp3db
    Running setup.py install for ikp3db: started
    Running setup.py install for ikp3db: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /var/lang/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sxp3my5m/ikp3db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sxp3my5m/ikp3db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4novo7jv/install-record.txt --single-version-externally-managed --home /tmp/pip-target-flv4_fn6 --compile --install-headers /tmp/pip-target-flv4_fn6/include/python/ikp3db
         cwd: /tmp/pip-install-sxp3my5m/ikp3db/
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    copying ikp3db.py -> build/lib.linux-x86_64-3.8
    running egg_info
    writing ikp3db.egg-info/PKG-INFO
    writing dependency_links to ikp3db.egg-info/dependency_links.txt
    writing top-level names to ikp3db.egg-info/top_level.txt
    reading manifest file 'ikp3db.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'ikp3db.egg-info/SOURCES.txt'
    running build_ext
    building 'iksettrace3' extension
    creating build/temp.linux-x86_64-3.8
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/var/lang/include/python3.8 -c iksettrace3.c -o build/temp.linux-x86_64-3.8/iksettrace3.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /var/lang/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sxp3my5m/ikp3db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sxp3my5m/ikp3db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4novo7jv/install-record.txt --single-version-externally-managed --home /tmp/pip-target-flv4_fn6 --compile --install-headers /tmp/pip-target-flv4_fn6/include/python/ikp3db Check the logs for full command output.
WARNING: You are using pip version 20.2.1; however, version 20.3.3 is available.
You should consider upgrading via the '/var/lang/bin/python3.8 -m pip install --upgrade pip' command.

Build Failed
Error: HelloWorldFunction failed to build: The command '/bin/sh -c python3.8 -m pip install -r requirements.txt -t .' returned a non-zero code: 1
"sam build" failed: /home/ec2-user/environment/py38image/app___vsctk___template.yaml
Starting SAM application locally
Running: (not started) [/home/linuxbrew/.linuxbrew/bin/sam local start-api --template /home/ec2-user/environment/py38image/app___vsctk___template.yaml --env-vars /tmp/aws-toolkit-vscode/vsctkt5Ceuk/env-vars.json --port 5858 --debug-port 5859 --debug-args -m ikp3db --ikpdb-address=0.0.0.0 --ikpdb-port=5859 -ik_ccwd=py38image/hello_world -ik_cwd=/var/task --ikpdb-log=G]
Sending request to local API: http://127.0.0.1:5858/hello
Mounting HelloWorldFunction at http://127.0.0.1:5858/hello [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2020-12-15 21:38:56  * Running on http://127.0.0.1:5858/ (Press CTRL+C to quit)
Exception on /hello [GET]
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.13.2/libexec/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.13.2/libexec/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.13.2/libexec/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.13.2/libexec/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.13.2/libexec/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.13.2/libexec/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.13.2/libexec/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 297, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.13.2/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 103, in invoke
    raise InvalidIntermediateImageError(
samcli.commands.local.lib.exceptions.InvalidIntermediateImageError: ImageUri not provided for Function: HelloWorldFunction of PackageType: Image
2020-12-15 21:38:56 127.0.0.1 - - [15/Dec/2020 21:38:56] "GET /hello HTTP/1.1" 502 -
Timeout while waiting for command: "sam local start-api"
Failed to start local API Gateway: Timeout while waiting for command: "sam local start-api"
Waiting for SAM application to start...
Attaching debugger to SAM application...
Command stopped: "sam local start-api"
```

**Comment by justinmk3** [comment]
Reported to SAM CLI: https://github.com/aws/aws-sam-cli/issues/2572

**Comment by justinmk3** [comment]
via https://github.com/aws/aws-toolkit-vscode/pull/2870#discussion_r964086927 :

> I should add that the original error shown in the related issue is due to `ikp3db` being built from source in the container. But it can be fixed by adding this to the Dockerfile:
> ```
> RUN yum groupinstall -y "Development Tools"
> ```
> 
> This PR fixes the problem you would run into _after_ updating the Dockerfile.
