### ISSUE TITLE
SAM local debug fails with VSCode "Remote: Container" feature: ECONNREFUSED 127.0.0.1:5858

### ISSUE THREAD

**Issue by MarkMindlin** [aws/aws-toolkit-vscode#1507]
**Desktop (please complete the following information):**

-   OS: Windows 10 (1909)
-   VS Code version: 1.53.0
-   AWS Toolkit extension version:1.20.0

**Question**
Hi,

We need to solve this bug.

Steps:

- Open in Dev Container
- Run Debug with configured launch.json with Lambda direct-invoke

Python 3.6
Lambda function debug
Launch.json
{
"type": "aws-sam",
"request": "direct-invoke",
"name": "Invoke Lambda",
"invokeTarget": {
"target": "code",
"lambdaHandler": "lambdaHandler",
"projectRoot": "${workspaceFolder}"
},
"lambda": {
"runtime": "python3.6",
"payload": {
"json": {}
}
}
},

VS Code version: Code 1.53.0 (8490d3d, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by justinmk3** [comment]
- Do you have antivirus software that may be interfering? 
- Can you provide the logs? In VSCode, use the `AWS: View AWS Toolkit Logs` command.

**Comment by MarkMindlin** [comment]
Yes, I have Symantec EndPoint Protection

2021-02-15 02:25:54 [INFO]: Preparing to debug locally: Lambda "app.lambdaHandler"
2021-02-15 02:25:54 [INFO]: Building SAM application...
2021-02-15 02:25:54 [INFO]: Running command: (not started) [sam build --build-dir /tmp/aws-toolkit-vscode/vsctkV37Alb/output --template /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml --base-dir /workspaces/validation/${workspaceFolder} --manifest /tmp/aws-toolkit-vscode/vsctkV37Alb/debug-requirements.txt]
2021-02-15 02:25:55 [WARN]: "sam build" failed: /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml
2021-02-15 02:25:55 [INFO]: Starting SAM application locally
2021-02-15 02:25:55 [INFO]: AWS.running.command
2021-02-15 02:25:55 [ERROR]: Error running command "sam local invoke": spawn sam ENOENT
2021-02-15 02:25:55 [ERROR]: Timeout while waiting for command: "sam local invoke"
2021-02-15 02:25:55 [ERROR]: Failed to run SAM application locally: Timeout while waiting for command: "sam local invoke"
Command stopped: "sam local invoke"
2021-02-15 02:25:55 [INFO]: Waiting for SAM application to start...
2021-02-15 02:25:55 [INFO]: Attaching debugger to SAM application...
2021-02-15 02:26:10 [ERROR]: Retry limit reached while trying to attach the debugger.
2021-02-15 02:26:10 [ERROR]: Unable to attach Debugger. Check AWS Toolkit logs. If it took longer than expected to start, you can still attach.

**Comment by justinmk3** [comment]
`sam build` is failing. It may help to increase the Toolkit log level to verbose (in vscode settings search for "aws log level", set it to "verbose"). Can you try again and then send the verbose logs?

>  Open in Dev Container

To confirm, you are using this vscode feature? https://code.visualstudio.com/docs/remote/containers

> Workspace files are mounted from the local file system or copied or cloned into the container. Extensions are installed and run inside the container

We haven't explicitly tested this scenario, but the Toolkit is known to work with the vscode "remote" (SSH) feature.

**Comment by MarkMindlin** [comment]
2021-02-16 10:00:11 [VERBOSE]: Log level is now: verbose
2021-02-16 10:01:37 [INFO]: Preparing to debug locally: Lambda "app.lambdaHandler"
2021-02-16 10:01:37 [INFO]: Building SAM application...
2021-02-16 10:01:37 [INFO]: Running command: (not started) [sam build --build-dir /tmp/aws-toolkit-vscode/vsctkz4sw5l/output --template /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml --base-dir /workspaces/validation/${workspaceFolder} --manifest /tmp/aws-toolkit-vscode/vsctkz4sw5l/debug-requirements.txt]
2021-02-16 10:01:37 [WARN]: "sam build" failed: /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml
2021-02-16 10:01:37 [INFO]: Starting SAM application locally
2021-02-16 10:01:37 [INFO]: AWS.running.command
2021-02-16 10:01:37 [ERROR]: Error running command "sam local invoke": spawn sam ENOENT
2021-02-16 10:01:37 [ERROR]: Timeout while waiting for command: "sam local invoke"
2021-02-16 10:01:37 [ERROR]: Failed to run SAM application locally: Timeout while waiting for command: "sam local invoke"
Command stopped: "sam local invoke"
2021-02-16 10:01:37 [INFO]: Waiting for SAM application to start...
2021-02-16 10:01:37 [INFO]: Attaching debugger to SAM application...
2021-02-16 10:01:49 [ERROR]: Retry limit reached while trying to attach the debugger.
2021-02-16 10:01:49 [ERROR]: Unable to attach Debugger. Check AWS Toolkit logs. If it took longer than expected to start, you can still attach.



2021-02-16 00:33:12 [ERROR]: log level: info
2021-02-16 00:33:12 [INFO]: Retrieving AWS endpoint data
2021-02-16 00:33:12 [INFO]: OS:  Linux x64 5.4.72-microsoft-standard-WSL2
Visual Studio Code Extension Host Version:  1.53.2
AWS Toolkit Version:  1.20.0

2021-02-16 00:38:13 [INFO]: Successfully sent a telemetry batch of 5
2021-02-16 09:58:15 [INFO]: Successfully sent a telemetry batch of 1
2021-02-16 09:58:36 [ERROR]: [n [Error]: No AWS profile selected
	at Object.<anonymous> (/root/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:8220480)
	at Generator.next (<anonymous>)
	at o (/root/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:8219245)]
2021-02-16 09:58:36 [WARN]: No folder passed into tryRemoveFolder: undefined
2021-02-16 09:58:36 [ERROR]: AWS.samcli.deploy.general.error
2021-02-16 10:00:11 [INFO]: Setting log level to: verbose
2021-02-16 10:00:11 [INFO]: Setting log level to: verbose
2021-02-16 10:00:11 [VERBOSE]: Log level is now: verbose
2021-02-16 10:00:11 [VERBOSE]: Log level is now: verbose
2021-02-16 10:01:37 [VERBOSE]: SAM debug: config: "Invoke Lambda"
2021-02-16 10:01:37 [INFO]: Preparing to debug locally: Lambda "app.lambdaHandler"
2021-02-16 10:01:37 [INFO]: Building SAM application...
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/local/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /home/linuxbrew/.linuxbrew/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /root/.linuxbrew/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /vscode/vscode-server/bin/x64/622cb03f7e070a9670c94bae1a45d78d7181fbd4/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /opt/gtk/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/local/sbin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/local/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/sbin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /sbin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /bin/sam
2021-02-16 10:01:37 [INFO]: SAM CLI location: undefined
2021-02-16 10:01:37 [INFO]: Running command: (not started) [sam build --build-dir /tmp/aws-toolkit-vscode/vsctkz4sw5l/output --template /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml --base-dir /workspaces/validation/${workspaceFolder} --manifest /tmp/aws-toolkit-vscode/vsctkz4sw5l/debug-requirements.txt]
2021-02-16 10:01:37 [WARN]: SAM CLI not found and not configured
2021-02-16 10:01:37 [VERBOSE]: running: (not started) [sam build --build-dir /tmp/aws-toolkit-vscode/vsctkz4sw5l/output --template /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml --base-dir /workspaces/validation/${workspaceFolder} --manifest /tmp/aws-toolkit-vscode/vsctkz4sw5l/debug-requirements.txt]
2021-02-16 10:01:37 [INFO]: Running: (not started) [sam build --build-dir /tmp/aws-toolkit-vscode/vsctkz4sw5l/output --template /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml --base-dir /workspaces/validation/${workspaceFolder} --manifest /tmp/aws-toolkit-vscode/vsctkz4sw5l/debug-requirements.txt]
2021-02-16 10:01:37 [WARN]: "sam build" failed: /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml
2021-02-16 10:01:37 [ERROR]: Unexpected exitcode (-2), expecting (0)
2021-02-16 10:01:37 [ERROR]: Error: Error: spawn sam ENOENT
2021-02-16 10:01:37 [ERROR]: stderr: 
2021-02-16 10:01:37 [ERROR]: stdout: 
2021-02-16 10:01:37 [INFO]: Starting SAM application locally
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/local/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /home/linuxbrew/.linuxbrew/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /root/.linuxbrew/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /vscode/vscode-server/bin/x64/622cb03f7e070a9670c94bae1a45d78d7181fbd4/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /opt/gtk/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/local/sbin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/local/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/sbin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /usr/bin/sam
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /sbin/sam
2021-02-16 10:01:37 [VERBOSE]: CloudFormationTemplateRegistry: manager detected a new file: /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml
2021-02-16 10:01:37 [VERBOSE]: Searching for SAM CLI in: /bin/sam
2021-02-16 10:01:37 [INFO]: AWS.running.command
2021-02-16 10:01:37 [INFO]: SAM CLI location: undefined
2021-02-16 10:01:37 [WARN]: SAM CLI not found and not configured
2021-02-16 10:01:37 [INFO]: Running: (not started) [sam local invoke awsToolkitSamLocalResource --template /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml --event /tmp/aws-toolkit-vscode/vsctkz4sw5l/event.json --env-vars /tmp/aws-toolkit-vscode/vsctkz4sw5l/env-vars.json -d 5858 --debugger-path /root/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/resources/debugger --debug-args /tmp/lambci_debug_files/py_debug_wrapper.py --listen 0.0.0.0:5858 --wait-for-client]
2021-02-16 10:01:37 [ERROR]: Error running command "sam local invoke": spawn sam ENOENT
2021-02-16 10:01:37 [ERROR]: Timeout while waiting for command: "sam local invoke"
2021-02-16 10:01:37 [ERROR]: Failed to run SAM application locally: Timeout while waiting for command: "sam local invoke"
2021-02-16 10:01:37 [VERBOSE]: SAM: command exited (code: -2): (not started) [sam local invoke awsToolkitSamLocalResource --template /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml --event /tmp/aws-toolkit-vscode/vsctkz4sw5l/event.json --env-vars /tmp/aws-toolkit-vscode/vsctkz4sw5l/env-vars.json -d 5858 --debugger-path /root/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/resources/debugger --debug-args /tmp/lambci_debug_files/py_debug_wrapper.py --listen 0.0.0.0:5858 --wait-for-client]
2021-02-16 10:01:37 [INFO]: Waiting for SAM application to start...
2021-02-16 10:01:37 [INFO]: Attaching debugger to SAM application...
2021-02-16 10:01:37 [VERBOSE]: CloudFormationTemplateRegistry: ,anager detected a deleted file: /workspaces/validation/${workspaceFolder}/app___vsctk___template.yaml
2021-02-16 10:01:49 [ERROR]: Retry limit reached while trying to attach the debugger.
2021-02-16 10:01:49 [ERROR]: Unable to attach Debugger. Check AWS Toolkit logs. If it took longer than expected to start, you can still attach.
2021-02-16 10:03:16 [INFO]: Successfully sent a telemetry batch of 3

**Comment by justinmk3** [comment]
> 2021-02-16 10:01:37 [WARN]: SAM CLI not found and not configured

Looks like `sam` is not installed in the container. SAM CLI now supports [installation without linuxbrew](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html#serverless-sam-cli-install-linux-sam-cli).

Can you confirm also that `docker` works in the container and can create containers? Else that will be the next problem :)

**Comment by MarkMindlin** [comment]
Please send me information or link
- how to install/verify sam in container
- how to install/verify docker in conteiner

**Comment by justinmk3** [comment]
> how to install/verify sam in container

That depends on how you build your container. Typically you would add a line(s) to a Dockerfile so that `sam` is available in the container. The steps to install `sam` are documented here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html#serverless-sam-cli-install-linux-sam-cli

> how to install/verify docker in container

You can verify by trying the `docker` command in the container. I don't have a reference for installing Docker in Docker.

**Comment by odenisenko** [comment]
```
2021-02-24 12:52:34 [ERROR]: START RequestId: be3f1f37-e318-4ea5-8108-51a914e543c2 Version: $LATEST

2021-02-24 12:52:34 [ERROR]: Prepending Lambda task root to path: /var/task
Starting debugger

2021-02-24 12:52:34 [INFO]: Waiting for SAM application to start...
2021-02-24 12:52:34 [INFO]: Attaching debugger to SAM application...
2021-02-24 12:52:34 [ERROR]: Traceback (most recent call last):
  File "/tmp/lambci_debug_files/py_debug_wrapper.py", line 14, in <module>
    runpy.run_module('debugpy', run_name='__main__')
  File "/var/lang/lib/python3.8/runpy.py", line 203, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/var/lang/lib/python3.8/runpy.py", line 138, in _get_module_details
    raise error("No module named %s" % mod_name)
ImportError: No module named debugpy

2021-02-24 12:52:34 [ERROR]: time="2021-02-24T10:52:37.223" level=error msg="Init failed" InvokeID= error="Runtime exited with error: exit status 1"
time="2021-02-24T10:52:37.223" level=error msg="INIT DONE failed: Runtime.ExitError"

2021-02-24 12:54:32 [INFO]: Successfully sent a telemetry batch of 1
2021-02-24 12:55:11 [ERROR]: Retry limit reached while trying to attach the debugger.
2021-02-24 12:55:11 [ERROR]: Unable to attach Debugger. Check AWS Toolkit logs. If it took longer than expected to start, you can still attach.
2021-02-24 12:59:32 [INFO]: Successfully sent a telemetry batch of 1

```

**Comment by justinmk3** [comment]
That looks like good progress. Toolkit should automatically install `debugpy` for the debugger, but it failed somehow. Just for troubleshooting, can you try adding `debugpy` to your application's `requirements.txt` ?

**Comment by justinmk3** [comment]
> "projectRoot": "${workspaceFolder}"

I just noticed that your launch config has `${workspaceFolder}`. This isn't supported by the Toolkit yet, but you can try the prerelease artifact from https://github.com/aws/aws-toolkit-vscode/pull/1522 :

1. Download and extract [toolkit.zip](https://github.com/aws/aws-toolkit-vscode/files/6079537/toolkit.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has  version 1.21 (not the release/older version).

**Comment by justinmk3** [comment]
[Toolkit 1.21](https://github.com/aws/aws-toolkit-vscode/releases/tag/v1.21.0) supports `${workspaceFolder}` in SAM launch configs.

**Comment by rtorres280** [comment]
I have same behavior as above where my invoke fails due to not having debugpy

**Comment by justinmk3** [comment]
@rtorres280 please open a new issue and include the logs.
Can you provide the logs? 

1. Set the Toolkit log level to "verbose": in VSCode settings search for "aws log level", then select "verbose".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View AWS Toolkit Logs` command to get the logs.

**Comment by sergeyfsv-da** [comment]
I've fixed that by changing name of c:\Python38\Scripts\sam.exe to c:\Python38\Scripts\_sam.exe since it interfered with another sam.cmd in "c:\Program Files\Amazon\AWSSAMCLI\bin\" in my PATH.
