### ISSUE TITLE
failing test: "ConstructNode initializes icon paths for CloudFormation resources"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1524]
seen in https://github.com/aws/aws-toolkit-vscode/pull/1516/checks?check_run_id=1939291245

```
  2 failing
  1) ConstructNode
       initializes icon paths for CloudFormation resources:

      AssertionError [ERR_ASSERTION]: Unexpected dark icon path
      + expected - actual

      -/d:/a/aws-toolkit-vscode/aws-toolkit-vscode/resources/dark/cdk/cloudformation.svg
      +d:\a\aws-toolkit-vscode\aws-toolkit-vscode\resources\dark\cdk\cloudformation.svg
      
      at d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\cdk\explorer\constructNode.test.ts:59:16
      at Generator.next (<anonymous>)
      at d:\a\aws-toolkit-vscode\aws-toolkit-vscode\dist\src\test\cdk\explorer\constructNode.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\dist\src\test\cdk\explorer\constructNode.test.js:8:12)
      at Context.<anonymous> (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\cdk\explorer\constructNode.test.ts:42:74)
      at processImmediate (internal/timers.js:456:21)

  2) ConstructNode
       initializes icon paths for CDK constructs:

      AssertionError [ERR_ASSERTION]: Unexpected dark icon path
      + expected - actual

      -/d:/a/aws-toolkit-vscode/aws-toolkit-vscode/resources/dark/cdk/cdk.svg
      +d:\a\aws-toolkit-vscode\aws-toolkit-vscode\resources\dark\cdk\cdk.svg
```

**Comment by bryceitoc9** [comment]
Can't replicate this one locally (on the tip of `feature/sso`) and for some reason the `version` command either isn't working on Insiders or just doesn't work on Windows so I can't even dig up the specific version that was used for the test:
```
Running Main test suite...
Setting up VS Code test instance, version: insiders
Downloading VS Code insiders from https://update.code.visualstudio.com/latest/win32-archive/insider
Downloaded VS Code insiders into .vscode-test/vscode-insiders
VS Code test instance location: D:\a\aws-toolkit-vscode\aws-toolkit-vscode\.vscode-test\vscode-insiders\Code - Insiders.exe
Invoking vscode CLI command:
    "D:\a\aws-toolkit-vscode\aws-toolkit-vscode\.vscode-test\vscode-insiders\bin\code-insiders.cmd" ["--version"]

Installing VS Code Extension: redhat.vscode-yaml
```
Will keep an eye on it but thinking this may be some weird one-off?
