### ISSUE TITLE
failing test (macOS Insiders): ChildProcess: "Error: read ENOTCONN"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#1525]
Example: https://github.com/aws/aws-toolkit-vscode/pull/1483/checks?check_run_id=1956795148

```
  4) ChildProcess
       start
         reports error for missing executable:
     Uncaught Error: read ENOTCONN
      at tryReadStart (net.js:573:20)
      at Socket._read (net.js:584:5)
      at Socket.Readable.read (_stream_readable.js:467:10)
      at Socket.read (net.js:624:39)
      at new Socket (net.js:376:12)
      at Object.Socket (net.js:267:41)
      at createSocket (internal/child_process.js:314:14)
      at ChildProcess.spawn (internal/child_process.js:437:23)
      at Object.spawn (child_process.js:557:9)
      at Function.spawn (node_modules/cross-spawn/index.js:12:24)
      at ChildProcess.<anonymous> (dist/src/shared/utilities/childProcess.js:9:4530)
      at Generator.next (<anonymous>)
      at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/dist/src/shared/utilities/childProcess.js:9:1746
      at new Promise (<anonymous>)
      at __awaiter (dist/src/shared/utilities/childProcess.js:9:662)
      at ChildProcess.start (dist/src/shared/utilities/childProcess.js:9:4054)
      at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/src/test/shared/utilities/childProcess.test.ts:289:36
      at Generator.next (<anonymous>)
      at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/dist/src/test/shared/utilities/childProcess.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (dist/src/test/shared/utilities/childProcess.test.js:8:12)
      at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/src/test/shared/utilities/childProcess.test.ts:288:63
      at new Promise (<anonymous>)
      at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/src/test/shared/utilities/childProcess.test.ts:288:19
      at Generator.next (<anonymous>)
      at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/dist/src/test/shared/utilities/childProcess.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (dist/src/test/shared/utilities/childProcess.test.js:8:12)
      at Context.<anonymous> (src/test/shared/utilities/childProcess.test.ts:283:63)
      at processImmediate (internal/timers.js:456:21)


Exit code:   1
```

**Comment by justinmk3** [comment]
Reproduced locally on macOS 10.14.6:

```
$ npm run testCompile && VSCODE_TEST_VERSION=insiders npm run test
...
Setting up VS Code test instance, version: insiders
Remove outdated Insiders at /Volumes/workplace/aws-toolkit-vscode/.vscode-test/vscode-insiders and re-downloading.
Old: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3 | 2020-10-07T00:58:35.624Z
New: e7989863202eac0ec4e66ca82733d968bca7527a | 2021-03-01T21:06:53.719Z
...
  9) ChildProcess
       run
         reports error for missing executable:
     Uncaught Error: read ENOTCONN
      at tryReadStart (net.js:573:20)
      at Socket._read (net.js:584:5)
      at Socket.Readable.read (_stream_readable.js:467:10)
      ...
      at /Volumes/workplace/aws-toolkit-vscode/dist/src/test/shared/utilities/childProcess.test.js:12:71
      at new Promise (<anonymous>)
      at __awaiter (dist/src/test/shared/utilities/childProcess.test.js:8:12)
      at Context.<anonymous> (src/test/shared/utilities/childProcess.test.ts:142:63)
      at processImmediate (internal/timers.js:456:21)

```
