### ISSUE TITLE
Authentication fails when using a credential_process and source_profile

### ISSUE THREAD

**Issue by michael-plutoflume** [aws/aws-toolkit-vscode#1541]
**Describe the bug**

I get an error when trying to use a `credential_process` in conjunction with a `source_profile`.

**To Reproduce**

I have a config file (`~/.aws/config`) that is equivalent to

```
[profile base-profile]
credential_process = some-process

[profile child]
region            = eu-west-1
role_arn          = arn:aws:iam::123456789:role/some-role
source_profile    = base-profile
role_session_name = something
```

and no credentials file. This works fine with the CLI, python SDK etc. but when I try and select the `child` profile for use with the toolkit I get an error. The logs read

```
2021-03-08 17:55:34 [ERROR]: Error trying to connect to AWS with Credentials Provider profile:child. Toolkit will now disconnect from AWS. [Error: ENOENT: no such file or directory, open '/home/michael.aldridge/.aws/credentials'
	at Object.openSync (fs.js:466:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
	at Object.readFileSync (fs.js:368:35)
	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
	at Object.readFileSync (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:191193)
	at constructor.o [as parseFile] (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1751687)
	at constructor.loadFrom (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1752116)
	at constructor.region (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:3310)
	at constructor.set (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2654917)
	at constructor.<anonymous> (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2653560)
	at constructor.each (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:198600)
	at new constructor (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2653520)
	at t.constructor.t.constructor.loadServiceClass (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2641401)
	at t.constructor.t.constructor.constructor (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2640222)
	at new t.constructor.t.constructor (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:200250)
	at constructor.loadRoleProfile (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2761836)
	at constructor.load (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2760365)
	at constructor.coalesceRefresh (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1747274)
	at constructor.refresh (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2760979)
	at constructor.get (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1747100)
	at e (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1748324)
	at constructor.resolve (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1748368)
	at /home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:202656
	at new Promise (<anonymous>)
	at constructor.resolvePromise (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:202593)
	at f.<anonymous> (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1330687)
	at Generator.next (<anonymous>)
	at /home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1329196
	at new Promise (<anonymous>)
	at n (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1328941)
	at f.getCredentials (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1330382)
	at t.CredentialsStore.<anonymous> (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1911079)
	at Generator.next (<anonymous>)
	at /home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1910287
	at new Promise (<anonymous>)
	at n (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1910032)
	at t.CredentialsStore.setCredentials (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1911016)
	at t.CredentialsStore.<anonymous> (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1910895)
	at Generator.next (<anonymous>)
	at o (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1910089)] {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/michael.aldridge/.aws/credentials'
}
```

I have tried adding an empty credentials file, but in that case I get the following error when trying to use the `child` profile

```
2021-03-08 17:58:21 [ERROR]: Error trying to connect to AWS with Credentials Provider profile:child. Toolkit will now disconnect from AWS. [Error [CredentialsError]: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
	at constructor.load (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2760784)
	at constructor.coalesceRefresh (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1747274)
	at constructor.refresh (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2760979)
	at constructor.get (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1747100)
	at constructor.getCredentials (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2653837)
	at constructor.<anonymous> (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2656411)
	at constructor.callListeners (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1745559)
	at constructor.emit (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1745298)
	at constructor.emitEvent (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2676636)
	at constructor.e (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2672143)
	at r.runTo (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2678478)
	at constructor.runTo (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2673900)
	at constructor.send (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2673793)
	at t.constructor.t.constructor.makeRequest (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2642951)
	at t.constructor.t.constructor.n.util.each.e.<computed>.e.api.operations.<computed>.authtype.e.<computed> [as assumeRole] (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2649777)
	at constructor.loadRoleProfile (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2762262)
	at constructor.load (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2760365)
	at constructor.coalesceRefresh (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1747274)
	at constructor.refresh (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2760979)
	at constructor.get (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1747100)
	at new constructor (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:2759949)
	at /home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1332217
	at e (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1748308)
	at constructor.resolve (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1748368)
	at /home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:202656
	at new Promise (<anonymous>)
	at constructor.resolvePromise (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:202593)
	at f.<anonymous> (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1330687)
	at Generator.next (<anonymous>)
	at /home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1329196
	at new Promise (<anonymous>)
	at n (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1328941)
	at f.getCredentials (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1330382)
	at t.CredentialsStore.<anonymous> (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1911079)
	at Generator.next (<anonymous>)
	at /home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1910287
	at new Promise (<anonymous>)
	at n (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1910032)
	at t.CredentialsStore.setCredentials (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1911016)
	at t.CredentialsStore.<anonymous> (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1910895)
	at Generator.next (<anonymous>)
	at o (/home/michael.aldridge/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.20.0/dist/extension.js:2:1910089)] {
  code: 'CredentialsError',
  time: 2021-03-08T17:58:21.463Z,
  originalError: {
    message: 'Could not load credentials from constructor',
    code: 'CredentialsError',
    time: 2021-03-08T17:58:21.463Z,
    originalError: {
      message: 'Credentials not set for profile base-profile',
      code: 'SharedIniFileCredentialsProviderFailure',
      time: 2021-03-08T17:58:21.462Z
    }
  }
}
```

**Expected behavior**

Authentication to succeed 

**Desktop (please complete the following information):**

OS:  Linux x64 5.4.0-65-generic
Visual Studio Code Extension Host Version:  1.53.2
AWS Toolkit Version:  1.20.0

**Comment by bryceitoc9** [comment]
Hi @michael-plutoflume

We've had some issues with credential loading if [no `~/.aws/credentials` file is present](https://github.com/aws/aws-toolkit-vscode/issues/641). Could you just `touch ~/.aws/credentials` and see if it works after that? In our experience a blank file makes this work.

**Comment by michael-plutoflume** [comment]
> Hi @michael-plutoflume
> 
> We've had some issues with credential loading if [no `~/.aws/credentials` file is present](https://github.com/aws/aws-toolkit-vscode/issues/641). Could you just `touch ~/.aws/credentials` and see if it works after that? In our experience a blank file makes this work.

Hi @bryceitoc9. Thanks for the quick response! I tried that but I still get an error (see the second log in the description).

**Comment by dannysteenman** [comment]
I have the same issue here.

**Comment by justinmk3** [comment]
Toolkit 1.23 (unreleased) includes https://github.com/aws/aws-toolkit-vscode/pull/1626 which fixes the issue where Toolkit may fail to authenticate if  `~/.aws/credentials` does not exist.

The following prerelease build includes the fix, we appreciate your feedback:

1. Download/extract the prerelease build: [aws-toolkit.zip](https://github.com/aws/aws-toolkit-vscode/files/6281457/aws-toolkit.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Extensions: Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version).
