### ISSUE TITLE
"Create Lambda SAM Application" fails with " Cannot find git"

### ISSUE THREAD

**Issue by varshithvvs** [aws/aws-toolkit-vscode#1593]
I have been trying to create a sample SAM application; however I find the following issue popping up saying git executable not found.

Following are the steps I have tried to resolve the same:
1. Updated git to its latest version (2.31.0.1)
2. Added git folder to the environment variables path

Log of the error at verbose setting:

2021-03-21 11:41:51 [ERROR]: log level: info
2021-03-21 11:41:51 [INFO]: Retrieving AWS endpoint data
2021-03-21 11:41:51 [INFO]: OS:  Windows_NT x64 10.0.19042
Visual Studio Code Extension Host Version:  1.54.3
AWS Toolkit Version:  1.22.0

2021-03-21 11:46:52 [INFO]: Successfully sent a telemetry batch of 5
2021-03-21 14:10:34 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:10:34 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:34 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:35 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:10:35 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:10:35 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:35 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:35 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:10:35 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:10:35 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:35 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:35 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:10:35 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:10:35 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:35 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:36 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:10:36 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:36 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:10:36 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:36 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:10:36 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:36 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:36 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:10:36 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:10:36 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:36 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:37 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:10:37 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:10:37 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:37 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:10:37 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:11:43 [INFO]: Setting log level to: verbose
2021-03-21 14:11:43 [INFO]: Setting log level to: verbose
2021-03-21 14:11:43 [VERBOSE]: Log level is now: verbose
2021-03-21 14:11:43 [VERBOSE]: Log level is now: verbose
2021-03-21 14:12:05 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:12:05 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:05 [VERBOSE]: running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:05 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:05 [VERBOSE]: stdout: {
  "version": "1.20.0"
}

2021-03-21 14:12:05 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:12:05 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:12:05 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:05 [VERBOSE]: running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:05 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:05 [VERBOSE]: stdout: {
  "version": "1.20.0"
}

2021-03-21 14:12:05 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:12:05 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:12:05 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:05 [VERBOSE]: running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:05 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [VERBOSE]: stdout: {
  "version": "1.20.0"
}

2021-03-21 14:12:06 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:12:06 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:12:06 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [VERBOSE]: running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [VERBOSE]: stdout: {
  "version": "1.20.0"
}

2021-03-21 14:12:06 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:12:06 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:12:06 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [VERBOSE]: running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [VERBOSE]: stdout: {
  "version": "1.20.0"
}

2021-03-21 14:12:06 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:12:06 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:12:06 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [VERBOSE]: running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:06 [VERBOSE]: stdout: {
  "version": "1.20.0"
}

2021-03-21 14:12:07 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:12:16 [INFO]: Successfully sent a telemetry batch of 1
2021-03-21 14:12:17 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:12:17 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:17 [VERBOSE]: running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:17 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info]
2021-03-21 14:12:18 [VERBOSE]: stdout: {
  "version": "1.20.0"
}

2021-03-21 14:12:18 [INFO]: SAM CLI location: C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2021-03-21 14:12:18 [INFO]: Running command: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd init --name lambda-python3.8 --no-interactive --dependency-manager pip --package-type Image --base-image amazon/python3.8-base]
2021-03-21 14:12:18 [INFO]: SAM CLI not configured, using SAM found at: 'C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\sam.cmd'
2021-03-21 14:12:18 [VERBOSE]: running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd init --name lambda-python3.8 --no-interactive --dependency-manager pip --package-type Image --base-image amazon/python3.8-base]
2021-03-21 14:12:18 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd init --name lambda-python3.8 --no-interactive --dependency-manager pip --package-type Image --base-image amazon/python3.8-base]
2021-03-21 14:12:18 [VERBOSE]: stderr: 
Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates

2021-03-21 14:12:18 [VERBOSE]: stderr: WARN: Can't clone app repo, git executable not found
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 205, in _clone_new_app_templates
    [self._git_executable(), "clone", self._repo_url],
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 237, in _git_executable
    raise OSError("Cannot find git, was looking at executables: {}".format(options))
OSError: Cannot find git, was looking at executables: ['git', 'git.cmd', 'git.exe', 'git.bat']

2021-03-21 14:12:19 [VERBOSE]: stderr: Error: Please verify your location. The following types of location are supported:

* Github: gh:user/repo (or) https://github.com/user/repo (or) git@github.com:user/repo.git
          For Git repositories, you must use location of the root of the repository.

* Mercurial: hg+ssh://hg@bitbucket.org/repo

* Http(s): https://example.com/code.zip

* Local Path: /path/to/code.zip

2021-03-21 14:12:19 [ERROR]: Unexpected exitcode (1), expecting (0)
2021-03-21 14:12:19 [ERROR]: An error occurred while creating a new SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
2021-03-21 14:12:19 [ERROR]: Error: undefined
2021-03-21 14:12:19 [ERROR]: stderr: Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates
,WARN: Can't clone app repo, git executable not found
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 205, in _clone_new_app_templates
    [self._git_executable(), "clone", self._repo_url],
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 237, in _git_executable
    raise OSError("Cannot find git, was looking at executables: {}".format(options))
OSError: Cannot find git, was looking at executables: ['git', 'git.cmd', 'git.exe', 'git.bat']
,Error: Please verify your location. The following types of location are supported:

* Github: gh:user/repo (or) https://github.com/user/repo (or) git@github.com:user/repo.git
          For Git repositories, you must use location of the root of the repository.

* Mercurial: hg+ssh://hg@bitbucket.org/repo

* Http(s): https://example.com/code.zip

* Local Path: /path/to/code.zip
2021-03-21 14:12:19 [ERROR]: stdout: 
2021-03-21 14:12:19 [ERROR]: Error creating new SAM Application: [Error: Error with child process: Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates
,WARN: Can't clone app repo, git executable not found
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 205, in _clone_new_app_templates
    [self._git_executable(), "clone", self._repo_url],
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 237, in _git_executable
    raise OSError("Cannot find git, was looking at executables: {}".format(options))
OSError: Cannot find git, was looking at executables: ['git', 'git.cmd', 'git.exe', 'git.bat']
,Error: Please verify your location. The following types of location are supported:

* Github: gh:user/repo (or) https://github.com/user/repo (or) git@github.com:user/repo.git
          For Git repositories, you must use location of the root of the repository.

* Mercurial: hg+ssh://hg@bitbucket.org/repo

* Http(s): https://example.com/code.zip

* Local Path: /path/to/code.zip
	at Object.t.logAndThrowIfUnexpectedExitCode (c:\Users\User\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.22.0\dist\extension.js:2:553655)
	at Object.<anonymous> (c:\Users\User\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.22.0\dist\extension.js:2:8157268)
	at Generator.next (<anonymous>)
	at o (c:\Users\User\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.22.0\dist\extension.js:2:8156443)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]

PS: I'm an amateur trying to learn AWS toolkit, let me know in case I have missed anything during basic setup as well

**Comment by justinmk3** [comment]
The root problem is that `sam` ([SAM CLI](https://github.com/aws/aws-sam-cli/)) cannot find git. So we need to figure out why.

> 2\. Added git folder to the environment variables path

If you open cmd.exe and run `git --version`, what happens?

If you run `where git` or `which git` , what does it report?

If you try this command, what happens:

    "C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" init --name lambda-python3.8 --no-interactive --dependency-manager pip --package-type Image --base-image amazon/python3.8-base

**Comment by varshithvvs** [comment]
Hi @justinmk3 ,

I have tried the all the commands following are the screenshots of the results I have observed:
![AWS lambda Issue](https://user-images.githubusercontent.com/37666557/112259843-f8106200-8c8e-11eb-98c4-0f5cc916ef80.png)

**Comment by justinmk3** [comment]
Maybe the only problem is https://github.com/aws/aws-sam-cli-app-templates/issues/95 , for which the Toolkit is considering a fix/workaround.

To confirm, in VSCode using the AWS Toolkit, try `Create Lambda SAM Application` command and choose any runtime except python3.8. Does it work or does it have the same "Cannot find git" issue?

**Comment by varshithvvs** [comment]
Yeah it worked I have tried python3.7 and python3.8 sample SAM application is being created. But I'm having issues when using python 3.8 (Image).
