### ISSUE TITLE
"invalid security token" for one region's services but not the other? 

### ISSUE THREAD

**Issue by abdulkadirdere** [aws/aws-toolkit-vscode#1644]
**Desktop (please complete the following information):**

-   OS: macOS Big Sur
-   VS Code version: 1.55.2
-   AWS Toolkit extension version: v1.22.0

**Question**

I can only view one region. I am getting an error on the other region for the same account.
This is the case for all services in one region. But without changing anything I can view services in another region:

Error code
        UnrecognizedClientException
    
Error message
        The security token included in the request is invalid.

Using AD for authorisation.

**Comment by justinmk3** [comment]
> Using AD for authorisation.

Do other regions work with `aws` CLI or other tools? 

> But without changing anything I can view services in another region:

Can you expand on this? You _can_ view services in another region, after doing what steps exactly?

Can you provide the Toolkit logs? 

1. Set the Toolkit log level to "verbose": in VSCode settings search for "aws log level", then select "verbose".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View AWS Toolkit Logs` command to get the logs.

**Comment by abdulkadirdere** [comment]
> Do other regions work with aws CLI or other tools?

Yes, other region works.
Please see the screenshot:<img width="821" alt="Screenshot 2021-04-16 at 11 42 33" src="https://user-images.githubusercontent.com/13560023/115006892-adf35880-9ea9-11eb-9f57-183c86728a59.png">
This is the error I am getting. Do I need to make changes for each region? I thought the same token would work for all regions under the same account.

> Can you expand on this? You can view services in another region, after doing what steps exactly?

I can show other regions by selecting them from 'Select region in the Explore' from AWS Toolkit settings. So if I add Europe region I can view the services in it without changing anything.

**Comment by justinmk3** [comment]
> Do I need to make changes for each region? I thought the same token would work for all regions under the same account.

It depends on the IAM permissions associated with the credentials. For the region that doesn't work in the Toolkit, try this command in your terminal (where PROFILE and REGION are the values relevant to this issue):

    aws --profile PROFILE --region REGION lambda list-functions

**Comment by abdulkadirdere** [comment]
@justinmk3 I have tried your suggestion but still the same error.

From the full log of error I am getting:
```
[ERROR]: [UnrecognizedClientException: The security token included in the request is invalid
	at Object.c [as extractError] (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:700:17922)
	at constructor.N (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1438:4672)
	at constructor.callListeners (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1438:25030)
	at constructor.emit (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1438:24739)
	at constructor.emitEvent (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:10845)
	at constructor.N (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:6431)
	at u.runTo (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:12683)
	at /Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:12895
	at constructor.<anonymous> (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:6642)
	at constructor.<anonymous> (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:10900)
	at constructor.callListeners (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1438:25134)
	at constructor.emit (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1438:24739)
	at constructor.emitEvent (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:10845)
	at constructor.N (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:6431)
	at u.runTo (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:12683)
	at /Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:12895
	at constructor.<anonymous> (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:6642)
	at constructor.<anonymous> (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1639:10900)
	at constructor.callListeners (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1438:25134)
	at N (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1438:24915)
	at IncomingMessage.<anonymous> (/Users/admin/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.23.0/dist/extension.js:1638:34858)
	at IncomingMessage.emit (events.js:327:22)
	at IncomingMessage.EventEmitter.emit (domain.js:483:12)
	at endReadableNT (_stream_readable.js:1220:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)] {
  code: 'UnrecognizedClientException',
```

**Comment by justinmk3** [comment]
> I have tried your suggestion but still the same error.

That implies that this is related to IAM permissions defined in your AWS account (or AD).
