### ISSUE TITLE
Cannot Start debugging

### ISSUE THREAD

**Issue by offfscar** [aws/aws-toolkit-vscode#1685]
After last update whenever I try to launch the debugger it throws this:

> 2021-04-28 11:27:59 [INFO]: AWS.running.command
> Error: [InvalidResourceException('.', 'Logical ids must be alphanumeric.')] ('.', 'Logical ids must be alphanumeric.')

I found that when the "_app___vsctk___template.yaml_" file is autogenerated it's content is:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  helloworldfunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: helloworldfunction
      Runtime: nodejs12.x
      CodeUri: ./
      Handler: index.handler
      Timeout: 30
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/Coder
      MemorySize: 128
      Events:
        FinantialIndicator:
          Type: Api
          Properties:
            Path: /helloworld
            Method: GET
```
changing my resource name "helloworldfunction" to "."

1. Go to Menú "Run" and then select "Start debugging"

Expected behavior
Debug started.

An important thing to take in count is that the same project is able to be compiled and deployed with "_sam build && sam deploy_" command.

Environment info:
Ubuntu 20.04.2 LTS 64bit
Gnome 3.36.8
AWS Toolkit v1.24.0
Visual Studio Code Version: 1.55.2
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-72-generic snap

**Desktop (please complete the following information):**

-   OS:
-   Visual Studio Code Version:
-   AWS Toolkit Version:

Complete error is:
```
2021-04-28 15:11:23 [INFO]: Preparing to debug locally: Lambda "index.handler"
2021-04-28 15:11:23 [INFO]: Building SAM application...
2021-04-28 15:11:23 [INFO]: Running command: (not started) [/home/linuxbrew/.linuxbrew/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctknQ86Ij/output --template /home/user/aws/HelloWorlNodeJsLambda/app___vsctk___template.yaml --base-dir /home/user/aws/HelloWorlNodeJsLambda]
2021-04-28 15:11:25 [INFO]: Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 78, in run_plugins
    parser.parse(template_copy, all_plugins)  # parse() will run all configured plugins
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 147, in parse
    raise InvalidDocumentException(document_errors)
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('.', 'Logical ids must be alphanumeric.')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 210, in cli
    do_cli(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 277, in do_cli
    with BuildContext(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/commands/build/build_context.py", line 78, in __enter__
    self._stacks, remote_stack_full_paths = SamLocalStackProvider.get_stacks(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 230, in get_stacks
    current = SamLocalStackProvider(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 51, in __init__
    self._template_dict = self.get_template(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_base_provider.py", line 161, in get_template
    template_dict = SamTranslatorWrapper(template_dict, parameter_values=parameters_values).run_plugins()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 80, in run_plugins
    raise InvalidSamDocumentException(
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('.', 'Logical ids must be alphanumeric.')] ('.', 'Logical ids must be alphanumeric.')

2021-04-28 15:11:25 [WARN]: "sam build" failed: /home/user/aws/HelloWorlNodeJsLambda/app___vsctk___template.yaml
2021-04-28 15:11:25 [INFO]: Starting SAM application locally
2021-04-28 15:11:26 [INFO]: AWS.running.command
Error: [InvalidResourceException('.', 'Logical ids must be alphanumeric.')] ('.', 'Logical ids must be alphanumeric.')

Command stopped: "sam local invoke"
2021-04-28 15:11:27 [ERROR]: Timeout while waiting for command: "sam local invoke"
2021-04-28 15:11:27 [ERROR]: Failed to run SAM application locally: Timeout while waiting for command: "sam local invoke"
2021-04-28 15:11:27 [INFO]: Waiting for SAM application to start...
2021-04-28 15:11:57 [WARN]: Failed to use debugger port: 5858
2021-04-28 15:11:57 [INFO]: Attaching debugger to SAM application...
2021-04-28 15:12:22 [ERROR]: Retry limit reached while trying to attach the debugger.
2021-04-28 15:12:22 [ERROR]: Unable to attach Debugger. Check AWS Toolkit logs. If it took longer than expected to start, you can still attach.
```

**Comment by justinmk3** [comment]
Thanks for reporting. Likely duplicate of https://github.com/aws/aws-toolkit-vscode/issues/1684

**Comment by offfscar** [comment]
The [#1684](https://github.com/aws/aws-toolkit-vscode/issues/1684) it's related with the resource name given by the developer, but in this case the plugin renames it automatically to "." in the "app___vsctk___template.yaml" temporary file.
Thanks in advance for your time!

**Comment by JadenSimon** [comment]
These two bug do appear to be unrelated, though they lead to the same error. This bug is caused by the CodeUri being changed, while the other bug is from inferring resource names from the project name.

**Comment by justinmk3** [comment]
@offfscar can you post the launch config you are using? Specifically are you using `target: code` ?
