### ISSUE TITLE
Display error details in AWS Explorer

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#170]
When errors are encountered while loading data into the AWS Explorer, relevant information needs to be shown. Currently, "No functions" is incorrectly shown.

Where possible, indicate the error code and error service in a tree node.
The tree node should show an error icon.

Consider surfacing full details (like a stack trace) - possible example: clicking on error node outputs the full details somewhere so user can copy to clipboard.

Here is a sample of the AWS Toolkit for Jetbrains
![image](https://user-images.githubusercontent.com/39839589/49890840-ed9d6780-fdf9-11e8-91de-71eb358f13d4.png)

**Comment by acguglielmo** [comment]
Hello @awschristou! I'm interested in working on this issue.

**Comment by acguglielmo** [comment]
There is the following comment in `utils.ts`: 

> TODO: Handle error gracefully, possibly add a node that can attempt to retry the operation

It should be addressed in this issue too?

**Comment by awschristou** [comment]
You are correct, this task can be worked on using the latest `develop` branch now.
Regarding the TODO you have found, it would be a welcome change, but I'd recommend that it take place as a separate PR.

**Comment by acguglielmo** [comment]
I'm ready to send a PR, but it seems there are the following broken tests in `upstream/develop (eba1db7a0f562)`:

```
  1) CloudFormationNode
       initializes name and tooltip:
     AssertionError [ERR_ASSERTION]: undefined == 'myStack [UPDATE_COMPLETE]'
      at Object.<anonymous> (src/test/lambda/explorer/cloudformationNode.test.ts:43:16)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/cloudformationNode.test.ts:39:51)


  2) CloudFormationNode
       only specific cloudformation stack lambdas:
     TypeError: functionNode_1.CloudFormationFunctionNode is not a constructor
      at awsTreeNodeBase_1.AWSTreeNodeBase.getChildren.__awaiter.regionLambdas.filter.map.lambdaInfo (out/src/lambda/explorer/cloudFormationNode.js:9:5005)
      at Array.map (<anonymous>)
      at DerivedCloudFormationNode.<anonymous> (out/src/lambda/explorer/cloudFormationNode.js:9:4942)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/lambda/explorer/cloudFormationNode.js:9:1515)
      at new Promise (<anonymous>)
      at __awaiter (out/src/lambda/explorer/cloudFormationNode.js:9:327)
      at DerivedCloudFormationNode.getChildren (out/src/lambda/explorer/cloudFormationNode.js:9:3511)
      at Object.<anonymous> (src/test/lambda/explorer/cloudformationNode.test.ts:107:43)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/cloudformationNode.test.ts:60:65)


  3) CloudFormationStackNode
       initializes name and tooltip:
     TypeError: cloudFormationNodes_1.CloudFormationNode is not a constructor
      at Object.<anonymous> (src/test/lambda/explorer/cloudformationStackNode.test.ts:48:13)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationStackNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationStackNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/cloudformationStackNode.test.ts:46:51)


  4) CloudFormationStackNode
       returns placeholder node if no children are present:
     TypeError: cloudFormationNodes_1.CloudFormationNode is not a constructor
      at Object.<anonymous> (src/test/lambda/explorer/cloudformationStackNode.test.ts:86:13)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationStackNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationStackNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/cloudformationStackNode.test.ts:56:74)


  5) CloudFormationStackNode
       only includes functions which are in a CloudFormation stack:
     TypeError: cloudFormationNodes_1.CloudFormationNode is not a constructor
      at Object.<anonymous> (src/test/lambda/explorer/cloudformationStackNode.test.ts:181:13)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationStackNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationStackNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/cloudformationStackNode.test.ts:96:82)


  6) CloudFormationStackNode
       initializes icon path:
     TypeError: cloudFormationNodes_1.CloudFormationNode is not a constructor
      at Object.<anonymous> (src/test/lambda/explorer/cloudformationStackNode.test.ts:203:13)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationStackNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/cloudformationStackNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/cloudformationStackNode.test.ts:197:44)


  7) FunctionNode
       initializes name and tooltip:
     TypeError: functionNode_1.RegionFunctionNode is not a constructor
      at Object.<anonymous> (src/test/lambda/explorer/functionNode.test.ts:36:26)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/functionNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/functionNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/functionNode.test.ts:35:51)


  8) FunctionNode
       initializes icon path:
     TypeError: functionNode_1.RegionFunctionNode is not a constructor
      at Object.<anonymous> (src/test/lambda/explorer/functionNode.test.ts:54:26)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/functionNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/functionNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/functionNode.test.ts:49:44)


  9) FunctionNode
       returns expected context value:
     TypeError: functionNode_1.RegionFunctionNode is not a constructor
      at Object.<anonymous> (src/test/lambda/explorer/functionNode.test.ts:84:26)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/functionNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/functionNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/functionNode.test.ts:83:53)


  10) FunctionNode
       has no children:
     TypeError: functionNode_1.RegionFunctionNode is not a constructor
      at Object.<anonymous> (src/test/lambda/explorer/functionNode.test.ts:97:26)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/functionNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/functionNode.test.js:7:12)
      at Context.fakeExtensionContext_1.FakeExtensionContext.it (src/test/lambda/explorer/functionNode.test.ts:96:38)


  11) GenericNode
       initializes name and tooltip:
     AssertionError [ERR_ASSERTION]: [] == 'myGenericNode'
      at Object.<anonymous> (src/test/lambda/explorer/genericAwsTreeNode.test.ts:22:16)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/genericAwsTreeNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/genericAwsTreeNode.test.js:7:12)
      at Context.it (src/test/lambda/explorer/genericAwsTreeNode.test.ts:17:51)


  12) GenericNode
       minimum children number:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Object.<anonymous> (src/test/lambda/explorer/genericAwsTreeNode.test.ts:32:9)
      at Generator.next (<anonymous>)
      at fulfilled (out/src/test/lambda/explorer/genericAwsTreeNode.test.js:8:58)
      at <anonymous>


  13) GenericNode
       initializes name and tooltip:
     AssertionError [ERR_ASSERTION]: undefined == 'myGenericNode'
      at Object.<anonymous> (src/test/lambda/explorer/genericNode.test.ts:21:16)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/genericNode.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/lambda/explorer/genericNode.test.js:7:12)
      at Context.it (src/test/lambda/explorer/genericNode.test.ts:17:51)


  14) LambdaProvider
       displays region nodes with user-friendly region names:
     TypeError: regionNode_1.RegionNode is not a constructor
      at __dirname.getChildren.explorerRegionCodes.forEach.explorerRegionCode (out/src/lambda/lambdaProvider.js:9:8413)
      at Array.forEach (<anonymous>)
      at LambdaProvider.<anonymous> (out/src/lambda/lambdaProvider.js:9:7980)
      at Generator.next (<anonymous>)
      at fulfilled (out/src/lambda/lambdaProvider.js:9:653)
      at <anonymous>


  15) AwsClientBuilder
       createAndConfigureSdkClient
         includes custom user-agent if no options are specified:
     TypeError: awsClientBuilder_1.AWSClientBuilder is not a constructor
      at Object.<anonymous> (src/test/shared/awsClientBuilder.test.ts:62:29)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/shared/awsClientBuilder.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/shared/awsClientBuilder.test.js:7:12)
      at Context.aws_sdk_1.Service.it (src/test/shared/awsClientBuilder.test.ts:61:81)


  16) AwsClientBuilder
       createAndConfigureSdkClient
         includes custom user-agent if not specified in options:
     TypeError: awsClientBuilder_1.AWSClientBuilder is not a constructor
      at Object.<anonymous> (src/test/shared/awsClientBuilder.test.ts:70:29)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/shared/awsClientBuilder.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/shared/awsClientBuilder.test.js:7:12)
      at Context.aws_sdk_1.Service.it (src/test/shared/awsClientBuilder.test.ts:69:81)


  17) AwsClientBuilder
       createAndConfigureSdkClient
         does not override custom user-agent if specified in options:
     TypeError: awsClientBuilder_1.AWSClientBuilder is not a constructor
      at Object.<anonymous> (src/test/shared/awsClientBuilder.test.ts:78:29)
      at Generator.next (<anonymous>)
      at __awaiter (out/src/test/shared/awsClientBuilder.test.js:11:71)
      at new Promise (<anonymous>)
      at __awaiter (out/src/test/shared/awsClientBuilder.test.js:7:12)
      at Context.aws_sdk_1.Service.it (src/test/shared/awsClientBuilder.test.ts:77:86)
```

Is this occurring only in my environment?

**Comment by mpiroc** [comment]
Those tests aren't present in the latest develop. If you're on the latest develop, they're probably left over from a previous build. You can clean by running running `Remove-Item -Recurse -Force ./out` (PowerShell) or `rm -rf ./out` (bash) from the root of your repository. Then rebuild by restarting the `npm: watch` task in vscode or by running the `npm: compile` task. Let me know if that doesn't work.

Sorry about that, we should probably add a 'clean' step before running tests.
