### ISSUE TITLE
Install and run behind proxy

### ISSUE THREAD

**Issue by jesperalmstrom** [aws/aws-toolkit-vscode#185]
**Describe the bug**
When trying to install and run behind a corporate proxy solution (MITM) the extension will time-out after some while with the following message

> Unable to load Lambda Functions, click here to retry

**To Reproduce**
1. Install according to README.md 
2. Run Connect to AWS:

#### Select your profile in Visual Studio Code

1. Launch Visual Studio Code.
2. Select `View > Command Palette...` and search for `AWS`.
3. Select `AWS: Connect to AWS`

**Expected behavior**
Something should load ...
![screenshot from 2018-12-21 16-05-13](https://user-images.githubusercontent.com/6968138/50348892-63ac7780-053a-11e9-9d01-e34f16b9fdfb.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Visual Studio Code Version: 1.30.1
 - AWS Toolkit for Visual Studio Code Version: 0.0.1

**Additional context**
There is a experimental setting in VS Code 
`"http.proxySupport": "on"`
This does not work.

**Comment by nascarsayan** [comment]
+1

**Comment by jesperalmstrom** [comment]
https://github.com/Microsoft/vscode/issues/12588
This could be interesting.

**Comment by jesperalmstrom** [comment]
Tested with latest VSCode and latest aws-toolkit-vscode build but it did not help.
```
2019-03-12 21:48:54 [INFO]: > Downloading latest toolkits endpoint data
2019-03-12 21:48:54 [ERROR]: Error getting resource from https://aws-toolkit-endpoints.s3.amazonaws.com/endpoints.json :  Error: tunneling socket could not be established, statusCode=403
	at ClientRequest.onConnect (/home/jesper/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.0.1/node_modules/tunnel-agent/index.js:166:19)
	at Object.onceWrapper (events.js:273:13)
	at ClientRequest.emit (events.js:182:13)
	at ClientRequest.EventEmitter.emit (domain.js:442:20)
	at Socket.socketOnData (_http_client.js:465:11)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at ClientRequest.onsocket (/usr/share/code/resources/app/node_modules.asar/https-proxy-agent/index.js:182:14)
	at Object.onceWrapper (events.js:273:13)
	at ClientRequest.emit (events.js:187:15)
	at ClientRequest.EventEmitter.emit (domain.js:442:20)
	at tickOnSocket (_http_client.js:651:7)
	at onSocketNT (_http_client.js:667:5)
	at process._tickCallback (internal/process/next_tick.js:63:19)
2019-03-12 21:57:58 [ERROR]: Error: connect ETIMEDOUT 52.94.241.129:443
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

**Comment by bryceitoc9** [comment]
I'm assuming all VS Code-written networking features work fine? If so, the proxy is probably only affecting the AWS JS SDK and CLI (both of which we leverage).

For our future reference, here's how to implement a proxy with the JS SDK (we'll have to implement this) https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html . If you're getting blocked on SAM-related calls (such as deploying functions), this should work if you export these for all new sessions (we'll look to add a configuration for this through VS Code directly): https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html

**Comment by mpiroc** [comment]
We need a well-defined, documented, well-tested story for proxy support. This includes (at mimimum):

* A documented model/instructions for using the toolkit from behind a proxy.
* A formal set of manual and/or automated tests to validate proxy support.

**Comment by justinmk3** [comment]
> For our future reference, here's how to implement a proxy with the JS SDK (we'll have to implement this

For reference:

```diff
diff --git a/src/shared/awsClientBuilder.ts b/src/shared/awsClientBuilder.ts
index 12bfde9bfe86..9622a5d0267e 100644
--- a/src/shared/awsClientBuilder.ts
+++ b/src/shared/awsClientBuilder.ts
@@ -7,6 +7,7 @@ import { ServiceConfigurationOptions } from 'aws-sdk/lib/service'
 import { env, version } from 'vscode'
 import { AwsContext } from './awsContext'
 import { pluginVersion } from './constants'
+import * as proxyagent from 'proxy-agent'
-
 export interface AWSClientBuilder {
     createAndConfigureServiceClient<T>(                      
@@ -34,6 +35,9 @@ export class DefaultAWSClientBuilder implements AWSClientBuilder {
             awsServiceOpts = {}
         }                       
-                                
+        // awsServiceOpts.httpOptions = { agent: new proxyagent('http://example.com') }
+        awsServiceOpts.httpOptions = { proxy: 'http://example.com' }
+                                  
         if (!awsServiceOpts.credentials) {                                 
             awsServiceOpts.credentials = await this._awsContext.getCredentials()
         }
```

**Comment by boyersnet** [comment]
@justinmk3 has there been any more updates on the ability to specify paths on the CA certificates?  I'm having this exact issue and the SAM team sent me over to the toolkit team.  See (https://github.com/awslabs/aws-sam-cli/issues/1981) for details.  A member of my team also mentioned it here (https://github.com/aws/aws-toolkit-vscode/issues/917#issuecomment-583658923).

**Comment by justinmk3** [comment]
@boyersnet no update since https://github.com/aws/aws-toolkit-vscode/issues/185#issuecomment-589500254 . 

> ability to specify paths on the CA certificates?

Do you do this in other software? Examples would be helpful.

**Comment by boyersnet** [comment]
@justinmk3 - In order to get the docker container to work with SAM CLI, I had to pass the path to my cert bundle in as an env variable as AWS_CA_BUNDLE as per AWS CLI documentation.  Once that was done the call to SSM worked as expected from the container.  The problem I face now is how to debug in VS Code with the toolkit.  The toolkit should follow the same pattern as the AWS CLI and respect order specified here: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html

**Comment by justinmk3** [comment]
Thanks for mentioning that. `AWS_CA_BUNDLE` is another mechanism that has not been mentioned yet. Related awsk-sdk-js issue: https://github.com/aws/aws-sdk-js/issues/2970

**Comment by justinmk3** [comment]
Related: VSCode 1.51 release notes mention 

- proxy dialog https://code.visualstudio.com/updates/v1_51#_remember-proxy-credentials 
- `window.enableExperimentalProxyLoginDialog: true` setting

**Comment by AbhilashPurohith** [comment]
Go to Visual Studio -> Settings icon -> Settings -> search for Proxy -> Remove http proxy if any -> uncheck Http: Proxy Strict SSL -> restart Visual studio code

This solved my problem.

If at all you are not able to do it. Try removing proxy from settings.. Go out of VPN and then try it again.

Or else check if u are setting any http proxy in your environmental variables. Remove it and try

**Comment by justinmk3** [comment]
VSCode now has a "Proxy support" item in settings. Try setting it to `override` :

<img width="414" alt="Image" src="https://github.com/user-attachments/assets/62d68a0b-a484-4163-a851-e70335b47b72" />
