### ISSUE TITLE
Can't debug Lambda after clean software install

### ISSUE THREAD

**Issue by efremsternbach** [aws/aws-toolkit-vscode#2296]
**Desktop (please complete the following information):**

-   OS: Windows 10 Pro 21H1 64 bit
-   VS Code version: 1.62.2
-   AWS Toolkit extension version: 1.33
-   SAM CLI : 1.35
-   Docker : 4.20.0
-   Python runtime 3.9

**Question**

I'm submitting this as a question since I don't know if this is a bug or configuration issue on my end. I would appreciate any help.

I recently had the unfortunate necessity of rebuilding my Windows 10 system. Everything seems to be working properly except I am unable to debug my python based Lambda functions as before. I can build my Lambdas with sam and deploy them to AWS without issue.

I am getting the following message:

> 2021-11-16 11:23:38 [INFO]: Traceback (most recent call last):
>   File "runpy.py", line 194, in _run_module_as_main
>   File "runpy.py", line 87, in _run_code
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
>     cli(prog_name="sam")
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 157, in wrapped
>     raise exception  # pylint: disable=raising-bad-type
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 122, in wrapped
>     return_value = func(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
>     actual_result = func(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
>     return func(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 174, in cli
>     do_cli(
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 251, in do_cli
>     ctx.run()
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 197, in run
>     move_template(stack.location, output_template_path, modified_template)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\_utils\template.py", line 89, in move_template
>     modified_template = _update_relative_paths(template_dict, original_root, new_root)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\_utils\template.py", line 159, in _update_relative_paths
>     updated_path = _resolve_relative_to(path, original_root, new_root)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\_utils\template.py", line 233, in _resolve_relative_to
>     return os.path.relpath(
>   File "ntpath.py", line 703, in relpath
> ValueError: path is on mount 'D:', start on mount 'C:'
> 
> 2021-11-16 11:23:38 [WARN]: "sam build" failed: D:/Development/source/repos/GitHub/AWS-Code/production/applications/fundamental_data/fundamental-data-etl/template.yaml

My system is on disk C: and my code is on disk D:

All paths in code or configurations are relative. No absolute paths anywhere

Any ideas or suggestions?

Thanks in advance!

**Comment by JadenSimon** [comment]
Seems like SAM CLI is moving/copying the template then trying to map the paths on the C drive. Can you post from your logs what build arguments the toolkit is sending to SAM CLI? The log message will look something like `Running sam build [BUILD ARGS] (not started)`. It's possible the toolkit is creating a temporary build directory on C which breaks the mapping. If so, you can set the `buildDir` field in the launch config (under "sam") to somewhere on the D drive instead.

**Comment by efremsternbach** [comment]
sam command from log:

> 2021-11-16 13:03:16 [INFO]: Running: (not started) [C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd build --build-dir C:\Users\efrem\AppData\Local\Temp\aws-toolkit-vscode\vsctk7KLV2S\output --template D:/Development/source/repos/GitHub/AWS-Code/production/applications/fundamental_data/fundamental-data-etl/template.yaml --manifest C:\Users\efrem\AppData\Local\Temp\aws-toolkit-vscode\vsctk7KLV2S\debug-requirements.txt]
> 2021-11-16 13:05:13 [ERROR]: Unexpected exitcode (1), expecting (0)

I'm fine with it using temp space on the C: drive to build and the weird thing is that the code is actually being built in --build-dir directory without a problem. Also the listed manifest is where the command line thinks it is. Whatever is happening is happening after the code has been built. So the code is being built without problem but the next step is failing and complaining about disks for some reason.

**Comment by JadenSimon** [comment]
Could you try explicitly setting a build directory in the launch config to somewhere on the D drive? Like this:
```json
    "sam": {
        "buildDir": "${workspaceFolder}/build",
    }
```

I want to say that an absolute path is somehow getting placed somewhere which breaks SAM CLI, but not entirely sure since this apparently was working before. I'll try digging into this on my windows machine as well.

**Comment by efremsternbach** [comment]
Well your suggestion worked, although I'm at a loss to understand why changing the build directory location had such a significant effect. To me this is rather nonintuitive  and I never would have thought to try that. I think it's not unusual for people to have working directories on different disks than the system disk.

Having said that I greatly appreciate your help. Now I can at least use use the debugger.

Thanks!

**Comment by JadenSimon** [comment]
> To me this is rather nonintuitive and I never would have thought to try that. I think it's not unusual for people to have working directories on different disks than the system disk.

Agreed, though it's still a mystery as to what exactly is causing this problem. I tried to reproduce on my windows machine without success. I'm thinking SAM CLI is trying to convert certain relative paths in your template to relative paths on the other drive. At some point those relative paths are converted into absolute paths which breaks things. I'll open an issue with them and see if they have any insight.

**Comment by efremsternbach** [comment]
I realize it can sometimes be difficult to reproduce these kind of problems. However I can tell you the following:

- This is a pristine installation, just rebuilt a few days ago with a fresh Windows 10 Pro 21H1 64 bit install.
- There are no weird permissions on the source code directories, basically accessible by all users.
- The source code used to be on the C: drive before the registry corruption that necessitated my system rebuild. I considered that location unwise after going through the rebuild.
- The Visual Studio Code install is a personal installation, not system wide. I'm the only one on this computer who uses it.

Would be great if this was resolved since I don't think my development environment is at all unusual. In any case I have a workaround for the time being so thanks again.

**Comment by JadenSimon** [comment]
Thanks for the extra info, this will be helpful.
Anything specific in your template that isn't present in the 'Hello World' starter projects? My hunch is that a certain relative path in the template breaks things.

**Comment by efremsternbach** [comment]
This is a complex serverless application template that has a half dozen Lamdas and uses layers. Unfortunately I can't share it with you for intellectual property reasons. However the only paths in the template file are the CodeUri property for the Lambdas and these are all relative paths from the location of the template file

**Comment by justinmk3** [comment]
Another report involving layers: #2395
