### ISSUE TITLE
Fail to list services in ECS cluster when there are more than 10 services

### ISSUE THREAD

**Issue by richardj-bsquare** [aws/aws-toolkit-vscode#2362]
As above indicates

Expand the tree view on an ECS cluster with more 10 services running

**Expected behavior**

You should see all the services

**Desktop (please complete the following information):**

-   OS: macOS Monterey 12.0.1
-   Visual Studio Code Version: 1.62.3
-   AWS Toolkit Version: 1.34.0

**Additional context**

The AWS DescribeServices API limits the number of services to at most 10, so this will always fail beyond 10 as currently implemented.

``` text
2021-12-09 09:52:43 [ERROR]: [InvalidParameterException: service names can have at most 10 items.
	at constructor.p (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:5:7865)
	at constructor.callListeners (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:21118)
	at constructor.emit (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:20827)
	at constructor.emitEvent (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:6680)
	at constructor.e (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:2266)
	at F.runTo (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:18:1767)
	at /Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:18:1979
	at constructor.<anonymous> (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:2477)
	at constructor.<anonymous> (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:6735)
	at constructor.callListeners (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:21222)
	at constructor.emit (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:20827)
	at constructor.emitEvent (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:6680)
	at constructor.e (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:2266)
	at F.runTo (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:18:1767)
	at /Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:18:1979
	at constructor.<anonymous> (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:2477)
	at constructor.<anonymous> (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:6735)
	at constructor.callListeners (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:21222)
	at e (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:6:21003)
	at IncomingMessage.<anonymous> (/Users/richardj/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.34.0/dist/extension.js:1:203602)
	at IncomingMessage.emit (events.js:327:22)
	at IncomingMessage.EventEmitter.emit (domain.js:467:12)
	at endReadableNT (internal/streams/readable.js:1327:12)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  code: 'InvalidParameterException',
  time: 2021-12-09T09:52:43.532Z,
  requestId: 'de24ca65-ec31-4484-a02f-813319f81d4b',
  statusCode: 400,
  retryable: false,
  retryDelay: 69.06900738089251
}
2021-12-09 09:55:32 [INFO]: telemetry: sent batch (size=15)
```

**Comment by justinmk3** [comment]
Toolkit 1.35 includes a fix for this issue. Thank you for reporting it!
