### ISSUE TITLE
Local debug SAM Build Error: PythonPipBuilder:ResolveDependencies - {future==0.18.2(sdist)}

### ISSUE THREAD

**Issue by vishnurpiper** [aws/aws-toolkit-vscode#2724]
## Problem
SAM application (initialized using the cookie cutter template - https://github.com/aws-samples/cookiecutter-aws-sam-python) fails when starting local debug
## Steps to reproduce the issue

1. Run `sam init --location gh:aws-samples/cookiecutter-aws-sam-python ` and create a sample SAM application
2. Update requirements.txt in the hello_world function folder - uncomment `aws-lambda-powertools` to add layer dependency
3. Add Debug Config - create `launch.json`
4. F5 to debug
5. See error 
6. Running a sam build works just fine, its the build that's triggered as part of the debug command that's failing at the build step.

```
2022-06-28 11:48:56 [INFO]: Preparing to debug locally: Lambda "app.hello_name"
2022-06-28 11:48:56 [INFO]: Building SAM application...
2022-06-28 11:48:56 [INFO]: Command: (not started) [/usr/local/bin/sam build --debug --build-dir /tmp/aws-toolkit-vscode/vsctk3O64wM/output --template /tmp/aws-toolkit-vscode/vsctk3O64wM/app___vsctk___template.yaml --base-dir /home/<user>/mysamprojects/cookie-cutter-experiment/hello_world --manifest /tmp/aws-toolkit-vscode/vsctk3O64wM/debug-requirements.txt]
2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,286 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-06-28 11:48:57,286 | Using config file: samconfig.toml, config environment: default

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,286 | Expand command line arguments to:
2022-06-28 11:48:57,286 | --template_file=/tmp/aws-toolkit-vscode/vsctk3O64wM/app___vsctk___template.yaml --build_dir=/tmp/aws-toolkit-vscode/vsctk3O64wM/output --base_dir=/home/<user>/mysamprojects/cookie-cutter-experiment/hello_world --manifest=/tmp/aws-toolkit-vscode/vsctk3O64wM/debug-requirements.txt --cache_dir=.aws-sam/cache 

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,414 | 'build' command is called

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,416 | No Parameters detected in the template

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,429 | There is no customer defined id or cdk path defined for resource helloworld, so we will use the resource logical id as the resource id

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,429 | 0 stacks found in the template
2022-06-28 11:48:57,430 | No Parameters detected in the template

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,442 | There is no customer defined id or cdk path defined for resource helloworld, so we will use the resource logical id as the resource id

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,442 | 1 resources found in the stack 
2022-06-28 11:48:57,442 | Found Serverless function with name='helloworld' and CodeUri='/home/<user>/mysamprojects/cookie-cutter-experiment/hello_world'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,445 | Instantiating build definitions

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,445 | No previous build graph found, generating new one
2022-06-28 11:48:57,445 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(python3.9, /home/<user>/mysamprojects/cookie-cutter-experiment/hello_world, Zip, , f641a186-b3a6-4718-a4d7-0b57425c12b1, {}, {}, x86_64, []), Function: Function(function_id='helloworld', name='helloworld', functionname='helloworld', runtime='python3.9', memory=None, timeout=None, handler='app.hello_name', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/home/<user>/mysamprojects/cookie-cutter-experiment/hello_world', environment={'Variables': OrderedDict()}, rolearn=None, layers=[], events=None, metadata={'SamResourceId': 'helloworld'}, inlinecode=None, codesign_config_arn=None, architectures=None, function_url_config=None, stack_path=''))

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,447 | Building codeuri: /home/<user>/mysamprojects/cookie-cutter-experiment/hello_world runtime: python3.9 metadata: {} architecture: x86_64 functions: ['helloworld']

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,447 | Building to following folder /tmp/aws-toolkit-vscode/vsctk3O64wM/output/helloworld

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,448 | Loading workflow module 'aws_lambda_builders.workflows'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,450 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,452 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,453 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,455 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,458 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,459 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,460 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,462 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,463 | Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,463 | Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,799 | Running workflow 'PythonPipBuilder'

2022-06-28 11:48:57 [INFO]: 2022-06-28 11:48:57,799 | Running PythonPipBuilder:ResolveDependencies

2022-06-28 11:48:58 [INFO]: 2022-06-28 11:48:58,140 | calling pip download -r /tmp/aws-toolkit-vscode/vsctk3O64wM/debug-requirements.txt --dest /tmp/tmpsh9nw3mk --exists-action i

2022-06-28 11:49:03 [INFO]: 2022-06-28 11:49:03,695 | Non zero rc (2) from the setup.py egg_info command: b"Usage: sam [OPTIONS] COMMAND [ARGS]...\nTry 'sam -h' for help.\n\nError: no such option: -c\n"

2022-06-28 11:49:03 [INFO]: 2022-06-28 11:49:03,695 | Using fallback location for PKG-INFO file in package directory: /tmp/tmpvxr2tkzq/future-0.18.2

2022-06-28 11:49:03 [INFO]: 2022-06-28 11:49:03,704 | Full dependency closure: {fastjsonschema==2.15.3(wheel), python-dateutil==2.8.2(wheel), s3transfer==0.6.0(wheel), boto3==1.24.18(wheel), aws-xray-sdk==2.9.0(wheel), debugpy==1.6.0(wheel), jmespath==1.0.1(wheel), wrapt==1.14.1(wheel), six==1.16.0(wheel), aws-lambda-powertools==1.26.2(wheel), future==0.18.2(sdist), botocore==1.27.18(wheel), urllib3==1.26.9(wheel)}

2022-06-28 11:49:03 [INFO]: 2022-06-28 11:49:03,704 | initial compatible: {python-dateutil==2.8.2(wheel), urllib3==1.26.9(wheel), boto3==1.24.18(wheel), s3transfer==0.6.0(wheel), aws-xray-sdk==2.9.0(wheel), debugpy==1.6.0(wheel), jmespath==1.0.1(wheel), wrapt==1.14.1(wheel), six==1.16.0(wheel), aws-lambda-powertools==1.26.2(wheel), botocore==1.27.18(wheel), fastjsonschema==2.15.3(wheel)}
2022-06-28 11:49:03,704 | initial incompatible: {future==0.18.2(sdist)}
2022-06-28 11:49:03,705 | Downloading missing wheels: {future==0.18.2(sdist)}
2022-06-28 11:49:03,705 | calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp39 --dest /tmp/tmpsh9nw3mk future==0.18.2

2022-06-28 11:49:04 [INFO]: 2022-06-28 11:49:04,665 | compatible wheels after second download pass: {fastjsonschema==2.15.3(wheel), python-dateutil==2.8.2(wheel), s3transfer==0.6.0(wheel), boto3==1.24.18(wheel), aws-xray-sdk==2.9.0(wheel), debugpy==1.6.0(wheel), jmespath==1.0.1(wheel), wrapt==1.14.1(wheel), six==1.16.0(wheel), aws-lambda-powertools==1.26.2(wheel), botocore==1.27.18(wheel), urllib3==1.26.9(wheel)}

2022-06-28 11:49:04 [INFO]: 2022-06-28 11:49:04,666 | Build missing wheels from sdists (C compiling True): {future==0.18.2(sdist)}
2022-06-28 11:49:04,666 | calling pip wheel --no-deps --wheel-dir /tmp/tmpsh9nw3mk /tmp/tmpsh9nw3mk/future-0.18.2.tar.gz

2022-06-28 11:49:08 [INFO]: 2022-06-28 11:49:08,676 | compatible after building wheels (no C compiling): {fastjsonschema==2.15.3(wheel), python-dateutil==2.8.2(wheel), s3transfer==0.6.0(wheel), boto3==1.24.18(wheel), aws-xray-sdk==2.9.0(wheel), debugpy==1.6.0(wheel), jmespath==1.0.1(wheel), wrapt==1.14.1(wheel), six==1.16.0(wheel), aws-lambda-powertools==1.26.2(wheel), botocore==1.27.18(wheel), urllib3==1.26.9(wheel)}

2022-06-28 11:49:08 [INFO]: 2022-06-28 11:49:08,677 | Build missing wheels from sdists (C compiling False): {future==0.18.2(sdist)}
2022-06-28 11:49:08,677 | calling pip wheel --no-deps --wheel-dir /tmp/tmpsh9nw3mk /tmp/tmpsh9nw3mk/future-0.18.2.tar.gz

2022-06-28 11:49:12 [INFO]: 2022-06-28 11:49:12,775 | compatible after building wheels (C compiling): {fastjsonschema==2.15.3(wheel), python-dateutil==2.8.2(wheel), s3transfer==0.6.0(wheel), boto3==1.24.18(wheel), aws-xray-sdk==2.9.0(wheel), debugpy==1.6.0(wheel), jmespath==1.0.1(wheel), wrapt==1.14.1(wheel), six==1.16.0(wheel), aws-lambda-powertools==1.26.2(wheel), botocore==1.27.18(wheel), urllib3==1.26.9(wheel)}

2022-06-28 11:49:12 [INFO]: 2022-06-28 11:49:12,776 | Final compatible: {fastjsonschema==2.15.3(wheel), python-dateutil==2.8.2(wheel), s3transfer==0.6.0(wheel), boto3==1.24.18(wheel), aws-xray-sdk==2.9.0(wheel), debugpy==1.6.0(wheel), jmespath==1.0.1(wheel), wrapt==1.14.1(wheel), six==1.16.0(wheel), aws-lambda-powertools==1.26.2(wheel), botocore==1.27.18(wheel), urllib3==1.26.9(wheel)}
2022-06-28 11:49:12,776 | Final incompatible: set()
2022-06-28 11:49:12,776 | Final missing wheels: {future==0.18.2(sdist)}

2022-06-28 11:49:13 [INFO]: 2022-06-28 11:49:13,580 | PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "aws_lambda_builders/workflows/python_pip/actions.py", line 54, in execute
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 156, in build_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 261, in build_site_packages
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {future==0.18.2(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 302, in run
  File "aws_lambda_builders/workflows/python_pip/actions.py", line 57, in execute
aws_lambda_builders.actions.ActionFailedError: {future==0.18.2(sdist)}

2022-06-28 11:49:13 [INFO]: 
Build Failed

2022-06-28 11:49:13 [INFO]: 2022-06-28 11:49:13,587 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '05204aae-56b6-447e-aa07-9ad567672a97', 'installationId': '994b9b2c-d6e1-41d1-bbbc-e955d3adc192', 'sessionId': '323c5e49-7523-48e9-a303-15774354698a', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.52.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 16301, 'exitReason': 'WorkflowFailedError', 'exitCode': 1}}]}

2022-06-28 11:49:14 [INFO]: 2022-06-28 11:49:14,011 | Telemetry response: 200

2022-06-28 11:49:14 [INFO]: Error: PythonPipBuilder:ResolveDependencies - {future==0.18.2(sdist)}

2022-06-28 11:49:14 [WARN]: "sam build" failed: /tmp/aws-toolkit-vscode/vsctk3O64wM/app___vsctk___template.yaml


```

## Expected behavior
Expecting local debugging to work

## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 10 (running WSL - Ubuntu 20.04)
-   Visual Studio Code version: 1.68.1 (with remote -wsl extension)
-   AWS Toolkit version: v1.42.0

**Comment by vishnurpiper** [comment]
> Looks like you might need to build in the container due to `debugpy`, a dependency the Toolkit adds:
> 
> ```
> 
> 2022-06-28 11:49:03,704 | initial incompatible: {future==0.18.2(sdist)}
> 
> 2022-06-28 11:49:03,705 | Downloading missing wheels: {future==0.18.2(sdist)}
> 
> ```
> 
> 
> 
> `sdist` means there's no binary ('wheel') that can be downloaded. See if adding the following to your launch config works:
> 
> ```json
> 
> "sam": {
> 
>     "containerBuild": true
> 
> }
> 
> ```

That did it! Thanks much
