### ISSUE TITLE
ECS error: "InvalidParameterException: Invalid identifier: Identifier is for cluster "

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#2915]
steps to reproduce:

1. try to expand ECS cluster to show running services.
2. error:
    - <img width="325" alt="image" src="https://user-images.githubusercontent.com/55561878/193358133-8921f6bd-6657-4c73-91e0-2602db642941.png">

seems to fail here:

https://github.com/aws/aws-toolkit-vscode/blob/742a19c81b4d95e98e3e82308541b6be9d28ef0c/src/shared/treeview/resource.ts#L46-L49

```
2022-09-30 14:19:50 [ERROR]: [InvalidParameterException: Invalid identifier: Identifier is for cluster jan7. Your cluster is default
	at Request.extractError (/Volumes/workplace/aws-toolkit-vscode/node_modules/aws-sdk/lib/protocol/json.js:52:27)
	at Request.callListeners (/Volumes/workplace/aws-toolkit-vscode/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
	at Request.emit (/Volumes/workplace/aws-toolkit-vscode/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
	at Request.emit (/Volumes/workplace/aws-toolkit-vscode/node_modules/aws-sdk/lib/request.js:686:14)
	at Request.transition (/Volumes/workplace/aws-toolkit-vscode/node_modules/aws-sdk/lib/request.js:22:10)
	at AcceptorStateMachine.runTo (/Volumes/workplace/aws-toolkit-vscode/node_modules/aws-sdk/lib/state_machine.js:14:12)
	at /Volumes/workplace/aws-toolkit-vscode/node_modules/aws-sdk/lib/state_machine.js:26:10
	at Request.<anonymous> (/Volumes/workplace/aws-toolkit-vscode/node_modules/aws-sdk/lib/request.js:38:9)
	at Request.<anonymous> (/Volumes/workplace/aws-toolkit-vscode/node_modules/aws-sdk/lib/request.js:688:12)
```

**Comment by justinmk3** [comment]
confirmed that before https://github.com/aws/aws-toolkit-vscode/pull/2905 , I'm able to expand services/tasks:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/55561878/193358612-7d224610-8e01-4231-834e-c14e34ba7d07.png">

**Comment by justinmk3** [comment]
fixed by https://github.com/aws/aws-toolkit-vscode/pull/2916
