### ISSUE TITLE
Unable to authenticate connection using IAM Identity Center

### ISSUE THREAD

**Issue by escherrer** [aws/aws-toolkit-vscode#3082]
Hello,

I've been trying for a few days but can't seem to get connected using IAM Identity Center. I have confirmed that IAM IC is setup correctly as I can manually log into using the /start link in the browser and have full access to my account. I've also tried to debug the toolkit extension to get a better error but I'm going to need some time to get up to speed on that.

[VSCodeIntegration]
sso_start_url = https://redacted.awsapps.com/start
sso_region = us-east-1
sso_account_id = redacted
sso_role_name = AWSServiceRoleForSSO
region = us-east-1

And here is the log file:

2023-01-03 11:59:41 [ERROR]: log level: info
2023-01-03 11:59:42 [INFO]: Retrieving AWS endpoint data
2023-01-03 11:59:42 [INFO]: OS: Windows_NT x64 10.0.22621
2023-01-03 11:59:42 [INFO]: Visual Studio Code extension host:  1.74.2
2023-01-03 11:59:42 [INFO]: AWS Toolkit:  1.60.0
2023-01-03 11:59:42 [INFO]: node: 16.14.2
2023-01-03 11:59:42 [INFO]: electron: 19.1.8
2023-01-03 11:59:44 [WARN]: auth (codecatalyst): removing saved connection "codecatalyst.savedConnectionId" as it no longer exists
2023-01-03 11:59:44 [WARN]: auth (codewhisperer): removing saved connection "codewhisperer.savedConnectionId" as it no longer exists
2023-01-03 12:00:11 [WARN]: credentials (sso): invalidating stored token: No access
2023-01-03 12:00:11 [ERROR]: _aws.auth.reauthenticate: Error: Unable to authenticate connection
	 -> ForbiddenException: No access
2023-01-03 12:04:42 [INFO]: telemetry: sent batch (size=14)

Any help is appreciated.

**Comment by escherrer** [comment]
I just tried with #3023 because it addresses a similar issue and got the following error:

2023-01-03 21:17:30 [ERROR]: log level: info
2023-01-03 21:17:31 [INFO]: Retrieving AWS endpoint data
2023-01-03 21:17:31 [INFO]: OS: Windows_NT x64 10.0.22621
2023-01-03 21:17:31 [INFO]: Visual Studio Code extension host:  1.74.2
2023-01-03 21:17:31 [INFO]: AWS Toolkit:  testPluginVersion
2023-01-03 21:17:31 [INFO]: node: 16.14.2
2023-01-03 21:17:31 [INFO]: electron: 19.1.8
2023-01-03 21:17:31 [WARN]: CloudFormationTemplateRegistry: addWatchPattern(**/*.{yaml,yml}): no workspace
2023-01-03 21:17:32 [WARN]: auth (codecatalyst): removing saved connection "codecatalyst.savedConnectionId" as it no longer exists
2023-01-03 21:17:32 [WARN]: auth (codewhisperer): removing saved connection "codewhisperer.savedConnectionId" as it no longer exists
2023-01-03 21:17:32 [WARN]: CodelensRootRegistry: addWatchPattern(**/requirements.txt): no workspace
2023-01-03 21:17:32 [WARN]: CodelensRootRegistry: addWatchPattern(**/package.json): no workspace
2023-01-03 21:17:32 [WARN]: CodelensRootRegistry: addWatchPattern(**/*.csproj): no workspace
2023-01-03 21:17:32 [WARN]: CodelensRootRegistry: addWatchPattern(**/go.mod): no workspace
2023-01-03 21:17:32 [WARN]: CodelensRootRegistry: addWatchPattern(**/build.gradle): no workspace
2023-01-03 21:17:32 [WARN]: CodelensRootRegistry: addWatchPattern(**/pom.xml): no workspace
2023-01-03 21:18:00 [WARN]: credentials (sso): invalidating stored token: No access
2023-01-03 21:18:00 [ERROR]: _aws.auth.reauthenticate: [ToolkitError: Unable to authenticate connection
	at ToolkitError.chain (c:\Git\Repos\IAMICFix\aws-toolkit-vscode\dist\src\shared\errors.js:79:16)
	at c:\Git\Repos\IAMICFix\aws-toolkit-vscode\dist\src\credentials\auth.js:814:37
	at Generator.throw (<anonymous>)
	at rejected (c:\Git\Repos\IAMICFix\aws-toolkit-vscode\dist\src\credentials\auth.js:10:65)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)] {
  info: [Object],
  code: undefined,
  details: undefined,
  cause: [SSOServiceException]
}

**Comment by JadenSimon** [comment]
Hi @escherrer,

Thanks for trying out my PR, it helps a lot! The error message from the SSO service is obscure but it looks like you might not have access to either `ListAccounts`, `ListAccountRoles`, or `GetRoleCredentials`?. Restricted permissions are not handled nicely by the current implementation. 

Considering that the public Toolkit version only uses `GetRoleCredentials`, I think this issue is similar to https://github.com/aws/aws-cli/issues/6316. Can you verify that `sso_account_id` and `sso_role_name` are accurate?

**Comment by escherrer** [comment]
Hi @JadenSimon,

Thanks for the guidance. I will verify those fields and recheck all the permissions. I guess it's somewhere in auth.js that I could pinpoint the specific access failure?

**Comment by JadenSimon** [comment]
@escherrer 

Unfortunately the failure is coming from the service which is intentionally opaque about the exact cause. But I think I see the problem: `AWSServiceRoleForSSO` is being used as the role name but that's an automatically generated role used by the IAM identity center service. Have you create a permission set for your user/group? Creating a permission set will create a role in your account(s) which I believe always have the same name as the permission set. The name is what you'll use for `sso_role_name` instead of `AWSServiceRoleForSSO`.

https://github.com/aws/aws-toolkit-vscode/pull/3023 makes this process slightly easier because you can create a new IAM identity center connection and have all available accounts/roles listed automatically. You can test this by following these steps:
1. Run the `AWS: Connect to AWS` command from the command palette 
2. Select `Add New Connection` ->  `Connect using AWS IAM Identity Center`
3. Use your `sso_region` and `sso_start_url` values for the remaining two steps
4. Under the AWS Explorer, click the `Select IAM Credentials to View Resources` node
5. If any accounts/roles are available, you should see them listed

**Comment by escherrer** [comment]
@JadenSimon thanks so much, that was indeed the issue. I saw the sso_role_name name and clumsily assumed it must be a IAM role. I have created and assigned a permission set and it's working now. Thanks so much for the help :)
