### ISSUE TITLE
Explorer-> Resources: Conflict: Multiple items have the key 'AWS::Logs::LogStream'

### ISSUE THREAD

**Issue by escherrer** [aws/aws-toolkit-vscode#3132]
## Problem
When expanding the Resources node in the Explorer it should list resources

## Steps to reproduce the issue

1. Go to Explorer -> Resources
3. See error:
2023-01-28 14:49:46 [ERROR]: [Error: Conflict: Multiple items have the key 'AWS::Logs::LogStream'
	at fr (c:\Users\jogne\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1337:472)
	at WD.updateChildren (c:\Users\jogne\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1997:809)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.getChildNodes (c:\Users\jogne\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1997:420)
	at async Cm (c:\Users\jogne\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1541:112)
	at async WD.getChildren (c:\Users\jogne\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1997:386)
	at async Z3.getChildren (c:\Users\jogne\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:2034:930)
	at async w.R (c:\Users\jogne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:19075)
	at async w.getChildren (c:\Users\jogne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:15494)]

## Expected behavior
List the resources

## System details (run the `AWS: About Toolkit` command)

OS: Windows_NT x64 10.0.22621
Visual Studio Code extension host:  1.74.3
AWS Toolkit:  1.61.0
node: 16.14.2
electron: 19.1.8

**Comment by mengeworkman** [comment]
Same on Mac M1

Go to Explorer -> Resources
See error:
2023-01-28 16:14:09 [ERROR]: Error: Conflict: Multiple items have the key 'AWS::Logs::LogStream'
    at fr (/Users/workcomputer/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.61.0/dist/src/main.js:1337:472)
    at WD.updateChildren (/Users/workcomputer/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.61.0/dist/src/main.js:1997:809)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.getChildNodes (/Users/workcomputer/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.61.0/dist/src/main.js:1997:420)
    at Cm (/Users/workcomputer/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.61.0/dist/src/main.js:1541:112)
    at WD.getChildren (/Users/workcomputer/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.61.0/dist/src/main.js:1997:386)
    at Z3.getChildren (/Users/workcomputer/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.61.0/dist/src/main.js:2034:930)
    at w.R (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:19075)
    at w.getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:15494)

OS: Darwin arm64 22.2.0
Visual Studio Code extension host:  1.74.3
AWS Toolkit:  1.61.0
node: 16.14.2
electron: 19.1.8

**Comment by heisen92** [comment]
Im following the following youtube tutorial:  
https://www.youtube.com/watch?v=iRaai1IBlB0
After enter terraform plan and terraform apply, the output says:
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

but im having exactly the same error

2023-01-28 21:18:31 [ERROR]: [Error: Conflict: Multiple items have the key 'AWS::Logs::LogStream'
	at fr (c:\Users\eviarrd\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1337:472)
	at WD.updateChildren (c:\Users\eviarrd\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1997:809)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.getChildNodes (c:\Users\eviarrd\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1997:420)
	at async Cm (c:\Users\eviarrd\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1541:112)
	at async WD.getChildren (c:\Users\eviarrd\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1997:386)
	at async Z3.getChildren (c:\Users\eviarrd\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:2034:930)
	at async w.R (c:\Users\eviarrd\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:19075)
	at async w.getChildren (c:\Users\eviarrd\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:15494)]

im in Windows 10

**Comment by dankao** [comment]
Same error. Windows 11 x86_64.

```
2023-01-29 23:10:05 [INFO]: Retrieving AWS endpoint data
2023-01-29 23:10:05 [INFO]: OS: Windows_NT x64 10.0.22621
2023-01-29 23:10:05 [INFO]: Visual Studio Code extension host:  1.74.3
2023-01-29 23:10:05 [INFO]: AWS Toolkit:  1.61.0
2023-01-29 23:10:05 [INFO]: node: 16.14.2
2023-01-29 23:10:05 [INFO]: electron: 19.1.8
```
```
[ERROR]: [Error: Conflict: Multiple items have the key 'AWS::Logs::LogStream'
	at fr (c:\Users\danka\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1337:472)
	at WD.updateChildren (c:\Users\danka\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1997:809)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.getChildNodes (c:\Users\danka\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1997:420)
	at async Cm (c:\Users\danka\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1541:112)
	at async WD.getChildren (c:\Users\danka\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:1997:386)
	at async Z3.getChildren (c:\Users\danka\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.61.0\dist\src\main.js:2034:930)
	at async w.R (c:\Users\danka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:19075)
	at async w.getChildren (c:\Users\danka\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:15494)]
```

**Comment by escherrer** [comment]
Thanks @JadenSimon ! Just got the update today and this is so cool so see all these resources and quickly get the definitions. Much appreciated.
