### ISSUE TITLE
Deploy SAM Application can't handle broken symlinks in workspace

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-vscode#327]
**Describe the bug**
```
ENOENT: no such file or directory, stat '/Users/richali/tmp/adfssssssasdfasfda/symlink'
```
**To Reproduce**
* In the workspace with a SAM project, create a symlink to an invalid path: `ln -s /not/a/real/path symlink`
* Command Palette -> Deploy SAM Application 

**Expected behavior**
* Ignore the broken symlink

**Comment by justinmk3** [comment]
Still happens with Toolkit 1.19. 

Since https://github.com/aws/aws-toolkit-vscode/commit/5e17cf74a2c0cfe94dc9bb68a5719ccb9cd5332c , deploy actually proceeds anyways. But that is probably an anti-feature in this case.

## Reference

`sam` invokes `npm pack` which appears to be failing:

```
2021-01-26 17:19:28 [INFO]: 2021-01-26 17:19:28,920 | Found workflow 'NodejsNpmBuilder' to support capabilities 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-01-26 17:19:28,921 | Running workflow 'NodejsNpmBuilder'
2021-01-26 17:19:28,921 | Running NodejsNpmBuilder:NpmPack
2021-01-26 17:19:28,921 | NODEJS packaging file:/Volumes/workplace/sam-samples/n12/hello-world to /var/folders/43/7yp29jpx7dg7x4khq7418w7mhcztr9/T/tmpy1mbwd2l
2021-01-26 17:19:28,921 | executing NPM: ['npm', 'pack', '-q', 'file:/Volumes/workplace/sam-samples/n12/hello-world']

2021-01-26 17:19:29 [INFO]: 2021-01-26 17:19:29,569 | NodejsNpmBuilder:NpmPack failed
Traceback (most recent call last):
  File "/Volumes/workplace/aws-sam-cli/venv/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm/actions.py", line 59, in execute
    tarfile_name = self.subprocess_npm.run(["pack", "-q", package_path], cwd=self.scratch_dir).splitlines()[-1]
  File "/Volumes/workplace/aws-sam-cli/venv/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm/npm.py", line 85, in run
    raise NpmExecutionError(message=err.decode("utf8").strip())
aws_lambda_builders.workflows.nodejs_npm.npm.NpmExecutionError: NPM Failed: npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Volumes/workplace/sam-samples/n12/hello-world/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Volumes/workplace/sam-samples/n12/hello-world/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

- So this is a limitation of `npm` itself. 
    - This does **not** happen with a python SAM project, for example.
