### ISSUE TITLE
CI: failing CodeCatalyst E2E test: Timed out waiting to install remote SSH extension

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#3390]
## Problem

e2e tests failing because of vscode extension install issue. 

```
  1) Test how this codebase uses the CodeCatalyst API
       Dev Environment functionality
         prompts to install the ssh extension if not available:
     Error: Timed out waiting to install remote SSH extension
      at /codebuild/output/src862865382/src/github.com/aws/aws-toolkit-vscode/src/testE2E/codecatalyst/client.test.ts:213:27

  2) Test how this codebase uses the CodeCatalyst API
       Dev Environment functionality
         connects to a running Dev Environment:
     Error: Remote SSH extension not installed
      at tools (src/codecatalyst/tools.ts:42:40)
      at Generator.next (<anonymous>)
      at /codebuild/output/src862865382/src/github.com/aws/aws-toolkit-vscode/src/codecatalyst/tools.ts:12:71
      at new Promise (<anonymous>)
      at localize (src/codecatalyst/tools.ts:8:12)
      at ensureDependencies (src/codecatalyst/tools.ts:39:12)
      at devenvStop (src/codecatalyst/model.ts:192:42)
      at Generator.next (<anonymous>)
      at /codebuild/output/src862865382/src/github.com/aws/aws-toolkit-vscode/src/codecatalyst/model.ts:12:71
      at new Promise (<anonymous>)
      at exports (src/codecatalyst/model.ts:8:12)
      at prepareDevEnvConnection (src/codecatalyst/model.ts:191:12)
      at Context.backend_1 (src/testE2E/codecatalyst/client.test.ts:220:69)
      at Generator.next (<anonymous>)
      at /codebuild/output/src862865382/src/github.com/aws/aws-toolkit-vscode/src/testE2E/codecatalyst/client.test.ts:12:71
      at new Promise (<anonymous>)
      at spaceName (src/testE2E/codecatalyst/client.test.ts:8:12)
      at Context.<anonymous> (src/testE2E/codecatalyst/client.test.ts:218:20)
      at Context.fn (src/test/setupUtil.ts:31:24)

  3) Test how this codebase uses the CodeCatalyst API
       Dev Environment functionality
         stops a running Dev Environment, then starts it up again:
     Error: Remote SSH extension not installed
      at tools (src/codecatalyst/tools.ts:42:40)
```

**Comment by JadenSimon** [comment]
The tests are failing because the minimum version we specified for the remote ssh extension isn't compatible with our minimum version of VS Code. We can make that clearer in the tests though.

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/3391
