### ISSUE TITLE
tests: noisy stepfunctions test

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#3399]
## Problem

[Test](https://github.com/aws/aws-toolkit-vscode/blob/40f8380b269d2d282b810f9ca374bdaba8aeedeb/src/test/eventSchemas/commands/downloadSchemaItemCode.test.ts#L609) `should throw error if user picks Cancel when collision occurs` is noisy and adds (multiple) such messages to the CI log: 

```
rejected promise not handled within 1 second: Error: Download code bindings cancelled
stack trace: Error: Download code bindings cancelled
    at Context.<anonymous> (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/src/test/eventSchemas/commands/downloadSchemaItemCode.test.ts:610:27)
    at Generator.next (<anonymous>)
    at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/dist/src/test/eventSchemas/commands/downloadSchemaItemCode.test.js:12:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/dist/src/test/eventSchemas/commands/downloadSchemaItemCode.test.js:8:12)
    at Context.<anonymous> (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/dist/src/test/eventSchemas/commands/downloadSchemaItemCode.test.js:519:20)
    at Context.fn (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/src/test/setupUtil.ts:31:24)
    at callFn (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:666:10)
    at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:789:12
    at next (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:581:14)
    at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:591:7
    at next (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:474:14)
    at cbHookRun (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:539:7)
    at done (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runnable.js:310:5)
    at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/node_modules/mocha/lib/runnable.js:371:11
```

## Solution

Don't log this error, or handle the rejection properly. Or remove/re-arrange the test, is it actually a useful test?

**Comment by justinmk3** [comment]
This error no longer appears in CI logs. "rejected promise not handled" is checked by CI: https://github.com/aws/aws-toolkit-vscode/pull/4199
