### ISSUE TITLE
CI: failing "Insiders" build

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#3442]
Integ and E2E job fails for vscode Insiders:

```
Downloaded VS Code into /codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-linux-x64-insiders
VS Code test instance location: /codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-linux-x64-insiders/code-insiders
Invoking vscode CLI command:
    "/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-linux-x64-insiders/bin/code-insiders" ["--extensions-dir=/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/extensions","--user-data-dir=/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/user-data","--version","--user-data-dir","/tmp/"]
1.79.0-insider
efb49cc271d6eea5634ac395e36e1e4cd108a447
x64

Installing VS Code Extension: ms-python.python
Invoking vscode CLI command:
    "/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-linux-x64-insiders/bin/code-insiders" ["--extensions-dir=/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/extensions","--user-data-dir=/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/user-data","--install-extension","ms-python.python","--user-data-dir","/tmp/"]
output: [
  null,
  "Installing extensions...\nInstalling extension 'ms-python.python'...\n",
  "Option 'user-data-dir' is defined more than once. Using value '/tmp/'.\n" +
    '(node:9612) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n' +
    '(Use `code-insiders --trace-deprecation ...` to show where the warning was created)\n' +
    "EXDEV: cross-device link not permitted, rename '/tmp/SJ9o4FAh' -> '/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/extensions/ms-python.python-2023.8.0'\n" +
    'Failed Installing Extensions: ms-python.python\n'
]
Error: VS Code CLI command failed (exit-code: 1): /codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/vscode-linux-x64-insiders/bin/code-insiders --extensions-dir=/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/extensions,--user-data-dir=/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/.vscode-test/user-data,--install-extension,ms-python.python,--user-data-dir,/tmp/
    at /codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:68:15
    at Generator.next (<anonymous>)
    at /codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:12:71
    at new Promise (<anonymous>)
    at __awaiter (/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:8:12)
    at invokeVSCodeCli (/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:58:12)
    at /codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:80:23
    at Generator.next (<anonymous>)
    at /codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:12:71
    at new Promise (<anonymous>)
    at __awaiter (/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:8:12)
    at installVSCodeExtension (/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:83:12)
    at /codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:122:11
    at Generator.next (<anonymous>)
    at fulfilled (/codebuild/output/src281821284/src/github.com/aws/aws-toolkit-vscode/scripts/test/launchTestUtilities.ts:9:58)
    at runMicrotasks (<anonymous>)
Failed to run tests
```

**Comment by justinmk3** [comment]
no longer occurs
