### ISSUE TITLE
unreliable test: "Auth Shared ini files"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#3735]
https://github.com/aws/aws-toolkit-vscode/blob/590c2fa7d7d0641b454df6f86a01e118cb9334e5/packages/core/src/test/credentials/auth.test.ts#L426

```
 1) Auth
       Shared ini files
Error: 1 tests failed.
         does not cache if the credentials file changes:
    at d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\testRunner.ts:90:28

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected
    at MultiReporters.done (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha-multi-reporters\lib\MultiReporters.js:124:16)

    at done (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha\lib\mocha.js:1007:16)
  {
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
+   accessKeyId: 'x',
+   secretAccessKey: 'x',
-   accessKeyId: 'y',
-   secretAccessKey: 'y',
    sessionToken: undefined
  }
      + expected - actual

       {
      -  "accessKeyId": "x"
      -  "secretAccessKey": "x"
      +  "accessKeyId": "y"
      +  "secretAccessKey": "y"
         "sessionToken": [undefined]
       }
```

**Comment by Hweinstock** [comment]
Fixed by https://github.com/aws/aws-toolkit-vscode/pull/5979
