### ISSUE TITLE
tests: "ENOSPC: System limit for number of file watchers reached"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#3815]
# Problem

Linux unit tests sometimes fail:

```
  1) WinstonToolkitLogger
       logs to a file
         does not log a lower level:
     Error: ENOSPC: System limit for number of file watchers reached, watch '/tmp/aws-toolkit-vscode/vsctkxDXHCi'
      at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
      at Object.watch (node:fs:2247:34)
      at /codebuild/output/src3581993545/src/github.com/aws/aws-toolkit-vscode/src/test/shared/logger/winstonToolkitLogger.test.ts:27:28
      at new Promise (<anonymous>)
      at /codebuild/output/src3581993545/src/github.com/aws/aws-toolkit-vscode/src/test/shared/logger/winstonToolkitLogger.test.ts:26:19
```

# Proposal

- Eliminate `createLogWatcher` https://github.com/aws/aws-toolkit-vscode/blob/e7116952ab3503199420f30ce8656e07d8b36ad0/src/shared/logger/activation.ts#L168
    - it only shows a message, no other functional purpose
    - ![image](https://github.com/aws/aws-toolkit-vscode/assets/55561878/1ab76df1-a0f8-4a7e-b01a-c6b77000afff)
    - if the log file is deleted, Toolkit continues to work correctly, and logs to the vscode output channel

**Comment by justinmk3** [comment]
Noticed this in cloud9 logs w/ Toolkit 1.93:

```
2023-10-06 17:22:48 [INFO]: node: 16.20.1
2023-10-06 17:22:49 [WARN]: Failed to clean-up old logs: Error (FileSystemError): $readdir not implemented [Unknown]
```
