### ISSUE TITLE
Local Debug Error Cannot find module 'app'

### ISSUE THREAD

**Issue by DavidCabaniuk** [aws/aws-toolkit-vscode#3833]
## System details (run the `AWS: About Toolkit` command)

-   OS: Windows 10
-   Visual Studio Code version: 1.82.2
-   AWS Toolkit version: v1.89.0

## Question

I'm trying to debug a node lambda through AWS Toolkit.

I've used sam init to generate the default hello-world typescript project.

I've gone to the lambdaHandler and selected AWS: Add Debug Configuration.

I then have run the debugger using the generated launch config. 

I then get the error reported in the screen shots and my break point is never hit.

Any idea what I am doing wrong / missed?

Thanks

```
Debugger attached.
2023-09-14T23:02:07.592Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)","    at async Object.load (file:///var/runtime/index.mjs:1093:21)","    at async start (file:///var/runtime/index.mjs:1256:23)","    at async file:///var/runtime/index.mjs:1262:1"]}
Waiting for the debugger to disconnect...
14 Sep 2023 23:02:07,657 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
Debugger listening on ws://0.0.0.0:5858/461ef53a-cace-487d-834f-eafc5243466f
For help, see: https://nodejs.org/en/docs/inspector
```

![image](https://github.com/aws/aws-toolkit-vscode/assets/56564334/bb06b927-ddd0-424e-8f81-f566fb927ab8)

![image](https://github.com/aws/aws-toolkit-vscode/assets/56564334/79c03d7d-e899-4fcd-8174-a23e15c5be8e)

**Comment by DavidCabaniuk** [comment]
Sure can logs attached
[aws_toolkit_20230915T152357.log](https://github.com/aws/aws-toolkit-vscode/files/12620487/aws_toolkit_20230915T152357.log)

**Comment by bryceitoc9** [comment]
Just curious, does generating a debug handler from your `template.yaml` file work (use the codelens over the resource in the `template.yaml` file)? I'll look into the code-target handlers, but I'm having luck running a template-target one.

**Comment by maximedemarey-wb** [comment]
When I generate the debug launch config from template.yml, execution of the lambda is ok (but doesn't hit breakpoints)

```{
    "configurations": [
        {
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "test-debug:HelloWorldFunction",
            "invokeTarget": {
                "target": "template",
                "templatePath": "${workspaceFolder}/template.yaml",
                "logicalId": "HelloWorldFunction"
            },
            "lambda": {
                "payload": {},
                "environmentVariables": {}
            }
        },
        {
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "nodejs:app.lambdaHandler (nodejs18.x)",
            "invokeTarget": {
                "target": "code",
                "projectRoot": "${workspaceFolder}/hello-world",
                "lambdaHandler": "app.lambdaHandler"
            },
            "lambda": {
                "runtime": "nodejs18.x",
                "payload": {},
                "environmentVariables": {}
            }
        }
    ]
}```

**Comment by justinmk3** [comment]
> execution of the lambda is ok (but doesn't hit breakpoints)

Is `inlineSourceMap: true` specified in your `tsconfig.json` ?

**Comment by bryceitoc9** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/3952 for the code-target launch configs. Historically, the Typescript code-target launch configs were a best-guess (since we have to generate and `tsc` everything ourselves), but this seems like it fixes the base cases at the very least?

**Comment by ApexisDev** [comment]
are there any news on this?
