### ISSUE TITLE
CI: "Insiders" tests failing: "publishDocument .. createDocument"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4013]
unit tests are failing in "Insiders" CI since Nov 6:

```
  1) publishDocument
       createDocument
         createDocument API returns successfully:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(client.createDocument.calledWith(fakeCreateRequest))

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (src/test/ssmDocument/commands/publishDocument.test.ts:84:19)

  2) publishDocument
       updateDocument
         updateDocument API returns successfully:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(client.updateDocument.calledWith(fakeUpdateRequest))

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (src/test/ssmDocument/commands/publishDocument.test.ts:107:19)

deleteTestTempDirs: deleted 231 test temp dirs
```

**Comment by justinmk3** [comment]
This may not be entirely fixed, only less frequent. Seen again on https://github.com/aws/aws-toolkit-vscode/pull/3994 : 

```
  1) publishDocument
       createDocument
         createDocument API returns successfully:
      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  (0, assert_1.default)(client.createDocument.calledWith(fakeCreateRequest))
      + expected - actual
      -false
      +true
      
      at Context.<anonymous> (src/test/ssmDocument/commands/publishDocument.test.ts:84:19)
  2) publishDocument
       updateDocument
         updateDocument API returns successfully:
      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  (0, assert_1.default)(client.updateDocument.calledWith(fakeUpdateRequest))
      + expected - actual
      -false
      +true
      
      at Context.<anonymous> (src/test/ssmDocument/commands/publishDocument.test.ts:107:19)
```
