### ISSUE TITLE
unreliable test: codecatalyst/devEnv.test.ts: InactivityMessages

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4061]
```
2023-11-17 19:15:03 [DEBUG]: Sending update message to webview.
--
7915 | ✔ doesnt update the graph if a seperate file is opened or modified (210ms)
7916 | 92 passing (16m)
7917 | 20 pending
7918 | 1 failing
7919 | 1) InactivityMessages
7920 | shows expected messages 5 minutes before shutdown on a 15 minute inactivity timeout:
7921 |  
7922 | AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
7923 |  
7924 | 13 !== 14
7925 |  
7926 | + expected - actual
7927 |  
7928 | -13
7929 | +14
7930 |  
7931 | at assertMessagesShown (src/testInteg/codecatalyst/devEnv.test.ts:197:20)
7932 | at async Context.<anonymous> (src/testInteg/codecatalyst/devEnv.test.ts:62:9)
7933 |  
7934 | globalSetup: after()
7935 | Error: 1 tests failed.
7936 | at /codebuild/output/src3692660305/src/src/test/testRunner.ts:90:28
7937 | at MultiReporters.done (/codebuild/output/src3692660305/src/node_modules/mocha-multi-reporters/lib/MultiReporters.js:124:16)
7938 | at done (/codebuild/output/src3692660305/src/node_modules/mocha/lib/mocha.js:1007:16)
7939 | at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by justinmk3** [comment]
changed from a sleep() to waitUntil() https://github.com/aws/aws-toolkit-vscode/blob/e83b31cda2039df07954c77f162f033d42c453d4/packages/core/src/testInteg/codecatalyst/devEnv.test.ts#L175

**Comment by justinmk3** [comment]
skipped: https://github.com/aws/aws-toolkit-vscode/commit/3ce0dec2cbfea11610b48bd08e170e5d4935b3ad
