### ISSUE TITLE
tests: python "codelens" integ test failing

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4169]
Integ tests have been consistently failing since https://github.com/aws/aws-toolkit-vscode/pull/4151 (could be unrelated to that PR, coincidental with an upstream vscode/extension change).

```

  4 failing
  1) SAM Integration Tests
       SAM runtime: python 3.10 (ZIP)
         Starting with a newly created python 3.10 (ZIP) SAM Application...
           produces an Add Debug Configuration codelens:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(codeLenses && codeLenses.length === 2)

      at Context.<anonymous> (src/testInteg/sam.test.ts:516:28)

  2) SAM Integration Tests
       SAM runtime: python 3.11 (ZIP)
         Starting with a newly created python 3.11 (ZIP) SAM Application...
           produces an Add Debug Configuration codelens:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(codeLenses && codeLenses.length === 2)

      at Context.<anonymous> (src/testInteg/sam.test.ts:516:28)

  3) SAM Integration Tests
       SAM runtime: python 3.10 (ZIP)
         Starting with a newly created python 3.10 (ZIP) SAM Application...
           produces an Add Debug Configuration codelens:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(codeLenses && codeLenses.length === 2)

      at Context.<anonymous> (src/testInteg/sam.test.ts:516:28)

  4) SAM Integration Tests
       SAM runtime: python 3.11 (ZIP)
         Starting with a newly created python 3.11 (ZIP) SAM Application...
           produces an Add Debug Configuration codelens:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(codeLenses && codeLenses.length === 2)

      at Context.<anonymous> (src/testInteg/sam.test.ts:516:28)
```

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/4170
