### ISSUE TITLE
codewhisperer: Too many pending tasks in queue CODEWHISPERER_INLINE_UPDATE_LOCK_KEY

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4196]
## Problem

Seen in CI test logs:

```
rejected promise not handled within 1 second: Error: Too many pending tasks in queue CODEWHISPERER_INLINE_UPDATE_LOCK_KEY
stack trace: Error: Too many pending tasks in queue CODEWHISPERER_INLINE_UPDATE_LOCK_KEY
    at AsyncLock.acquire (/codebuild/output/src1005977027/src/github.com/aws/aws-toolkit-vscode/node_modules/async-lock/lib/index.js:195:15)
    at RecommendationHandler.showRecommendation (/codebuild/output/src1005977027/src/github.com/aws/aws-toolkit-vscode/src/codewhisperer/service/recommendationHandler.ts:600:20)
    at RecommendationHandler.fn [as tryShowRecommendation] (/codebuild/output/src1005977027/src/github.com/aws/aws-toolkit-vscode/src/codewhisperer/service/recommendationHandler.ts:681:24)
    at InlineCompletionService.sharedTryShowRecommendation (/codebuild/output/src1005977027/src/github.com/aws/aws-toolkit-vscode/src/shared/utilities/functionUtils.ts:33:32)
    at Timeout.<anonymous> (/codebuild/output/src1005977027/src/github.com/aws/aws-toolkit-vscode/src/codewhisperer/service/inlineCompletionService.ts:69:22)
```

## Expected behavior

Is `AsyncLock.acquire` the right thing to use, or should we debounce / drop recommendation requests?

**Comment by justinmk3** [comment]
This test failure is near the first occurrence, is it related?

```
rejected promise not handled within 1 second: AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

true !== false

stack trace: AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

true !== false

    at testShouldInvoke (/codebuild/output/src3898943566/src/github.com/aws/aws-toolkit-vscode/src/test/codewhisperer/service/keyStrokeHandler.test.ts:156:20)
    at async /codebuild/output/src3898943566/src/github.com/aws/aws-toolkit-vscode/src/test/codewhisperer/service/keyStrokeHandler.test.ts:138:17
```

**Comment by leigaol** [comment]
Is this still happening recently?

**Comment by justinmk3** [comment]
Has not occurred since https://github.com/aws/aws-toolkit-vscode/pull/4322

Thank you @leigaol !
