### ISSUE TITLE
codewhisperer securityIssueProvider: "TypeError: Cannot read properties of undefined (reading 'range')"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4203]
CI test logs are showing many of these unhandled rejections:

```
rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'range')
stack trace: TypeError: Cannot read properties of undefined (reading 'range')
    at SecurityIssueHoverProvider.handleDocumentChange (/codebuild/output/src3775465363/src/github.com/aws/aws-toolkit-vscode/src/codewhisperer/service/securityIssueProvider.ts:20:54)
    at f.value (/codebuild/output/src3775465363/src/github.com/aws/aws-toolkit-vscode/src/codewhisperer/activation.ts:331:53)
```

In the future, these will fail CI, but currently this particular error is ignored because it's a known issue. https://github.com/aws/aws-toolkit-vscode/blob/7c4e848235ed11d1ec18ac54dfd4a92ac193cbe7/buildspec/linuxTests.yml#L41-L42

Half-baked patch:

```diff
diff --cc src/codewhisperer/service/securityIssueProvider.ts
index 504e07092cad,504e07092cad..0ff03895b4bb
--- a/src/codewhisperer/service/securityIssueProvider.ts
+++ b/src/codewhisperer/service/securityIssueProvider.ts
@@@ -5,6 -5,6 +5,7 @@@
  
  import * as vscode from 'vscode'
  import { AggregatedCodeScanIssue } from '../models/model'
++import { ToolkitError } from '../../shared/errors'
  
  export abstract class SecurityIssueProvider {
      private _issues: AggregatedCodeScanIssue[] = []
@@@ -17,6 -17,6 +18,9 @@@
      }
  
      public handleDocumentChange(event: vscode.TextDocumentChangeEvent) {
++        if (!event.contentChanges || event.contentChanges.length === 0) {
++            throw new ToolkitError(`invalid event.contentChanges: ${JSON.stringify(event.contentChanges)}`)
++        }
          const changedRange = event.contentChanges[0].range
          const changedText = event.contentChanges[0].text
          const lineOffset = this._getLineOffset(changedRange, changedText)
```

**Comment by justinmk3** [comment]
# Steps to reproduce

1. open `src/test/codewhisperer/service/telemetry.test.ts` in vscode
2. run the `Extension Tests (current file)` launch config
    - <img width="534" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/c0922225-001d-4108-acaf-e36ab8ec6764">
 

<img width="953" alt="image" src="https://github.com/aws/aws-toolkit-vscode/assets/55561878/30d6ba7e-54dd-4057-bc56-47f7891273f3">
