### ISSUE TITLE
unreliable test: codewhisperer "onInlineAcceptance"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4238]
flaky test sometimes fails:

```
  1) onInlineAcceptance
       onInlineAcceptance
         Should report telemetry that records this user decision event:

      AssertionError [ERR_ASSERTION]: telemetry item 1 (of 1) not found (in the expected order) for metric name: "codewhisperer_userDecision" 
      + expected - actual

         "codewhispererRequestId": "test"
         "codewhispererSessionId": "test"
         "codewhispererSuggestionIndex": "0"
         "codewhispererSuggestionReferenceCount": "0"
      -  "codewhispererSuggestionState": "Reject"
      +  "codewhispererSuggestionState": "Accept"
         "codewhispererTriggerType": "OnDemand"
         "codewhispererUserGroup": "Classifier"
         "credentialStartUrl": "testStartUrl"
       }
      
      at partialDeepCompare (src/test/testUtil.ts:196:12)
      at assertTelemetry (src/test/testUtil.ts:237:9)
      at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/src/test/testUtil.ts:253:9
      at Context.<anonymous> (src/test/codewhisperer/commands/onInlineAcceptance.test.ts:90:13)
```

**Comment by justinmk3** [comment]
also happens with onAcceptance :

```
  1) onAcceptance
       onAcceptance
         Should report telemetry that records this user decision event:

      AssertionError [ERR_ASSERTION]: telemetry item 1 (of 1) not found (in the expected order) for metric name: "codewhisperer_userDecision" 
      + expected - actual

         "codewhispererRequestId": "test"
         "codewhispererSessionId": "test"
         "codewhispererSuggestionIndex": "0"
         "codewhispererSuggestionReferenceCount": "0"
      -  "codewhispererSuggestionState": "Reject"
      +  "codewhispererSuggestionState": "Accept"
         "codewhispererTriggerType": "OnDemand"
         "codewhispererUserGroup": "Control"
         "credentialStartUrl": "testStartUrl"
       }
      
      at partialDeepCompare (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\testUtil.ts:196:12)
      at assertTelemetry (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\testUtil.ts:237:9)
      at d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\testUtil.ts:253:9
      at Context.<anonymous> (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\src\test\codewhisperer\commands\onAcceptance.test.ts:112:13)
```

**Comment by Will-ShaoHua** [comment]
ack

**Comment by justinmk3** [comment]
still happening @Will-ShaoHua . example from https://github.com/aws/aws-toolkit-vscode/commit/042c00e785dd53f75cd687576d99571a0a798c0c

```
  1 failing
  1) onAcceptance
       onAcceptance
         Should report telemetry that records this user decision event:

      AssertionError [ERR_ASSERTION]: telemetry item 1 (of 1) not found (in the expected order) for metric name: "codewhisperer_userDecision" 
      + expected - actual

         "codewhispererRequestId": "test"
         "codewhispererSessionId": "test"
         "codewhispererSuggestionIndex": "0"
         "codewhispererSuggestionReferenceCount": "0"
      -  "codewhispererSuggestionState": "Reject"
      +  "codewhispererSuggestionState": "Accept"
         "codewhispererTriggerType": "OnDemand"
         "codewhispererUserGroup": "Control"
         "credentialStartUrl": "testStartUrl"
       }
      
      at partialDeepCompare (src/test/testUtil.ts:196:12)
      at assertTelemetry (src/test/testUtil.ts:237:9)
      at /codebuild/output/src171806546/src/github.com/aws/aws-toolkit-vscode/src/test/testUtil.ts:253:9
      at Context.<anonymous> (src/test/codewhisperer/commands/onAcceptance.test.ts:116:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Will-ShaoHua** [comment]
noted, I will look into it

**Comment by Hweinstock** [comment]
Unable to find recent failures, so closing for now. Please reopen if failures continue.
