### ISSUE TITLE
unreliable test: rejected promise reading AWSTemplateFormatVersion

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4462]
since https://github.com/aws/aws-toolkit-vscode/pull/4436 @JLargent42 

```
rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'AWSTemplateFormatVersion')
stack trace: TypeError: Cannot read properties of undefined (reading 'AWSTemplateFormatVersion')
    at Object.tryLoad (/codebuild/output/src919682432/src/github.com/aws/aws-toolkit-vscode/packages/toolkit/src/shared/cloudformation/cloudformation.ts:442:21)
    at async /codebuild/output/src919682432/src/github.com/aws/aws-toolkit-vscode/packages/toolkit/src/shared/awsFiletypes.ts:71:19
```

**Comment by justinmk3** [comment]
@JLargent42 actually I'm looking into this

**Comment by JLargent42** [comment]
This appears to be specific to opening empty JSON files. I have a fix here: https://github.com/aws/aws-toolkit-vscode/pull/4464
