### ISSUE TITLE
unreliable test: getWorkspaceFoldersByPrefixes

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4525]
3 failing tests consistently failing on Windows CI, since the `feature/featureDev-codegen` branch was merged: https://github.com/aws/aws-toolkit-vscode/commit/b6b9038fbaabe6887bd467e3ba615dff229a70fb

```
      + expected - actual

       {
      -  "_C__Users_RUNNER~1_AppData_Local_Temp_aws-toolkit-vscode_vsctke59d5806_test_app_cdk_cdk": {
      +  "canary_app_cdk_cdk": {
           "index": 0
           "name": "cdk"
           "uri": {
             "_formatted": [null]
      -      "_fsPath": "c:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\aws-toolkit-vscode\\vsctke59d5806\\test\\app\\cdk"
      +      "_fsPath": "c:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\aws-toolkit-vscode\\vsctkef8b0405\\canary\\app\\cdk"
             "authority": ""
             "fragment": ""
      -      "path": "/C:/Users/RUNNER~1/AppData/Local/Temp/aws-toolkit-vscode/vsctke59d5806/test/app/cdk"
      +      "path": "/C:/Users/RUNNER~1/AppData/Local/Temp/aws-toolkit-vscode/vsctkef8b0405/canary/app/cdk"
             "query": ""
             "scheme": "file"
           }
         }
      -  "_C__Users_RUNNER~1_AppData_Local_Temp_aws-toolkit-vscode_vsctkef8b0405_canary_app_cdk_cdk": {
      +  "test_app_cdk_cdk": {
           "index": 0
           "name": "cdk"
           "uri": {
             "_formatted": [null]
      -      "_fsPath": "c:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\aws-toolkit-vscode\\vsctkef8b0405\\canary\\app\\cdk"
      +      "_fsPath": "c:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\aws-toolkit-vscode\\vsctke59d5806\\test\\app\\cdk"
             "authority": ""
             "fragment": ""
      -      "path": "/C:/Users/RUNNER~1/AppData/Local/Temp/aws-toolkit-vscode/vsctkef8b0405/canary/app/cdk"
      +      "path": "/C:/Users/RUNNER~1/AppData/Local/Temp/aws-toolkit-vscode/vsctke59d5806/test/app/cdk"
             "query": ""
             "scheme": "file"
           }
         }
      
      at Context.<anonymous> (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\amazonqFeatureDev\util\files.test.ts:220:20)

  2) file utils
       getWorkspaceFoldersByPrefixes
         when a folder collides with another one in prefixing, it will get the shorter prefix if there are no contenders:
     Error: ENOENT: no such file or directory, mkdir 'C:\Users\RUNNER~1\AppData\Local\Temp\aws-toolkit-vscode\vsctk759a3292\c:\Users\RUNNER~1\AppData\Local\Temp\aws-toolkit-vscode\vsctkb0c5a76e\test\app\cdk'
  

  3) file utils
       getWorkspaceFoldersByPrefixes
         when 2 folders collide, they will get suffixed:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

86 !== 82

      + expected - actual

      -86
      +82
      
      at Context.<anonymous> (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\amazonqFeatureDev\util\files.test.ts:271:20)
```

**Comment by matboros** [comment]
For #2, we need to skip the `:` from the path when [specifying it as subdir](https://github.com/aws/aws-toolkit-vscode/blob/master/packages/core/src/test/amazonqFeatureDev/util/files.test.ts#L232), though that `:` might actually impact the functionality too.... maybe we should replace it with `_`?

**Comment by matboros** [comment]
For #1, there are 2 issues, one with the name, and the other with the order, but I didnt look into them in detail

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/4531
