### ISSUE TITLE
unreliable tests: "command 'aws.amazonq.refreshStatusBar' not found"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#4806]
CI sometimes fails:

```
  1) onInlineAcceptance
       onInlineAcceptance
         "before each" hook for "Should dispose inline completion provider":
     Error: command 'aws.amazonq.refreshStatusBar' not found
      at S.n (vscode-file://vscode-app/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/.vscode-test/vscode-darwin-1.88.1/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:23049)
      at S.executeCommand (vscode-file://vscode-app/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/.vscode-test/vscode-darwin-1.88.1/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:22978)

  2) onAcceptance
       onAcceptance
         "before each" hook for "Should enqueue an event object to tracker":
     Error: command 'aws.amazonq.refreshStatusBar' not found
      at S.n (vscode-file://vscode-app/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/.vscode-test/vscode-darwin-1.88.1/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:23049)
      at S.executeCommand (vscode-file://vscode-app/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/.vscode-test/vscode-darwin-1.88.1/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:22978)

  3) invokeRecommendation
       invokeRecommendation
         "before each" hook for "Should call getPaginatedRecommendation with OnDemand as trigger type when inline completion is enabled":
     Error: command 'aws.amazonq.refreshStatusBar' not found
      at S.n (vscode-file://vscode-app/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/.vscode-test/vscode-darwin-1.88.1/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:23049)
      at S.executeCommand (vscode-file://vscode-app/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/.vscode-test/vscode-darwin-1.88.1/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:22978)
```

**Comment by justinmk3** [comment]
Not seen for several months.
