### ISSUE TITLE
Run Locally Error: ValueError: Path resolution for runtime: nodejs8.10 of binary: npm was not successful

### ISSUE THREAD

**Issue by matwerber1** [aws/aws-toolkit-vscode#504]
**Describe the bug**
When clicking "Run Locally" for a NodeJS 8.10 function inside VS Code, I receive the following error: 
`ValueError: Path resolution for runtime: nodejs8.10 of binary: npm was not successful`

**To Reproduce**
1. From terminal, `sam init`
2. Within SAM project directory in VS Code, open **hello-world/app.js**
3. Click the **Run Locally** button above exports.lambdaHandler

**Expected behavior**
Expect function to run locally without error. 

**Screenshots**
`Preparing to run app.lambdaHandler locally...
Building SAM Application...
Error: sam build encountered an error: 2019-04-23 18:01:20 Building resource 'awsToolkitSamLocalResource'
,Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.15.0', 'console_scripts', 'sam')()
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 100, in cli
    skip_pull_image, parameter_overrides, mode)  # pragma: no cover
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 141, in do_cli
    artifacts = builder.build()
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 108, in build
    lambda_function.runtime)
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 199, in _build_function
    runtime)
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 220, in _build_function_in_process
    mode=self._mode)
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/builder.py", line 115, in build
    return workflow.run()
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 48, in wrapper
    exec_paths = binary_path.resolver.exec_paths if not binary_path.path_provided else binary_path.binary_path
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/path_resolver.py", line 29, in exec_paths
    return self._which()
  File "/usr/local/Cellar/aws-sam-cli/0.15.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/path_resolver.py", line 24, in _which
    "{} was not successful".format(self.runtime, self.binary))
ValueError: Path resolution for runtime: nodejs8.10 of binary: npm was not successful
`

**Desktop:**
VS Code version 1.33.1
2. Node version 8.10.0
3. SAM CLI version 0.15.0
4. AWS Toolkit for VS Code v0.1.1
5. Mac Sierra 10.12.6

**Additional context**
It's worth noting that if I open a terminal, navigate to project directory, and run the command below, the local test works as expected:
`sam local invoke "HelloWorldFunction" -e event.json `

**Comment by awschristou** [comment]
Hi @matwerber1 , do you typically open VS Code from the Application Tray? If so, can you please try launching VS Code from the same terminal that you have success running `sam local invoke` from? I'd like to know if it that succeeds.

Would you also be able to provide:
* the location of your npm executable (`which npm`)
* your `SHELL` environment variable (`echo $SHELL`)

**Comment by bryceitoc9** [comment]
@matwerber1 , could you also try a `sam build` in the terminal? If you're in the directory with your template file, you should be able to use `sam build --build-dir . --template ./template.yaml` (fill in values as appropriate).

**Comment by keephopealive** [comment]
I'm having the same issue, I haven't been able to find a fix yet.
I'm using the mac OS terminal.
aws cli is successfully installed and tested.
sam cli is successfully installed and tested _(except for 'sam build' failing)_.
Create a sample application with: "sam init --runtime nodejs6.10"
I'm able to run: "sam local start-api"
**Unable to run: "sam build"**

Throws the same error as the OP.

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.19.0', 'console_scripts', 'sam')()
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 94, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 65, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 105, in cli
    skip_pull_image, parameter_overrides, mode)  # pragma: no cover
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 150, in do_cli
    artifacts = builder.build()
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 108, in build
    lambda_function.runtime)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 199, in _build_function
    runtime)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 220, in _build_function_in_process
    mode=self._mode)
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/builder.py", line 115, in build
    return workflow.run()
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 48, in wrapper
    exec_paths = binary_path.resolver.exec_paths if not binary_path.path_provided else binary_path.binary_path
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/path_resolver.py", line 29, in exec_paths
    return self._which()
  File "/usr/local/Cellar/aws-sam-cli/0.19.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/path_resolver.py", line 24, in _which
    "{} was not successful".format(self.runtime, self.binary))
**ValueError: Path resolution for runtime: nodejs6.10 of binary: npm was not successful**

**Comment by wukimmy** [comment]
I'm having the same problem, but I'm using nvm to control my node versions

**Comment by bryceitoc9** [comment]
Hi @wukimmy,

Just making sure, do the individual `build` and `invoke` steps that @awschristou and I suggested work if running through a terminal? If so, can you try opening VS Code through said terminal and running again?

**Comment by hanezu** [comment]
> try launching VS Code from the same terminal that you have success running sam local invoke from

Works like charm.

**Comment by ashish-fission** [comment]
Getting the same error. Tried opening the terminal from the same terminal. No luck!

**Comment by justinmk3** [comment]
If this is still an issue in the latest Toolkit please open a new issue. Thanks!
