### ISSUE TITLE
unreliable test: Auth promptForConnection

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#5115]
```
  1) Auth
       promptForConnection
         reauthenticates a connection if the user selects an expired one:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(!refreshedConnItem.description?.match(/expired/i))

      + expected - actual

      -false
      +true
      
      at /codebuild/output/src3389505232/src/github.com/aws/aws-toolkit-vscode/packages/core/src/test/credentials/auth.test.ts:512:24
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /codebuild/output/src3389505232/src/github.com/aws/aws-toolkit-vscode/packages/core/src/test/shared/vscode/window.ts:496:29
```

**Comment by justinmk3** [comment]
resolved by https://github.com/aws/aws-toolkit-vscode/pull/5228
