### ISSUE TITLE
unreliable test: "Amazon Q Login" `login/webview/vue/backend.test.ts:61:23`

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#5207]
```
  Amazon Q Login
    ✔ emits ui_click telemetry
    ✔ runs setup and emits success and recorded metrics
Error: error
    at setupFunc (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/packages/core/src/test/login/webview/vue/backend.test.ts:57:19)
    at runSetup (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/packages/core/src/login/webview/vue/backend.ts:74:23)
    at AmazonQLoginWebview.ssoSetup (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/packages/core/src/login/webview/vue/backend.ts:128:30)
    at Context.<anonymous> (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/packages/core/src/test/login/webview/vue/backend.test.ts:61:23)
    at Context.fn (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/packages/core/src/test/setupUtil.ts:33:24)
    at callFn (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:666:10)
    at /codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:789:12
    at next (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:581:14)
    at /codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:591:7
    at next (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:474:14)
    at cbHookRun (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:539:7)
    at done (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runnable.js:354:5)
    at next (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:498:10)
    at Immediate.<anonymous> (/codebuild/output/src2874790906/src/github.com/aws/aws-toolkit-vscode/node_modules/mocha/lib/runner.js:559:5)
    at processImmediate (node:internal/timers:478:21)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    ✔ runs setup and emits failed and recorded metrics
Error: Timeout token cancelled
```

**Comment by justinmk3** [comment]
No recent occurrences.
