### ISSUE TITLE
unreliable test: beforeEach..closeAllEditors failure in Amazon Q tests

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#5325]
In CI, the Amazon Q tests sometimes fail : 

```
  1) "before each" hook: beforeEach for "simple case 1":
     Error: Editors were still open after closeAllEditors():

      at Object.closeAllEditors (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\testUtil.ts:401:15)
      at runNextTicks (node:internal/process/task_queues:60:5)
      at processTimers (node:internal/timers:511:9)
      at async Context.beforeEach (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\globalSetup.test.ts:91:9)
```

These test results are near the top of the build logs. So although the final (core/) results report success, you need to scroll up to the amazonq/ tests.

Example: https://github.com/aws/aws-toolkit-vscode/actions/runs/9959760755/job/27517343024?pr=5309

**Comment by justinmk3** [comment]
still occurs, though the line numbers have changed

```
  1) "before each" hook: beforeEach for "should not remove extra closing symbol":
     Error: Editors were still open after closeAllEditors():

      at Object.closeAllEditors (/codebuild/output/src1772754914/src/github.com/aws/aws-toolkit-vscode/packages/core/src/test/testUtil.ts:510:15)
```

**Comment by Hweinstock** [comment]
Should be fixed by: https://github.com/aws/aws-toolkit-vscode/pull/5975
