### ISSUE TITLE
unreliable test: startSecurityScanPerformanceTest

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#5479]
https://github.com/aws/aws-toolkit-vscode/actions/runs/10498763649/job/29084326983?pr=5458

```
  1) startSecurityScanPerformanceTest
       Should calculate cpu and memory usage for file scans:

      AssertionError [ERR_ASSERTION]: Expected total CPU usage for Should calculate cpu and memory usage for file scans to be less than 50. Actual CPU usage was 85.47574143312488
      + expected - actual

      -false
      +true
      
      at assertPerformanceMetrics (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\shared\performance\performance.ts:100:11)
      at Context.<anonymous> (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\shared\performance\performance.ts:88:9)
```

**Comment by Hweinstock** [comment]
Fixed by https://github.com/aws/aws-toolkit-vscode/pull/5786
