### ISSUE TITLE
unreliable test: "TelemetrySpan records performance"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#5483]
https://d1ihu6zq92vp9p.cloudfront.net/02f32da6-0de7-44d3-9252-ee19fe4d341d/report.html

```
  1) TelemetrySpan
       records performance:
     Uncaught TypeError: Cannot read properties of undefined (reading '0')
      at Object.now (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/realclock/nodeClock.js:5:18)
      at Request.API_CALL (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/service.js:451:51)
      at Request.callListeners (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/request.js:686:14)
      at Request.transition (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/request.js:688:12)
      at Request.callListeners (/codebuild/output/src2640122628/src/github.com/aws/aws-toolkit-vscode/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**Comment by jpinkney-aws** [comment]
I think this should be fixed by https://github.com/aws/aws-toolkit-vscode/pull/5503. I'm going to wait a couple days and check the test runs before closing
