### ISSUE TITLE
failing test: target=code: typescript

### ISSUE THREAD

**Issue by jpinkney-aws** [aws/aws-toolkit-vscode#5587]
## Problem
The following test is failing in CI (and probably locally as well):

```
 SamDebugConfigurationProvider
       makeConfig
         target=code: typescript:
     Error: TypeScript compiler "tsc" not found in node_modules/ or the system.
      at compileTypeScript (src/shared/sam/debugger/typescriptSamDebug.ts:214:15)
      at async Object.makeTypescriptConfig (src/shared/sam/debugger/typescriptSamDebug.ts:77:5)
      at async SamDebugConfigProvider.makeConfig (src/shared/sam/debugger/awsSamDebugger.ts:635:32)
      at async Context.<anonymous> (src/test/shared/sam/debugger/samDebugConfigProvider.test.ts:706:29)
```

According to PR's it looks like it started failing yesterday

**Comment by jpinkney-aws** [comment]
On recent PR's it looks like its recovered. I'm guessing there was a temporary outage with downloading typescript? Or something else weird going on?

If I don't see the problem again in a few days I'll close this

**Comment by jpinkney-aws** [comment]
Nvm looks like I got it in https://github.com/aws/aws-toolkit-vscode/actions/runs/10854578001/job/30125976412
