### ISSUE TITLE
unreliable test: ec2/sshKeyPair.ts (Windows)

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#5658]
example failure: https://github.com/aws/aws-toolkit-vscode/actions/runs/10966951258/job/30455856559?pr=5590

Unhandled promise rejection on Windows CI. This tends to happen on Windows because it does not allow files/dirs to be deleted if they are still open in any process. 

```
rejected promise not handled within 1 second: Unknown (FileSystemError) (FileSystemError): Error: ENOTEMPTY: directory not empty, rmdir 'D:\'
stack trace: Unknown (FileSystemError) (FileSystemError): Error: ENOTEMPTY: directory not empty, rmdir 'D:\'
    at Function.e (file:///d:/a/aws-toolkit-vscode/aws-toolkit-vscode/.vscode-test/vscode-win32-x64-archive-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:9333)
    at Object.delete (file:///d:/a/aws-toolkit-vscode/aws-toolkit-vscode/.vscode-test/vscode-win32-x64-archive-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:8155)
    at async SshKeyPair.delete (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\awsService\ec2\sshKeyPair.ts:60:9)
    at async ph.value (d:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\awsService\ec2\sshKeyPair.ts:24:13)
```

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/pull/5661
