### ISSUE TITLE
unreliable test: Error: Timed-out waiting for browser login flow to complete

### ISSUE THREAD

**Issue by Hweinstock** [aws/aws-toolkit-vscode#6043]
unhandled promise rejection: 
``` 
rejected promise not handled within 1 second: Error: Timed-out waiting for browser login flow to complete
stack trace: Error: Timed-out waiting for browser login flow to complete
    at poll (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:368:15)
    at async openBrowserAndWaitUntilComplete (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:468:20)
    at async DeviceFlowAuthorization.authorize (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:482:33)
    at async DeviceFlowAuthorization.runFlow (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:142:28)
    at async DeviceFlowAuthorization.createToken (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:125:24)
Timed-out waiting for browser login flow to complete: Error: Timed-out waiting for browser login flow to complete
    at poll (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:368:15)
    at async openBrowserAndWaitUntilComplete (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:468:20)
    at async DeviceFlowAuthorization.authorize (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:482:33)
    at async DeviceFlowAuthorization.runFlow (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:142:28)
    at async DeviceFlowAuthorization.createToken (/codebuild/output/src312647086/src/github.com/aws/aws-toolkit-vscode/packages/core/src/auth/sso/ssoAccessTokenProvider.ts:125:24)
```
Example: https://d1ihu6zq92vp9p.cloudfront.net/f7645e40-59ef-4c69-9527-0c5b018f6087/report.html

**Comment by Hweinstock** [comment]
Fixed by https://github.com/aws/aws-toolkit-vscode/pull/6088
