### ISSUE TITLE
unreliable test: AppBuilder Walkthrough, Create project, download serverlessland proj:

### ISSUE THREAD

**Issue by Hweinstock** [aws/aws-toolkit-vscode#6078]
## Test Details

-   Name of test: AppBuilder Walkthrough, Create project, download serverlessland proj:
-   OS of failure: Mac OS
-   VSCode version of failure (minimum/insider/stable): insiders
-   Link to failing run: https://github.com/aws/aws-toolkit-vscode/actions/runs/11938979186/job/33278472677
-   Link to failing test: https://github.com/aws/aws-toolkit-vscode/blob/284455442b130e9b81b3def5c7a80d45668c802b/packages/core/src/test/awsService/appBuilder/walkthrough.test.ts#L210-L221

## Log of Test Failure
``` 
AppBuilder Walkthrough
       Create project
         download serverlessland proj:
     Error: Could not find the specified item "Yes" on message: severity: Warning, message: undefined, items: OK
      at TestMessage.selectItem (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/test/shared/vscode/message.ts:187:19)
      at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/test/awsService/appBuilder/walkthrough.test.ts:214:25
      at xh.value (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/test/shared/vscode/window.ts:501:35)
      at Proxy.B (file:///private/tmp/.vscode-test/vscode-darwin-arm64-insiders/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
      at Proxy.fire (file:///private/tmp/.vscode-test/vscode-darwin-arm64-insiders/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
      at fireOnDidShowMessage (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/test/shared/vscode/window.ts:147:35)
      at /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/test/shared/vscode/message.ts:247:27
      at new Promise (<anonymous>)
      at Proxy.<anonymous> (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/test/shared/vscode/message.ts:244:20)
      at errorPromptHelper (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/commands/startSecurityScan.ts:305:28)
      at startSecurityScan (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/commands/startSecurityScan.ts:232:13)
      at async /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/commands/startSecurityScan.ts:75:13
```

**Comment by roger-zhangg** [comment]
This case is weird, This test has a write file in before Each here

https://github.com/aws/aws-toolkit-vscode/blob/284455442b130e9b81b3def5c7a80d45668c802b/packages/core/src/test/awsService/appBuilder/walkthrough.test.ts#L166-L168

Then the test it self do a `await fs.exists(templateUri)`
https://github.com/aws/aws-toolkit-vscode/blob/2b6987a8f86e6f06c862f2a3415c420f6b646435/packages/core/src/awsService/appBuilder/walkthrough.ts#L181-L195
And Prompt for Yes/No if file is found. It seems like in the flaky scenario of this test. The file created in `beforeEach` is not detected in the following `fs.exists`. If this is the case, could you help to share some hint for how to make it more robust?

**Comment by justinmk3** [comment]
> And Prompt for Yes/No if file is found.

@roger-zhangg based on the test failure, it looks like the prompt isn't found:

> Error: Could not find the specified item "Yes" on message: severity: Warning, message: undefined, items: OK

That found a "warning" (not "info") message with only a OK button.

> how to make it more robust?

Just a guess, but try `waitUntil(... fs.exists(...))` in the before-each:

```ts
await fs.writeFile(vscode.Uri.joinPath(workspaceUri, 'template.yaml'), prevInfo)
waitUntil(...)
```

**Comment by roger-zhangg** [comment]
Thanks @justinmk3 for the headup, Had a detailed look into the log here. Was searching for where the Warning message with OK come from. It turns out that the only place that throws a warning with a OK is here in Codewisperer
https://github.com/aws/aws-toolkit-vscode/blob/0536f09cfe4ce1f0db14d36a810bb212966720c0/packages/core/src/codewhisperer/commands/startSecurityScan.ts#L301-L307

And this codewisperer behavior can be seen from the error log attached in this issue:
```
      at new Promise (<anonymous>)
      at Proxy.<anonymous> (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/test/shared/vscode/message.ts:244:20)
      at errorPromptHelper (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/commands/startSecurityScan.ts:305:28)
      at startSecurityScan (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/commands/startSecurityScan.ts:232:13)
      at async /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/commands/startSecurityScan.ts:75:13
```

Then looking into test execution, the test called `      ✔ setScansEnabled() works as expected` is executed right before this test. I wonder if this flaky case comes from the auto Scan being  enabled but not disabled after this test suite. Then the scan pops up a warning message before my Yes/No Prompter, causing this test to be flaky in this case.

Would like to have someone from CodeWhisperer team to take a look here as well. Thanks

**Comment by roger-zhangg** [comment]
added an assert to debug this case in 

https://github.com/aws/aws-toolkit-vscode/blob/0536f09cfe4ce1f0db14d36a810bb212966720c0/packages/core/src/test/codewhisperer/commands/basicCommands.test.ts#L653-L664
```
assert.strictEqual(CodeScansState.instance.isScansEnabled(), false)
```
output
```
  1) CodeWhisperer-basicCommands
       applySecurityFix
         handles apply edit failure:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

true !== false

      + expected - actual

      -true
      +false
```

So the scan is indeed still enabled after this test suite, I'll send a fix to disable the scan
