### ISSUE TITLE
unreliable test: crossFileContextUtil, for t1 group, should return repomap + opentabs context

### ISSUE THREAD

**Issue by Hweinstock** [aws/aws-toolkit-vscode#6079]
## Test Details

-   Name of test: crossFileContextUtil, fetchSupplementalContextForSrc, for t1 group, should return repomap + opentabs context:
-   OS of failure: Windows
-   VSCode version of failure (minimum/insider/stable): Insider
-   Link to failing run: https://github.com/aws/aws-toolkit-vscode/actions/runs/11938979186/job/33278472299
-   Link to failing test: https://github.com/aws/aws-toolkit-vscode/blob/284455442b130e9b81b3def5c7a80d45668c802b/packages/amazonq/test/unit/codewhisperer/util/crossFileContextUtil.test.ts#L64-L97

## Log of Test Failure
``` 
1) crossFileContextUtil
       fetchSupplementalContextForSrc
         for t1 group, should return repomap + opentabs context:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

0 !== 4

      + expected - actual

      -0
      +4
      
      at Context.<anonymous> (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\amazonq\test\unit\codewhisperer\util\crossFileContextUtil.test.ts:86:20)

deleteTestTempDirs: deleted 103 test temp dirs
Error: 1 tests failed.
    at D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\testRunner.ts:124:28
    at MultiReporters.done (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha-multi-reporters\lib\MultiReporters.js:124:16)
    at done (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha\lib\mocha.js:1007:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Extension host test runner error Error: 1 tests failed.
    at D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\testRunner.ts:124:28
Asking native host service to exit with code 1.
    at MultiReporters.done (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha-multi-reporters\lib\MultiReporters.js:124:16)
    at done (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha\lib\mocha.js:1007:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
## Additional Information
Observed 3+ times.

**Comment by Hweinstock** [comment]
Currently skipped in https://github.com/aws/aws-toolkit-vscode/pull/6085

**Comment by Hweinstock** [comment]
Addressed as part of https://github.com/aws/aws-toolkit-vscode/issues/6252
