### ISSUE TITLE
unreliable test: ToolkitLogger log tracking can find log from multiple files:

### ISSUE THREAD

**Issue by Hweinstock** [aws/aws-toolkit-vscode#6132]
## Test Details

-   Name of test: ToolkitLogger, log tracking, can find log from multiple files. 
-   OS of failure: Windows
-   VSCode version of failure (minimum/insider/stable): stable
-   Link to failing run: https://github.com/aws/aws-toolkit-vscode/actions/runs/12142141015/job/33855905517
-   Link to failing test: https://github.com/aws/aws-toolkit-vscode/blob/c4f965f96da553b3826641abd5cd69980f166633/packages/core/src/test/shared/logger/toolkitLogger.test.ts#L357-L380

## Log of Test Failure
``` 
 ToolkitLogger
       log tracking
         can find log from multiple files:
     Error: Expected message not found in log: error message 0
Expected message not found in log: error message 1
Expected message not found in log: error message 2
Expected message not found in log: error message 3
Expected message not found in log: error message 4
Expected message not found in log: error message 5
Expected message not found in log: error message 6
Expected message not found in log: error message 7
Expected message not found in log: error message 8
Expected message not found in log: error message 9


 Last 10 log lines:

      at D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\shared\logger\toolkitLogger.test.ts:52:17
      at runNextTicks (node:internal/process/task_queues:60:5)
      at listOnTimeout (node:internal/timers:545:9)
      at processTimers (node:internal/timers:519:7)

deleteTestTempDirs: deleted 334 test temp dirs
Error: 1 tests failed.
    at D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\testRunner.ts:124:28
    at MultiReporters.done (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha-multi-reporters\lib\MultiReporters.js:124:16)
    at done (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha\lib\mocha.js:1007:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Extension host test runner error Error: 1 tests failed.
    at D:\a\aws-toolkit-vscode\aws-toolkit-vscode\packages\core\src\test\testRunner.ts:124:28
    at MultiReporters.done (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha-multi-reporters\lib\MultiReporters.js:124:16)
    at done (D:\a\aws-toolkit-vscode\aws-toolkit-vscode\node_modules\mocha\lib\mocha.js:1007:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Hweinstock** [comment]
No recent occurrences, reopen with link to commit if occurs again.
