### ISSUE TITLE
unreliable test: generateZipTestGen

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#6160]
## Test Details

-   Name of test: generateZipTestGen
-   OS of failure: macOS
-   VSCode version of failure (minimum/insider/stable): minimum
-   Link to failing run: https://github.com/aws/aws-toolkit-vscode/actions/runs/12170063371/job/33944295842
-   Link to failing test: https://github.com/aws/aws-toolkit-vscode/blob/3a39b1033256743eedefbb6fc05c08e3f4ed602f/packages/amazonq/test/unit/codewhisperer/util/zipUtil.test.ts#L117

## Log of Test Failure

```
  1) zipUtil
       generateZipTestGen
         Should generate zip for test generation successfully:
     Error: done() called multiple times in test <zipUtil generateZipTestGen Should generate zip for test generation successfully> of file /Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/amazonq/dist/test/unit/codewhisperer/util/zipUtil.test.js; in addition, done() received error: EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, scandir '/test/zip/utgRequiredArtifactsDir'
    at Function.e (/private/tmp/.vscode-test/vscode-darwin-arm64-1.83.0/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:26740)
    at Object.readDirectory (/private/tmp/.vscode-test/vscode-darwin-arm64-1.83.0/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:24744)
    at async processDirectory (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/util/zipUtil.ts:190:29)
    at async ZipUtil.processMetadataDir (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/util/zipUtil.ts:212:9)
    at async ZipUtil.zipProject (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/util/zipUtil.ts:230:13)
    at async ZipUtil.generateZipTestGen (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/util/zipUtil.ts:602:41)
    at async Context.<anonymous> (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/amazonq/test/unit/codewhisperer/util/zipUtil.test.ts:159:28) {
  code: 'FileNotFound'
```

**Comment by Hweinstock** [comment]
Another failure: https://github.com/aws/aws-toolkit-vscode/actions/runs/12358099519/job/34487842964?pr=6249

**Comment by Hweinstock** [comment]
Reopening due to related failure:

## Test Details

-   Name of test: generateZipTestGen
-   OS of failure: Windows
-   VSCode version of failure (minimum/insider/stable): insider
-   Link to failing run: https://github.com/aws/aws-toolkit-vscode/actions/runs/12696996583/job/35392271325
-   Link to failing test: https://github.com/aws/aws-toolkit-vscode/blob/3a39b1033256743eedefbb6fc05c08e3f4ed602f/packages/amazonq/test/unit/codewhisperer/util/zipUtil.test.ts#L117

## Log of Test Failure

```
  1) zipUtil
       generateZipTestGen
         Should handle file copy to downloads folder error:

      AssertionError [ERR_ASSERTION]: mkdir should have been called 4 times

5 !== 4

      + expected - actual

      -5
      +4
```

**Comment by Hweinstock** [comment]
Test removed in https://github.com/aws/aws-toolkit-vscode/pull/6482
