### ISSUE TITLE
unreliable test: zipUtil-generateZip-Should generate zip for file scan and return expected metadata

### ISSUE THREAD

**Issue by Hweinstock** [aws/aws-toolkit-vscode#6203]
## Test Details

-   Name of test: Should generate zip for file scan and return expected metadata
-   OS of failure: macOS
-   VSCode version of failure (minimum/insider/stable): minimum
-   Link to failing run: https://github.com/aws/aws-toolkit-vscode/actions/runs/12260528617/job/34205370240
-   Link to failing test: https://github.com/aws/aws-toolkit-vscode/blob/b702dcdb2f486d393f6d3867506382a444d58220/packages/amazonq/test/unit/codewhisperer/util/zipUtil.test.ts#L44-L53

## Log of Test Failure
``` 
zipUtil
       generateZip
         Should generate zip for file scan and return expected metadata:
     Error: Payload size limit reached [FileSizeExceeded]
  
      at ZipUtil.zipFile (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/util/zipUtil.ts:137:19)
      at async ZipUtil.generateZip (/Users/runner/work/aws-toolkit-vscode/aws-toolkit-vscode/packages/core/src/codewhisperer/util/zipUtil.ts:544:31)
      at async Context.<anonymous> (test/unit/codewhisperer/util/zipUtil.test.ts:45:33)
``` 

## Additional Information
Potentially related to https://github.com/aws/aws-toolkit-vscode/issues/6160

**Comment by Hweinstock** [comment]
Potential fix in https://github.com/aws/aws-toolkit-vscode/pull/6290, please reopen if seen again.
