### ISSUE TITLE
unreliable test: shows warning 5 minutes before shutdown for 60 minute timeout

### ISSUE THREAD

**Issue by Hweinstock** [aws/aws-toolkit-vscode#6213]
## Test Details

-   Name of test: shows warning 5 minutes before shutdown for 60 minute timeout
-   OS of failure: Linux
-   VSCode version of failure (minimum/insider/stable): (1.95.3)
-   Link to failing run:
-   Link to failing test: https://github.com/aws/aws-toolkit-vscode/blob/2af8b45b8e2ba68bf81f7254ddb1bd27a3cbe887/packages/core/src/testInteg/codecatalyst/devEnv.test.ts#L72-L79

## Log of Test Failure
``` 
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  {
    message: 'Your CodeCatalyst Dev Environment has been inactive for 55 minutes, and will stop soon.',
+   minute: 54
-   minute: 55
  }
    at assertMessagesShown (/codebuild/output/src1534573611/src/github.com/aws/aws-toolkit-vscode/packages/core/src/testInteg/codecatalyst/devEnv.test.ts:144:20)
    at async Context.<anonymous> (/codebuild/output/src1534573611/src/github.com/aws/aws-toolkit-vscode/packages/core/src/testInteg/codecatalyst/devEnv.test.ts:76:9)

      + expected - actual

       {
         "message": "Your CodeCatalyst Dev Environment has been inactive for 55 minutes, and will stop soon."
      -  "minute": 54
      +  "minute": 55
       }
```
## Additional Information
Integ test

**Comment by justinmk3** [comment]
This test is definitely a known issue. If we can just retry it, we should. Or possibly skip() for now.

**Comment by Hweinstock** [comment]
Another failure on https://github.com/aws/aws-toolkit-vscode/commit/0d8c8fcb1c5b0540f0548f9b265f81ba9a23d4e9. Looks like 1 minute buffer period is no longer effective at mitigating flakiness.
