### ISSUE TITLE
unreliable test: "getFileSha384 performance tests"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#6225]
## Test Details

-   Name of test: `getFileSha384 performance tests`
-   OS of failure: linux
-   VSCode version of failure (minimum/insider/stable): insiders
-   Link to failing run: https://d1ihu6zq92vp9p.cloudfront.net/a00745e1-5c35-430a-8c73-db9b2756a462/report.html
-   Link to failing test:

## Log of Test Failure

```
  1) getFileSha384
       performance tests
         2MB performance tests
           "after all" hook for "2MB - test run 10":

      AssertionError [ERR_ASSERTION]: Expected total user CPU usage for 2MB to be less than 400. Actual user CPU usage was 462.1365886618588
      + expected - actual

      -false
      +true
      
      at assertPerformanceMetrics (/codebuild/output/src2928107957/src/github.com/aws/aws-toolkit-vscode/packages/core/src/shared/performance/performance.ts:182:11)
      at Context.<anonymous> (/codebuild/output/src2928107957/src/github.com/aws/aws-toolkit-vscode/packages/core/src/shared/performance/performance.ts:160:13)
      at Context.fn (/codebuild/output/src2928107957/src/github.com/aws/aws-toolkit-vscode/packages/core/src/test/setupUtil.ts:34:24)
      at processImmediate (node:internal/timers:483:21)
      at process.topLevelDomainCallback (node:domain:161:15)
      at process.callbackTrampoline (node:internal/async_hooks:128:24)
```

**Comment by Hweinstock** [comment]
Resolved by https://github.com/aws/aws-toolkit-vscode/pull/6249
