### ISSUE TITLE
unreliable test: "crossFileContextUtil full support should be non empty"

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#6252]
## Test Details

-   Name of test: `crossFileContextUtil full support should be non empty:`
-   OS of failure: macOS
-   VSCode version of failure (minimum/insider/stable): all
-   Link to failing run: (one of many:) https://github.com/aws/aws-toolkit-vscode/actions/runs/12323095533/job/34398051936
-   Link to failing test:

## Log of Test Failure

```
  1) crossFileContextUtil
       full support
         should be non empty:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(actual && actual.supplementalContextItems.length !== 0)

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/unit/codewhisperer/util/crossFileContextUtil.test.ts:342:24)
      at runNextTicks (node:internal/process/task_queues:60:5)
      at processTimers (node:internal/timers:516:9)

  2) crossFileContextUtil
       full support
         should be non empty:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(actual && actual.supplementalContextItems.length !== 0)

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/unit/codewhisperer/util/crossFileContextUtil.test.ts:342:24)
```

## Related

- https://github.com/aws/aws-toolkit-vscode/issues/6041
- https://github.com/aws/aws-toolkit-vscode/issues/6079

**Comment by justinmk3** [comment]
Also sometimes the `openTabsContext` case:

```
 1) supplementalContextUtil
       fetchSupplementalContext
         openTabsContext
           opentabContext should include chunks if non empty:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(actual?.supplementalContextItems.length === 3)

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/unit/codewhisperer/util/supplemetalContextUtil.test.ts:45:24)
      at runNextTicks (node:internal/process/task_queues:60:5)
      at processTimers (node:internal/timers:516:9)
```

**Comment by Will-ShaoHua** [comment]
temporarily skipped test case other than `java` and only run 1 language test case, still looking into test cases failure but have tested functionally and works fine on the languages skipped
