### ISSUE TITLE
Newbie: getting an Runtime.ImportModuleError using AWS: Create new SAM Application

### ISSUE THREAD

**Issue by smartserveteam** [aws/aws-toolkit-vscode#643]
**Describe the bug**
Using node 8 or node 10 and without changing anything on the generated application, I get a " Runtime.ImportModuleError"  when running locally in VSCode on Ubuntu.

**To Reproduce**
1. Use vscode "AWS: Create new SAM Application"
2. Select nodejs8.10 (same issue when I tried with nodejs10.x)
3. Select a workspace folder
4. Give the application a name
5. Open app.js and click on Run Locally

**Expected behavior**
Should run without errors

**Error message**
```
Build complete.
Starting the SAM Application locally (see Terminal for output)
Running command: sam local invoke awsToolkitSamLocalResource --template /tmp/aws-toolkit-vscode/vsctkjQEWyw/output/template.yaml --event /tmp/aws-toolkit-vscode/vsctkjQEWyw/event.json --env-vars /tmp/aws-toolkit-vscode/vsctkjQEWyw/env-vars.json
2019-06-25 22:15:45 Invoking app.lambdaHandler (nodejs8.10)
2019-06-25 22:15:45 Found credentials in shared credentials file: ~/.aws/credentials

Fetching lambci/lambda:nodejs8.10 Docker container image.............................................................................................................................................................................................................................................
2019-06-25 22:16:17 Mounting /tmp/aws-toolkit-vscode/vsctkjQEWyw/output/awsToolkitSamLocalResource as /var/task:ro,delegated inside runtime container
[32mSTART RequestId: 5afeb079-24d0-1d19-9f72-2e881226827c Version: $LATEST[0m
[31mUnable to import module 'app': Error[0m
[31m    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)[0m
[32mEND RequestId: 5afeb079-24d0-1d19-9f72-2e881226827c[0m
[32mREPORT RequestId: 5afeb079-24d0-1d19-9f72-2e881226827c	Duration: 4.37 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 31 MB	[0m

{"errorMessage":"Cannot find module '/var/task/app'","errorType":"Error","stackTrace":["Function.Module._load (module.js:474:25)","Module.require (module.js:596:17)","require (internal/module.js:11:18)"]}
Local invoke of SAM Application has ended.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Visual Studio Code Version: latest as of this post
 - AWS Toolkit for Visual Studio Code Version: just installed it so I guess it's the latest?

**Comment by smartserveteam** [comment]
Tried it on Mac and it works fine. Must be an issue on my ubuntu machine.

**Comment by bryceitoc9** [comment]
Hi @smartserveteam 

Out of curiosity, could you try restarting the Docker service on your Linux machine? This may be an issue with the directory not being mounted correctly in the Docker image.
