### ISSUE TITLE
SAM init error

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-vscode#658]
**To Reproduce**
1. SAM CLI path set to invalid location?
1. Command Palette > Create new SAM Application

**Additional context**
```
2019-07-02 14:24:42 [ERROR]: An error occurred while creating a new SAM Application. Check the logs for more information.
2019-07-02 14:24:42 [ERROR]: TypeError: Cannot read property 'on' of undefined
	at ChildProcess.<anonymous> (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:60:38)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:11:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:7:12)
	at ChildProcess.start (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:55:16)
	at ChildProcess.<anonymous> (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:34:28)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:11:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:7:12)
	at run.Promise (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:30:59)
	at new Promise (<anonymous>)
	at ChildProcess.<anonymous> (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:30:26)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:11:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:7:12)
	at ChildProcess.run (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/utilities/childProcess.js:29:16)
	at DefaultSamCliProcessInvoker.<anonymous> (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliInvoker.js:45:39)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliInvoker.js:11:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliInvoker.js:7:12)
	at DefaultSamCliProcessInvoker.invoke (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliInvoker.js:42:16)
	at SamCliInfoInvocation.<anonymous> (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliInfo.js:24:59)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliInfo.js:11:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliInfo.js:7:12)
	at SamCliInfoInvocation.execute (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliInfo.js:23:16)
	at DefaultSamCliValidatorContext.<anonymous> (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliValidator.js:128:37)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliValidator.js:11:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliValidator.js:7:12)
	at DefaultSamCliValidatorContext.getSamCliInfo (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliValidator.js:126:16)
	at DefaultSamCliValidator.<anonymous> (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliValidator.js:70:65)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/richali/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-0.3.0/out/src/shared/sam/cli/samCliValidator.js:8:58)
```

**Comment by bryceitoc9** [comment]
Confirmed that this is due to a bad SAM location. We need better error messaging for this. Additionally, we can look into adding a direct link into the `AWS: Detect SAM CLI` command in order to immediately prompt a user to select the correct location.

**Comment by justinmk3** [comment]
We automatically call `detectSamCli()` , which forces the value to a valid sam location.
