### ISSUE TITLE
Cannot run Helloworld application locally for Node.js

### ISSUE THREAD

**Issue by sahilkapoor89** [aws/aws-toolkit-vscode#743]
**Describe the bug**
When ever I try to run the sample Hello world application for node.js I get an error saying SAM build command failed

This issue is related to https://github.com/aws/aws-toolkit-jetbrains/issues/950

**To Reproduce**
OS: Windows
1. Create new AWS SAM application
2. Select nodejs 10.x
3. Select a folder in D: drive
4. enter application name
5. go to app.js and select run locally

**Expected behavior**
Function to run locally

**Logs:**
Starting SAM Application deployment...
Building SAM Application...
Error with child process: 2019-08-21 16:05:22 Building resource 'HelloWorldFunction'
,2019-08-21 16:05:22 Running NodejsNpmBuilder:NpmPack
,2019-08-21 16:05:24 Running NodejsNpmBuilder:CopyNpmrc
,2019-08-21 16:05:24 Running NodejsNpmBuilder:CopySource
,2019-08-21 16:05:24 Running NodejsNpmBuilder:NpmInstall
,2019-08-21 16:05:28 Running NodejsNpmBuilder:CleanUpNpmrc
,Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 103, in cli
    skip_pull_image, parameter_overrides, mode)  # pragma: no cover
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 151, in do_cli
    artifacts)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 143, in update_template
    artifact_relative_path = os.path.relpath(built_artifacts[logical_id], original_dir)
  File "ntpath.py", line 584, in relpath
ValueError: path is on mount 'C:', start on mount 'd:'
An error occurred while deploying a SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.

**Desktop (please complete the following information):**
 - OS: Windows
 - Visual Studio Code Version: 1.37.1
 - AWS Toolkit for Visual Studio Code Version: 1.0.0

**Comment by bryceitoc9** [comment]
Hi @sahilkapoor89 , thanks for writing in.

Looks like this might be an issue with the SAM CLI; I'd recommend taking a look at the issue here: https://github.com/awslabs/aws-sam-cli/issues/1336

In the meantime, can you try running your code out of the C:\ drive?

**Comment by sahilkapoor89** [comment]
@bryceitoc9 As per your suggestion I moved my code to the C:\ drive but still the build was failing with the same error. Finally I figured out that my VSCode was installed on the D:\ drive and once I moved VSCode to C:\ drive everything started working.
