### ISSUE TITLE
Unable to create a new SAM Application

### ISSUE THREAD

**Issue by vikashsingh3** [aws/aws-toolkit-vscode#977]
While trying to create a new SAM application getting an error message:
An error occurred while creating a new SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.

Toolkit log:
Error logs for this session are permanently stored in C:\Users\Vikash\AppData\Roaming\Code\logs\aws_toolkit\aws_toolkit_20200327T222217.log
2020-03-27 22:22:18 [INFO]: Retrieving AWS endpoint data
2020-03-27 22:22:18 [INFO]: OS:  Windows_NT x64 10.0.18362
Visual Studio Code Version:  1.43.2
AWS Toolkit for Visual Studio Code Version:  1.7.0

2020-03-27 22:22:18 [INFO]: SAM CLI location: D:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd
2020-03-27 22:22:20 [INFO]: Running command: D:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd --info
2020-03-27 22:23:16 [INFO]: Running command: D:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd init --name new-from-vs --runtime python3.8 --no-interactive --app-template hello-world --dependency-manager pip
2020-03-27 22:23:22 [ERROR]: Unexpected exitcode (1), expecting (0)
2020-03-27 22:23:22 [ERROR]: Error: undefined
2020-03-27 22:23:22 [ERROR]: stderr: SAM CLI now collects telemetry to better understand customer needs.

	You can OPT OUT and disable telemetry collection by setting the
	environment variable SAM_CLI_TELEMETRY=0 in your shell.
	Thanks for your help!

	Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

,
Cloning app templates from https://github.com/awslabs/aws-sam-cli-app-templates.git
,WARN: Can't clone app repo, git executable not found
Traceback (most recent call last):
  File "D:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 183, in _clone_new_app_templates
    [self._git_executable(), "clone", self._repo_url], cwd=tempdir, stderr=subprocess.STDOUT
  File "D:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 211, in _git_executable
    raise OSError("Cannot find git, was looking at executables: {}".format(options))
OSError: Cannot find git, was looking at executables: ['git', 'git.cmd', 'git.exe', 'git.bat']
,Error: Please verify your location. The following types of location are supported:

* Github: gh:user/repo (or) https://github.com/user/repo (or) git@github.com:user/repo.git
          For Git repositories, you must use location of the root of the repository.

* Mercurial: hg+ssh://hg@bitbucket.org/repo

* Http(s): https://example.com/code.zip

* Local Path: /path/to/code.zip
2020-03-27 22:23:22 [ERROR]: stdout: 
2020-03-27 22:23:22 [ERROR]: An error occurred while creating a new SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
2020-03-27 22:23:22 [ERROR]: Error creating new SAM Application Error: Error with child process: SAM CLI now collects telemetry to better understand customer needs.

	You can OPT OUT and disable telemetry collection by setting the
	environment variable SAM_CLI_TELEMETRY=0 in your shell.
	Thanks for your help!

	Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

,
Cloning app templates from https://github.com/awslabs/aws-sam-cli-app-templates.git
,WARN: Can't clone app repo, git executable not found
Traceback (most recent call last):
  File "D:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 183, in _clone_new_app_templates
    [self._git_executable(), "clone", self._repo_url], cwd=tempdir, stderr=subprocess.STDOUT
  File "D:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 211, in _git_executable
    raise OSError("Cannot find git, was looking at executables: {}".format(options))
OSError: Cannot find git, was looking at executables: ['git', 'git.cmd', 'git.exe', 'git.bat']
,Error: Please verify your location. The following types of location are supported:

* Github: gh:user/repo (or) https://github.com/user/repo (or) git@github.com:user/repo.git
          For Git repositories, you must use location of the root of the repository.

* Mercurial: hg+ssh://hg@bitbucket.org/repo

* Http(s): https://example.com/code.zip

* Local Path: /path/to/code.zip
	at Object.t.logAndThrowIfUnexpectedExitCode (c:\Users\Vikash\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.7.0\dist\extension.js:2:204623)
	at Object.<anonymous> (c:\Users\Vikash\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.7.0\dist\extension.js:2:6228986)
	at Generator.next (<anonymous>)
	at o (c:\Users\Vikash\.vscode\extensions\amazonwebservices.aws-toolkit-vscode-1.7.0\dist\extension.js:2:6228307)

-   OS: Windows 10 64-bit
-   Visual Studio Code Version: 1.43.2
-   AWS Toolkit Version: 1.7.0
-  SAM CLI, version 0.46.2

![image](https://user-images.githubusercontent.com/57470654/77756863-c95fab80-707b-11ea-8cda-d3a0385a0a46.png)

**Comment by awschristou** [comment]
Hello @vikashsingh3 , can you please check if you have git installed on your system? It appears that the SAM CLI was unable to locate it.

**Comment by vikashsingh3** [comment]
Hi Chris,

Thank you for your response. I installed GIT and is working now.
I was not able to see git was mentioned as prerequisites unless I
overlooked it.

Anyways, thank you so much for your help!
Have a great day!

Regards,
Vikash

**Comment by awschristou** [comment]
Thank you for following up to mention that installing git helped. I have passed feedback along to the SAM team to check their documented prerequisites.

**Comment by varshithvvs** [comment]
Hi Chris,

I have been facing a similar issue, however I have installed git following the process Vikash followed. But I still am facing the issue, Additionally I have also verified if git is added to the path as part of system variables

**Comment by justinmk3** [comment]
@varshithvvs  Can you open a new issue and share the logs? 

1. Set the Toolkit log level to "verbose": in VSCode settings search for "aws log level", then choose "verbose".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View AWS Toolkit Logs` command to get the logs.

**Comment by varshithvvs** [comment]
@justinmk3  I have opened a new issue, please find the following link for your reference: https://github.com/aws/aws-toolkit-vscode/issues/1593
